test/ui-testing/new_title.js
=> Fix check for new title

CHANGELOG.md, Instances.js, README.md, package.json, test/ui-testing/new_title.js
Align routing, permissions, ui-tests, meta-data.
=> Align code with new project name, inventory. UIIN-17.

Instances.js, ViewInstance.js, ViewItem.js, edit/InstanceForm.js, edit/holdings/HoldingsForm.js, edit/items/ItemForm.js
Updated pane headers to use IconButton and new Pane-props.
=> Fixed pane headers

Instances.js
=> FOLIO-398 tidy 1

ViewItem.js, edit/holdings/HoldingsForm.js, edit/items/ItemForm.js
Add parent record info to holdings, items headers
=> Align headings of forms, detailed views

CHANGELOG.md, edit/InstanceForm.js, edit/alternativeTitles.js, edit/classificationFields.js, edit/contributorFields.js, edit/descriptionFields.js, edit/identifierFields.js, edit/languageFields.js, edit/noteFields.js, edit/publicationFields.js, edit/seriesFields.js, edit/subjectFields.js, edit/urlFields.js, package.json
The `<FieldArray>`s of Instance Form have been switched to use the `<RepeatableField>` component from `stripes-components`. This results in a significant amount of clearing as many of the jsx portions have been reduced down to single components.
Also in this: I grouped the fields with Charlotte's help and placed them into `<Accordions>`
=> UIIN-52 implement repeatable field

CHANGELOG.md, edit/items/ItemForm.js
Fixes [UIIN-61](https://issues.folio.org/browse/UIIN-61).
=> enable and validate item-status field. Fixes UIIN-61

CHANGELOG.md, edit/holdings/HoldingsForm.js
Fixes [UIIN-60](https://issues.folio.org/browse/UIIN-60).
=> enable validation of holdings record. Fixes UIIN-60

CHANGELOG.md, Instances.js
Fixes [UIIN-59](https://issues.folio.org/browse/UIIN-59).
Hey, MARClemore! Can we go bar coding? 
What what what what? 
I'm gonna pop some tags
Only got a barcode in my search bar
I'm hunting, looking for a book now
This is freaking awesome
Nah, look up at a loan-list like, "What up? I got a big tome!"
And I'm pumped about the links on the checkout screen home
Request barcodes are so damn clicky
Librarians like, "Damn! I bet we got Z39.50."
=> Search by barcodes. Fixes UIIN-59

CHANGELOG.md, Instances.js
Fixes [UIIN-63](https://issues.folio.org/browse/UIIN-63).
=> sort contributor-types by name. Fixes UIIN-63

ViewInstance.js
Also add Collapse all link (WiP)
=> Keep 3rd panel open on select new instance row. Apply spinner.

CHANGELOG.md, edit/items/ItemForm.js
Refs [UIIN-61](https://issues.folio.org/browse/UIIN-61)
=> bug fix: require item-record's Material Type, Permanent Loan Type fields. Refs UIIN-61

package.json, test/ui-testing/new_title.js, test/ui-testing/stub.js, test/ui-testing/test.js
Remove repeating sort clicks, fix lint errors, add holdings and items coverage.
=> Ui testing

CHANGELOG.md, Instances.js, package.json
Re-fixes [UIIN-58](https://issues.folio.org/browse/UIIN-58). This was a regression inadvertently introduced in #100 / d9e3b8d565.
=> re-restoring show-single-record. Re-fixes UIIN-58

CHANGELOG.md, ViewInstance.js, ViewMetaData.js, package.json
Add dependency on mod-users for user names.
=> Move metadata section, add users' names. UIIN-97

CHANGELOG.md, Instances.js
Fixes [UIIN-104](https://issues.folio.org/browse/UIIN-104)
=> Lint. Fixes UIIN-104

CHANGELOG.md, ViewItem.js, edit/items/ItemForm.js, test/ui-testing/new_title.js
[https://issues.folio.org/browse/UIIN-27](https://issues.folio.org/browse/UIIN-27)
=> Clone an Item record. Fixes UIIN-27

CHANGELOG.md, ViewHoldingsRecord.js, edit/holdings/HoldingsForm.js
[https://issues.folio.org/browse/UIIN-26](https://issues.folio.org/browse/UIIN-26)
=> Clone a holding record. Fixes UIIN-26.

Instances.js
Specifically to make more clear that "Search All" is currently
searching three fields.
=> Tweak search field labels. UIIN-56.

package.json, settings/LoanTypesSettings.js, settings/MaterialTypesSettings.js
[This uses the new ControlledVocab functionality in this PR.](https://github.com/folio-org/stripes-smart-components/pull/118)
=> STCOM-228: Migrate LoanType and MaterialType settings to ControlledVocab

CHANGELOG.md, edit/InstanceForm.js, edit/contributorFields.js, package.json
Requires instance-storage v4.2 for new contributorTypeText field
=> Add contributor type to instance form. UIIN-92

Instances.js, Items.js, data/languages.js
"A foolish consistency is the hobgoblin of little minds, adored
by little statesmen and philosophers and divines and also ESLint."
-- RW Emerson
=> lint. use quotes consistently

CHANGELOG.md, Holdings.js, Items.js, ItemsPerHoldingsRecord.js, ViewInstance.js, ViewItem.js, translations/en.json
Show availability info on the item-details pane, including item status and, if any, links to open requests and the loan details. 
Fixes [UIIN-110](https://issues.folio.org/browse/UIIN-110)
=> Show availability info on item-details pane

Holdings.js
https://issues.folio.org/browse/UIIN-26
=> Fix cloning holding. Part of UIIN-26

CHANGELOG.md, ViewItem.js
https://issues.folio.org/browse/UIIN-142
=> Set cloned item's status to available. Fixes UIIN-142.

CHANGELOG.md, edit/holdings/HoldingsForm.js, edit/items/ItemForm.js
https://issues.folio.org/browse/UIIN-127
=> Migrate to hierarchical location end-point. Fixes UIIN-127

CHANGELOG.md, ViewItem.js
Refs [UIIN-110](https://issues.folio.org/browse/UIIN-110)
=> only show item-availability for open loans. Refs UIIN-110

edit/descriptionFields.js
Minimal change, trying out new PR regression test scheme.
=> Change labels in Instance form. UIIN-164

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIIN-171
=> Add location-units and locations to Okapi interfaces. Fixes UIIN-171.

CHANGELOG.md, ViewItem.js, edit/items/ItemForm.js
Fixes [UIIN-172](https://issues.folio.org/browse/UIIN-172)
=> handle i18n props correctly. Fixes UIIN-172

CHANGELOG.md, Jenkinsfile, ViewHoldingsRecord.js, ViewInstance.js, ViewItem.js, ViewMetadata.js, package.json
Refs [UIIN-173](https://issues.folio.org/browse/UIIN-173)
=> Favor metadata over metaData. Refs UIIN-173.

CHANGELOG.md, edit/holdings/HoldingsForm.js, edit/items/ItemForm.js
https://issues.folio.org/browse/UIIN-174
=> Fix holding and item forms. Fixes UIIN-174.

CHANGELOG.md, ViewItem.js
Refs [UIIN-110](https://issues.folio.org/browse/UIIN-110)
=> try harder to derive an item's status-date. Refs UIIN-110

ConnectedInstance/ApolloConnectedInstance.js, ConnectedInstance/ConnectedInstance.js, ConnectedInstance/StripesConnectedInstance.js, ConnectedInstance/index.js, ViewInstance.js
=> Use simple ConnectedInstance object

CHANGELOG.md, Holdings.js, Instances.js, ItemsPerHoldingsRecord.js, ViewHoldingsRecord.js, ViewItem.js, edit/items/ItemForm.js, package.json
https://issues.folio.org/browse/UIIN-182
=> Replace shelf location references with locations. Fixes UIIN-182.

package.json
Fixes UIIN-184.
(Of course, I can't actually _run_ the tests successfully; but that
seems to be just me, as Zak runs them without problems.)
=> Add "test" target that uses tests from ui-testing

settings/ContributorTypesSettings.js, settings/FormatsSettings.js, settings/ResourceTypesSettings.js, test/ui-testing/filters.js
UIIN-149,150,151: Column width formatting fails on columns not yet
existing in back-end, formatting rolled back while resolving data
loading and a display issue with some new reference data.
=> Temporary rollback while awaiting back-end update.

CHANGELOG.md, edit/alternativeTitles.js, edit/classificationFields.js, edit/contributorFields.js, edit/descriptionFields.js, edit/holdings/HoldingsForm.js, edit/identifierFields.js, edit/items/ItemForm.js, edit/languageFields.js, edit/noteFields.js, edit/publicationFields.js, edit/seriesFields.js, edit/subjectFields.js, edit/urlFields.js
Refs [STCOM-277](https://issues.folio.org/browse/STCOM-277)
=> update some stripes-components import paths

CHANGELOG.md, ViewItem.js, edit/holdings/HoldingsForm.js, edit/items/ItemForm.js, package.json
https://issues.folio.org/browse/UIIN-198
=> Enable un-setting a location. Fixes UIIN-198

edit/items/ItemForm.js
https://issues.folio.org/browse/UIIN-198
=> Fix temporary location field name. Part of UIIN-198

CHANGELOG.md, Instances.js
=> Increase the contributor-type limit from 100 to 400

CHANGELOG.md, Instances.js
Refs [UIIN-217](https://issues.folio.org/browse/UIIN-217)
=> provide defaults for props a plugin may override

Holdings.js, Instances.js, ItemsPerHoldingsRecord.js, ViewHoldingsRecord.js, ViewInstance.js, ViewItem.js, ViewMarc.js, edit/InstanceForm.js, edit/alternativeTitles.js, edit/childInstanceFields.js, edit/descriptionFields.js, edit/electronicAccessFields.js, edit/holdings/HoldingsForm.js, edit/holdings/holdingsStatementFields.js, edit/items/ItemForm.js, edit/items/noteFields.js, edit/items/pieceIdentifierFields.js, edit/languageFields.js, edit/parentInstanceFields.js, edit/publicationFields.js, edit/publicationFrequencyFields.js, edit/publicationRangeFields.js, edit/urlFields.js, index.js, package.json, referenceFormatters.js, test/ui-testing/new_title.js, test/ui-testing/stub.js, utils.js
Removes unnecessary `babel` packages, and adds needed `devDependencies`.
=> Clean up dependencies

ViewInstance.js
Likewise formatting contributors, identifiers in multicolumlist
=> Formatting publishers in table, instance details UIIN-284

ViewInstance.js, edit/InstanceForm.js, translations/ui-inventory/en.json
=> Move analytics relationships down to own accordion UIIN-318

CHANGELOG.md, test/ui-testing/filters.js
Fixes [UIIN-329](https://issues.folio.org/browse/UIIN-329)
=> fix case-sensitive tests

CHANGELOG.md, src/ViewInstance.js, translations/ui-inventory/en.json
https://issues.folio.org/browse/STRIPES-558
=> STRIPES-558 Remove notes helper app

translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/es.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/pt_BR.json
=> Update translation strings as of 20181005T195223

src/utils.js
=> Remove formatDate() util

CHANGELOG.md, test/ui-testing/inventorySearch.js
Accessible forms require you to click a search button to submit a query
rather than providing as-you-type results. So now we do that.
Refs [STCOM-354](https://issues.folio.org/browse/STCOM-354)
=> click "search" button in tests

translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/es.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/pt_BR.json
=> Update translation strings as of 20181026T143111

src/ViewHoldingsRecord.js, src/ViewInstance.js, src/ViewItem.js, translations/ui-inventory/en.json
Reverts folio-org/ui-inventory#342
=> Revert "Modify the copy and edit labels in inventory, refs UIIN-354"

test/ui-testing/inventorySearch.js
Hang search tests off `data-total-count` and `aria-label` instead of
using `title`. That still sorta sucks, but it sucks less.
Refs [STCOM-296](https://issues.folio.org/browse/STCOM-296)
=> tests should not use `title` attributes

src/ViewHoldingsRecord.js, src/edit/holdings/HoldingsForm.js, translations/ui-inventory/en.json
digitization policy, retention policy
=> Add two more holdings properties, view and form UIIN-234

CHANGELOG.md, package.json, src/Holdings.js, src/ItemsPerHoldingsRecord.js, src/ViewHoldingsRecord.js, test/bigtest/network/config.js, translations/ui-inventory/ar.json, translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en.json, translations/ui-inventory/es.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/pt_BR.json
- remove use of `platforms` end-point
- remove use of `holdingsRecord.electronicLocation`
=> Remove to-be-deprecated holdings data from the UI UIIN-388

src/ItemsPerHoldingsRecord.js, src/ViewInstance.js
Add a possibility to go to the holdings and item creation pages by route path
- Add `layer=createItem` query param which appears after click on "Add new item" button .
- Bind layer to the item creation page to this query param.
- Move layers components outside of the `ViewInstance` component general markup to be rendered like independent pages
=> STCOM-395: Add routing for holdings and item creation pages

Jenkinsfile, src/ViewItem.js, test/bigtest/network/config.js
WiP on Notes accordion content.
=> Layout notes four columns across UIIN-253

package.json, src/ViewInstance.js
inventory 8.0
instance-storage 6.0
holdings-storage 3.0
item-storage 7.0
=> Update dependencies on inventory APIs to latest.

src/edit/holdings/HoldingsForm.js
Also populate call number type select list
=> Add holdings type select list to form UIIN-232

CHANGELOG.md, Jenkinsfile, src/ViewHoldingsRecord.js, src/ViewInstance.js, src/ViewItem.js
Refs [STCOM-411](https://issues.folio.org/browse/STCOM-411)
=> move AppIcon import to @folio/stripes/core

CHANGELOG.md, test/ui-testing/inventorySearch.js, test/ui-testing/new_title.js
Changes to the aria attributes in MCL must be reflected in the
integration tests as well.
Refs [UIIN-474](https://issues.folio.org/browse/UIIN-474), [STCOM-365](https://issues.folio.org/browse/STCOM-365)
=> integration tests must accommodate MCL aria changes

test/bigtest/interactors/item-view-page.js
Refs [UIIN-480](https://issues.folio.org/browse/UIIN-480)
=> before calling whenLoaded, define whenLoaded

Jenkinsfile
This is PR to simply turn on tests running on CI
=> UIEN-480: Added test running to the Jenkinsfile

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIIN-491
=> Update circulation OKAPI interface to v7.0. Part of UIIN-491

translations/ui-inventory/ar.json, translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_SE.json, translations/ui-inventory/en_US.json, translations/ui-inventory/es.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/pt_BR.json, translations/ui-inventory/pt_PT.json, translations/ui-inventory/zh_CN.json
=> Update translation strings as of 20190225T222207

src/Items.js, src/ItemsPerHoldingsRecord.js
This PR should address the issue described in https://issues.folio.org/browse/UIIN-497
The item has to be created first before the item form is being closed.
=> Wait for item to be created before closing the form. Fixes UIIN-497

translations/ui-inventory/ar.json
=> Update translation strings as of 20190227T140407

src/Instances.js
Must be added on instances result view already or they are not ready
in time for the add-items and add-holdings forms.
=> Adds reference tables for holdings/items on instances UIIN-456 UIIN-457

src/edit/InstanceForm.js, src/edit/items/ItemForm.js
(translation files may still need updating ref FOLIO-1784)
=> Fixing 'required' settings on fields, remove double asterisks UIIN-493

translations/ui-inventory/pt_BR.json
=> Update translation strings as of 20190327T174151

CHANGELOG.md, src/Instances.js
These hard-coded numbers kill me, but 1,000 is better than 100 I guess
when it comes to retrieving things from lookup tables.
Refs [UIIN-413](https://issues.folio.org/browse/UIIN-413)
=> retrieve 1000 rows from lookup tables

translations/ui-inventory/ar.json, translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_SE.json, translations/ui-inventory/en_US.json, translations/ui-inventory/es.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/pt_BR.json, translations/ui-inventory/pt_PT.json, translations/ui-inventory/zh_CN.json
=> Update translation strings as of 20190401T154238

CHANGELOG.md, src/ViewHoldingsRecord.js, src/ViewInstance.js, src/ViewItem.js
The a11y prop for a `<Layer>` is `contentLabel`, not `label`.
=> provide correct a11y props to Layers

translations/ui-inventory/en_US.json
=> Update translation strings as of 20190426T133506

src/ViewItem.js
https://issues.folio.org/browse/UIREQ-253
=> Use item id instead of barcode when creating new request. Refs UIREQ-253

translations/ui-inventory/ar.json, translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_SE.json, translations/ui-inventory/en_US.json, translations/ui-inventory/es.json, translations/ui-inventory/es_419.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/pt_BR.json, translations/ui-inventory/pt_PT.json, translations/ui-inventory/zh_CN.json
=> Update translation strings as of 20190429T154045

CHANGELOG.md, src/Instances.js, test/bigtest/interactors/inventory.js, test/bigtest/network/config.js, test/bigtest/network/cql.js, test/bigtest/network/factories/holding.js, test/bigtest/network/factories/instance.js, test/bigtest/network/factories/item.js, test/bigtest/network/models/holding.js, test/bigtest/network/models/instance.js, test/bigtest/network/models/item.js, test/bigtest/tests/instances-index-test.js
https://issues.folio.org/browse/UIIN-143
=> Add ability to search by barcode. Part of UIIN-143

CHANGELOG.md, src/ViewHoldingsRecord.js
The acq stuff belongs in the acq accordion, not the notes accordion.
Refs [UIIN-506](https://issues.folio.org/browse/UIIN-506)
=> put acquisitions elements in correct accordion

translations/ui-inventory/en.json
Refs [UIIN-507](https://issues.folio.org/browse/UIIN-507)
=> change acquisitionFormat translation value

translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_SE.json, translations/ui-inventory/en_US.json, translations/ui-inventory/es.json, translations/ui-inventory/es_419.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/pt_PT.json
=> Update translation strings as of 20190501T184815

CHANGELOG.md, src/ViewItem.js, src/constants.js, src/utils.js, test/bigtest/network/config.js, test/bigtest/network/factories/holding.js, test/bigtest/network/factories/instance.js, test/bigtest/network/factories/item.js, test/bigtest/network/factories/loan.js, test/bigtest/network/models/loan.js, test/bigtest/network/serializers/holding.js, test/bigtest/network/serializers/item.js, test/bigtest/tests/instances-index-test.js, test/bigtest/tests/item-view-page-test.js
https://issues.folio.org/browse/UIIN-555
=> Add ability to mark Paged items as missing. Part of UIIN-555

CHANGELOG.md, src/constants.js, src/utils.js, test/bigtest/network/factories/instance.js, test/bigtest/tests/item-view-page-test.js
https://issues.folio.org/browse/UIIN-560
=> Mark In process items as missing. Part of UIIN-560

src/ViewItem.js
https://issues.folio.org/browse/UIREQ-253
=> Show link to request for items without barcode. Part of UIREQ-253

translations/ui-inventory/ar.json, translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_SE.json, translations/ui-inventory/en_US.json, translations/ui-inventory/es.json, translations/ui-inventory/es_419.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/pt_BR.json, translations/ui-inventory/pt_PT.json, translations/ui-inventory/zh_CN.json
=> Update translation strings as of 20190517T183537

src/edit/holdings/HoldingsForm.js
Refs [UIIN-506](https://issues.folio.org/browse/UIIN-506)
=> move edit-record items to correct accordion

translations/ui-inventory/ar.json, translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_SE.json, translations/ui-inventory/en_US.json, translations/ui-inventory/es.json, translations/ui-inventory/es_419.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/pt_BR.json, translations/ui-inventory/pt_PT.json, translations/ui-inventory/zh_CN.json
=> Update translation strings as of 20190520T224011

src/ViewItem.js, src/edit/items/ItemForm.js
https://issues.folio.org/browse/UIIN-568
=> Do not validate barcode for items without barcode. Part of UIIN-568

translations/ui-inventory/ar.json
=> Update translation strings as of 20190529T122422

CHANGELOG.md, src/Holdings.js, src/Items.js, src/ViewHoldingsRecord.js, test/bigtest/interactors/holdings-view-page.js, test/bigtest/interactors/item-view-page.js, test/bigtest/network/config.js, test/bigtest/network/factories/holding.js, test/bigtest/network/factories/instance.js, test/bigtest/network/scenarios/default.js, test/bigtest/tests/delete-item-available-test.js, test/bigtest/tests/delete-item-checked-out-test.js, test/bigtest/tests/delete-item-on-order-test.js, test/bigtest/tests/delete-item-with-open-request-test.js, test/bigtest/tests/holdings-view-page-test.js, test/bigtest/tests/instance-view-page-test.js, test/bigtest/tests/item-view-page-test.js, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-550
=> Check for dependencies when deleting holding record. Part of UIIN-550

CHANGELOG.md, src/Instances.js, test/bigtest/interactors/inventory.js, test/bigtest/tests/instances-index-test.js
Remove results display in case of there are not any search queries or filters in the scope of the [story](https://issues.folio.org/browse/UIIN-79)
=> UIIN-79: Remove results display by default

translations/ui-inventory/ar.json, translations/ui-inventory/es.json, translations/ui-inventory/es_419.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/pt_BR.json
=> Update translation strings as of 20190609T200038

CHANGELOG.md, src/ViewItem.js, src/edit/items/ItemForm.js, translations/ui-inventory/en.json
Change accordion header value from "Conditions" to "Condition" in the scope of the [ticket](https://issues.folio.org/browse/UIIN-576)
=> UIIN-576: Change accordion header value to Condition

CHANGELOG.md, src/edit/InstanceForm.js
https://issues.folio.org/browse/UIIN-496
=> Add validation to alternative title. Fixes UIIN-496.

translations/ui-inventory/ar.json, translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_SE.json, translations/ui-inventory/en_US.json, translations/ui-inventory/es.json, translations/ui-inventory/es_419.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/pt_BR.json, translations/ui-inventory/pt_PT.json, translations/ui-inventory/zh_CN.json
=> Update translation strings as of 20190611T141613

translations/ui-inventory/ar.json, translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_SE.json, translations/ui-inventory/en_US.json, translations/ui-inventory/es.json, translations/ui-inventory/es_419.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/pt_BR.json, translations/ui-inventory/pt_PT.json, translations/ui-inventory/zh_CN.json
=> Update translation strings as of 20190612T145704

translations/ui-inventory/ar.json, translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_SE.json, translations/ui-inventory/en_US.json, translations/ui-inventory/es.json, translations/ui-inventory/es_419.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/pt_BR.json, translations/ui-inventory/pt_PT.json, translations/ui-inventory/zh_CN.json
=> Update translation strings as of 20190614T145022

translations/ui-inventory/ar.json
=> Update translation strings as of 20190618T141239

CHANGELOG.md, src/ViewInstance.js, src/ViewItem.js
Refactored `getDerivedStateFromProps` to `accumulate: true` with componentDidMount in order to fix it. 
https://issues.folio.org/browse/UIIN-484
=> Fix item details retaining loan data for closed loan. Part of UIIN-484.

src/ViewInstance.js
This PR fixes the error when clicking the "View source" button.
=> UIIN-628: fix "View source" button

src/edit/instanceFormatFields.js, test/bigtest/tests/instance-edit-page-test.js
https://issues.folio.org/browse/UIIN-614
=> Remove asterisk from instance format. Part of UIIN-614

src/ViewItem.js, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-567
=> Fix instance title. Fixes UIIN-567

translations/ui-inventory/ar.json, translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_SE.json, translations/ui-inventory/en_US.json, translations/ui-inventory/es.json, translations/ui-inventory/es_419.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/pt_BR.json, translations/ui-inventory/pt_PT.json, translations/ui-inventory/zh_CN.json
=> Update translation strings as of 20190711T172340

CHANGELOG.md, src/ViewInstance.js
https://issues.folio.org/browse/UIIN-606
=> Change series format. Part of UIIN-606

src/ViewItem.js
The formatting was still incorrect. This PR should fix it.
https://issues.folio.org/browse/UIIN-567
=> Fix formatting. Part of UIIN-567.

src/Items.js, src/ViewInstance.js, src/withLocation.js, test/bigtest/interactors/inventory.js, test/bigtest/tests/instances-index-test.js, test/bigtest/tests/item-view-page-test.js
https://issues.folio.org/browse/UIIN-616
=> Carry over search and sort params when opening and closing an item. Fixes UIIN-616

src/constants.js, src/edit/items/ItemForm.js, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-458
=> Populate item damage status select. Part of UIIN-458

translations/ui-inventory/ar.json, translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_SE.json, translations/ui-inventory/en_US.json, translations/ui-inventory/es.json, translations/ui-inventory/es_419.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/pt_BR.json, translations/ui-inventory/pt_PT.json, translations/ui-inventory/zh_CN.json
=> Update translation strings as of 20190718T013203

src/edit/items/ItemForm.js
https://issues.folio.org/browse/UIIN-458
=> Set damaged status state when status changes. Part of UIIN-458

CHANGELOG.md, src/edit/contributorFields.js
https://issues.folio.org/browse/UIIN-620
=> Mark contributor name field as required. Part of UIIN-620.

CHANGELOG.md, src/ViewHoldingsRecord.js, src/ViewInstance.js, src/ViewItem.js
Don't hide the metadata component when there is no data.
Fixes [UIIN-626](https://issues.folio.org/browse/UIIN-626)
=> UIIN-626 always show metadata component

translations/ui-inventory/ar.json, translations/ui-inventory/zh_CN.json
=> Update translation strings as of 20190718T220243

CHANGELOG.md, src/ViewItem.js
https://issues.folio.org/browse/UIIN-651
=> Display Item damage status data. Fixes UIIN-651.

test/ui-testing/new-title.js
The structure of the `notes` field has changed.
Refs [UIIN-654](https://issues.folio.org/browse/UIIN-654)
=> UIIN-654 fix nightmare tests

CHANGELOG.md, package.json, src/Instances.js, src/components/RepeatableField/FieldRow.js, src/components/RepeatableField/RepeatableField.js, src/components/RepeatableField/readme.md, src/edit/InstanceForm.js, src/edit/components/PrimaryToggleButton/PrimaryToggleButton.js, src/edit/components/PrimaryToggleButton/readme.md, src/edit/holdings/HoldingsForm.js, src/edit/instanceFormatFields.js, src/edit/items/ItemForm.js, src/edit/languageFields.js, src/settings/StatisticalCodeSettings.js, src/utils.js, src/withLocation.js
https://issues.folio.org/browse/UIIN-668
=> Refactor forms to use Final Form. Part of UIIN-668. 

src/ItemsPerHoldingsRecord.js, src/ViewInstance.js, src/components/RepeatableField/FieldRow.js, src/edit/holdings/HoldingsForm.js, src/edit/holdings/note.js, src/edit/items/ItemForm.js
Correctly format props in order to clean up the console a bit.
=> js console cleanup

CHANGELOG.md, src/ViewItem.js, src/edit/formUtils.js, src/edit/holdings/HoldingsForm.js, src/edit/items/ItemForm.js, src/utils.js
https://issues.folio.org/browse/UIIN-653
=> Refactor item's copy number to a single field. Part of UIIN-653

src/Items.js, test/bigtest/interactors/instance-view-page.js, test/bigtest/interactors/inventory.js, test/bigtest/tests/instance-view-page-test.js
Link only the barcode, not the entire row. 
Fixes [UIIN-660](https://issues.folio.org/browse/UIIN-660)
=> UIIN-660 link barcode instead of row

translations/ui-inventory/ar.json
=> Update translation strings as of 20190807T131714

src/Filters/Filters.js, src/Filters/index.js, src/Instances.js, src/constants.js, src/utils.js, test/bigtest/interactors/inventory.js, test/bigtest/network/config.js, test/bigtest/network/factories/instance-type.js, test/bigtest/tests/instances-index-test.js
This PR updates inventory search filters: https://issues.folio.org/browse/UIIN-596
=> Update filters. Part of UIIN-596

translations/ui-inventory/ar.json, translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_SE.json, translations/ui-inventory/en_US.json, translations/ui-inventory/es.json, translations/ui-inventory/es_419.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/pt_BR.json, translations/ui-inventory/pt_PT.json, translations/ui-inventory/zh_CN.json
=> Update translation strings as of 20190815T130307

test/ui-testing/filters.js, test/ui-testing/new-title.js, test/ui-testing/search.js
The structure of the language filters changed in #669 so the integration
test needs to accommodate that.
Remove unused variables in new-title.
Make sure the search field is cleared before using it in search.
Refs [UIIN-671](https://issues.folio.org/browse/UIIN-671)
=> UIIN-671 failed integration test followup

CHANGELOG.md, src/Instances.js, src/ViewItem.js
Fix notes selector on item create form.
https://issues.folio.org/browse/UIIN-669
=> Fix notes selector on item create form. Fixes UIIN-669.

CHANGELOG.md, package.json, src/Items.js
https://issues.folio.org/browse/UIIN-177
=> Add ability to copy item's barcode to clipboard. Part of UIIN-177

src/Items.js
This PR fixes clipboard icon. 
https://issues.folio.org/browse/UIIN-177
=> Fix clipboard icon. Part of UIIN-177

package.json, src/ViewInstance.js, src/ViewMarc.js
UIIN-675: ViewSource shows the same record when record changes without ViewRecord closing :: FIXED
=> UIIN-675: ViewSource shows the same record when record changes without ViewRecord closing :: FIXED

translations/ui-inventory/pt_BR.json
=> Update translation strings as of 20190819T080537

translations/ui-inventory/ar.json, translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_SE.json, translations/ui-inventory/en_US.json, translations/ui-inventory/es.json, translations/ui-inventory/es_419.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/pt_BR.json, translations/ui-inventory/pt_PT.json, translations/ui-inventory/zh_CN.json
=> Update translation strings as of 20190823T083240

CHANGELOG.md, package.json
Release module for the FOLIO 2019Q3.2. Refs [UIIN-718](https://issues.folio.org/browse/UIIN-718).
=> Release v1.12.0

translations/ui-inventory/ar.json, translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_SE.json, translations/ui-inventory/en_US.json, translations/ui-inventory/es.json, translations/ui-inventory/es_419.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/pt_BR.json, translations/ui-inventory/pt_PT.json, translations/ui-inventory/zh_CN.json
=> Update translation strings as of 20190913T225241

translations/ui-inventory/ar.json, translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_SE.json, translations/ui-inventory/en_US.json, translations/ui-inventory/es.json, translations/ui-inventory/es_419.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/hu.json, translations/ui-inventory/pt_PT.json
=> Update translation strings as of 20190918T144452

package.json
Update acceptable circulation APIs to include v8 so we can get new changes to circulation rules.
Refs [UIIN-727](https://issues.folio.org/browse/UIIN-727)
=> UIIN-727 update circulation API to v8

package.json
Restores folio-org/ui-inventory#709 by reverting folio-org/ui-inventory#712
=> Restore "UIIN-727 update circulation API to v8"

CHANGELOG.md, src/Holdings.js
https://issues.folio.org/browse/UIIN-723
=> Increase limit for holdings to 1000. Refs UIIN-723

translations/ui-inventory/ar.json, translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_SE.json, translations/ui-inventory/en_US.json, translations/ui-inventory/es.json, translations/ui-inventory/es_419.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/pt_BR.json, translations/ui-inventory/pt_PT.json, translations/ui-inventory/ru.json, translations/ui-inventory/zh_CN.json, translations/ui-inventory/zh_TW.json
=> Update translation strings as of 20191028T151017

src/ViewItem.js, src/constants.js
https://issues.folio.org/browse/UIIN-798
##Purpose
Add support of new status "Open - Awaiting delivery status"
##Screenshots
=> UIIN-798: Add Open - Awaiting delivery status to requests status filter

translations/ui-inventory/ar.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/pt_BR.json
=> Update translation strings as of 20191104T173556

translations/ui-inventory/ar.json, translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_SE.json, translations/ui-inventory/en_US.json, translations/ui-inventory/es.json, translations/ui-inventory/es_419.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/ja.json, translations/ui-inventory/pt_BR.json, translations/ui-inventory/pt_PT.json, translations/ui-inventory/ru.json, translations/ui-inventory/zh_CN.json, translations/ui-inventory/zh_TW.json
=> Update translation strings as of 20191106T134035

src/ViewInstance.js
Add alphabetical sort by note types
=> UIIN-643: Update sort for instance notes

CHANGELOG.md, package.json, src/ViewItem.js, src/components/ItemFilters/ItemFilters.js, src/constants.js, src/utils.js, src/views/ItemsView.js, test/bigtest/interactors/filters/checkbox-filter.js, test/bigtest/interactors/filters/index.js, test/bigtest/interactors/instance-edit-page.js, test/bigtest/interactors/routes/items-route.js, test/bigtest/network/config.js, test/bigtest/network/scenarios/item-filters.js, test/bigtest/tests/filters/items/item-status-filter-test.js, translations/ui-inventory/en.json
Filter item records by item status. Part of UIIN-771.
https://issues.folio.org/browse/UIIN-771
=> Filter item records by item status. Part of UIIN-771

package.json, src/constants.js, src/routes/InstancesRoute.js, test/bigtest/interactors/filters/index.js, test/bigtest/interactors/filters/searchfield-filter.js, test/bigtest/interactors/holdings-view-page.js, test/bigtest/interactors/routes/instances-route.js, test/bigtest/network/config.js, test/bigtest/network/scenarios/instances-filters.js, test/bigtest/tests/filters/instances/search-field-filter-test.js, translations/ui-inventory/en.json
Add ability to search by using query language. 
https://issues.folio.org/browse/UIIN-724
=> Add ability to search by using query language. Part of UIIN-724

src/constants.js
https://issues.folio.org/browse/UIIN-602
=> Fix searching titles for words out of order. Part of UIIN-602

CHANGELOG.md, src/constants.js, src/routes/ItemsRoute.js, test/bigtest/interactors/routes/items-route.js, test/bigtest/network/scenarios/item-filters.js, test/bigtest/tests/filters/items/search-field-filter-test.js
The work here is pretty much almost the same as what we did under instances segment.
https://issues.folio.org/browse/UIIN-869
=> Add ability to search by cql from the item segment. Parf of UIIN-869.

CHANGELOG.md, src/constants.js, src/routes/HoldingsRoute.js, src/routes/InstancesRoute.js, src/routes/ItemsRoute.js, src/utils.js, test/bigtest/interactors/routes/holdings-route.js, test/bigtest/network/scenarios/holdings-filters.js, test/bigtest/tests/filters/holdings/search-field-filter-test.js
The work here is pretty much almost the same as what we did under instances segment and items segment.
https://issues.folio.org/browse/UIIN-868
=> Add ability to search by cql from the holding segment. Part of UIIN-868.

CHANGELOG.md, src/ViewInstance.js
https://issues.folio.org/browse/UIIN-859
=> Add support for new search segments in ViewInstance route. Part of UIIN-859

CHANGELOG.md, src/constants.js
https://issues.folio.org/browse/UIIN-717
=> UIIN-717: Change instance all/keyword search to use new keyword index

CHANGELOG.md, src/ViewInstance.js
https://issues.folio.org/browse/UIIN-846
=> UIIN-846: Display 'status updated' date/time

CHANGELOG.md, src/constants.js, src/routes/HoldingsRoute.js, src/routes/InstancesRoute.js, src/utils.js, test/bigtest/network/scenarios/holdings-filters.js, test/bigtest/tests/filters/holdings/search-field-filter-test.js
https://issues.folio.org/browse/UIIN-848
=> Add search options to holdings segment. Part of UIIN-848.

translations/ui-inventory/ar.json, translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_SE.json, translations/ui-inventory/en_US.json, translations/ui-inventory/es.json, translations/ui-inventory/es_419.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/he.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/ja.json, translations/ui-inventory/pt_BR.json, translations/ui-inventory/pt_PT.json, translations/ui-inventory/ru.json, translations/ui-inventory/zh_CN.json, translations/ui-inventory/zh_TW.json
=> Update translation strings as of 20191122T195518

CHANGELOG.md, src/ViewItem.js, src/edit/items/ItemForm.js
https://issues.folio.org/browse/UIIN-863
=> UIIN-863: Show effective location at top of item record

src/constants.js, src/routes/ItemsRoute.js
https://issues.folio.org/browse/UIIN-848
=> Cleanup ISBN search. Part of UIIN-848

CHANGELOG.md, src/ItemsPerHoldingsRecord.js, src/ViewHoldingsRecord.js, src/ViewItem.js, src/utils.js
https://issues.folio.org/browse/UIIN-884
=> UIIN-884: Display complete call number in holdings headers

src/ViewItem.js, src/settings/index.js, src/utils.js
Added a check for an empty element
Added function for getting FormattedTime component
=> UIIN-828: Adjust check for an empty value

CHANGELOG.md, package.json, src/ViewItem.js, src/edit/items/ItemForm.js, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-750
Please merge after https://github.com/folio-org/stripes-util/pull/20 is merged.
=> Display effective call number string at the top of the item record. Part of UIIN-750

src/ViewItem.js, src/edit/items/ItemForm.js
https://issues.folio.org/browse/UIIN-750
=> Adjust effectiveCallNumber. Part of UIIN-750

src/ViewItem.js, src/edit/items/ItemForm.js
https://issues.folio.org/browse/UIIN-750
=> Update effectiveCallNumber. Part of UIIN-750

CHANGELOG.md, src/components/InstanceFilters/InstanceFilters.js, src/utils.js, test/bigtest/interactors/inventory.js, test/bigtest/tests/filters/instances/resource-type-filter-test.js
https://issues.folio.org/browse/UIIN-193
=> Refactor Resource Type filter on instances segment. Part of UIIN-193.

translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-888
=> UIIN-888: Improve message during item deletion.

CHANGELOG.md, src/ViewItem.js, test/bigtest/interactors/item-view-page.js, test/bigtest/network/factories/item.js, test/bigtest/network/factories/service-point.js, test/bigtest/network/factories/user.js, test/bigtest/network/models/service-point.js, test/bigtest/tests/item-view-page-test.js, translations/ui-inventory/en.json
Show most recent check in on item record. [Story](https://issues.folio.org/browse/UIIN-749).
**Screenshot**
=> UIIN-749: Show most recent check in on item record

CHANGELOG.md, src/ViewItem.js, test/bigtest/interactors/item-view-page.js, test/bigtest/network/config.js, test/bigtest/tests/item-view-page-test.js
Fix display of information in the "Loan and availability" section when the item's status is "Missing". [Story](https://issues.folio.org/browse/UIIN-913).
=> UIIN-913: Fix display of information when the item's status is 'Missing'

CHANGELOG.md, src/components/InstanceFilters/InstanceFilters.js, src/views/InstancesView.js, test/bigtest/interactors/inventory.js, test/bigtest/tests/filters/instances/format-filter-test.js
https://issues.folio.org/browse/UIIN-820
=> Add filter for instance formats. Part of UIIN-820

src/utils.js
https://issues.folio.org/browse/UIIN-820
=> Fix order of found items. Part of UIIN-820

CHANGELOG.md, src/constants.js, test/bigtest/network/config.js, test/bigtest/network/factories/instance.js, test/bigtest/tests/filters/instances/search-field-filter-test.js
Add ability to search by Instance HRID (Instance segment). Story [UIIN-899](https://issues.folio.org/browse/UIIN-899).
=> UIIN-899: Search by Instance HRID (Instance segment)

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/reports/InstancesIdReport.js, src/reports/index.js, src/routes/HoldingsRoute.js, src/routes/InstancesRoute.js, src/routes/ItemsRoute.js, src/routes/buildManifestObject.js, src/routes/withData.js, test/bigtest/interactors/inventory.js, test/bigtest/tests/export-to-csv-test.js, translations/ui-inventory/en.json
Add instances UIIDs saving to csv file in the scope of the [story](https://issues.folio.org/browse/UIDEXP-1).
=> UIDEXP-1: Add saving instances UIIDS to csv file

CHANGELOG.md, src/constants.js, test/bigtest/network/config.js, test/bigtest/network/scenarios/item-filters.js, test/bigtest/tests/filters/items/search-field-filter-test.js
Add ability to search by Item HRID (Item segment). Story [UIIN-901](https://issues.folio.org/browse/UIIN-901).
=> UIIN-901: Search by Item HRID (Item segment)

CHANGELOG.md, src/constants.js, test/bigtest/network/config.js, test/bigtest/network/factories/holding.js, test/bigtest/tests/filters/holdings/search-field-filter-test.js
Add ability to search by Holdings HRID (Holdings segment). Story [UIIN-900](https://issues.folio.org/browse/UIIN-900).
=> UIIN-900: Search by Holdings HRID (Holdings segment)

translations/ui-inventory/it_IT.json
=> Update translation strings as of 20200127T201424

CHANGELOG.md, src/routes/withData.js
Refs [UIIN-819](https://issues.folio.org/browse/UIIN-819)
=> UIIN-819 retrieve up to 2000 statistical codes

translations/ui-inventory/pt_BR.json
=> Update translation strings as of 20200202T214053

CHANGELOG.md, src/components/InstanceFilters/InstanceFilters.js, src/constants.js, src/views/InstancesView.js, test/bigtest/interactors/inventory.js, test/bigtest/tests/filters/instances/mode-filter-test.js
Add filter for modes of issuance. Story [UIIN-823](https://issues.folio.org/browse/UIIN-823).
**Demo**
=> UIIN-823: Add filter for modes of issuance

CHANGELOG.md, src/ItemsPerHoldingsRecord.js, src/ViewInstance.js
https://issues.folio.org/browse/UIIN-953
=> UIIN-953: Fix search and filter pane when viewing a holdings record

CHANGELOG.md, translations/ui-inventory/en.json
Fix translation for "Awaiting delivery" item status. [Story](https://issues.folio.org/browse/UIIN-976).
**Screenshot**
=> UIIN-976: Fix translation for "Awaiting delivery" item status.

src/ViewInstance.js
https://issues.folio.org/browse/UIIN-953
The work done under UIIN-953 was not working correctly when items or holdings search segment was used. This is something @SergiyVSergiyenko found and also fixed. Thank you @SergiyVSergiyenko!
=> Refactor goBack based of feedback. Part of UIIN-953

CHANGELOG.md, src/ViewMarc.js
Refs [UIIN-980](https://issues.folio.org/browse/UIIN-980), [UIIN-986](https://issues.folio.org/browse/UIIN-986)
=> UIIN-980: Fix marc fields rendering

translations/ui-inventory/ar.json, translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_SE.json, translations/ui-inventory/en_US.json, translations/ui-inventory/es.json, translations/ui-inventory/es_419.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/he.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/ja.json, translations/ui-inventory/pt_BR.json, translations/ui-inventory/pt_PT.json, translations/ui-inventory/ru.json, translations/ui-inventory/ur.json, translations/ui-inventory/zh_CN.json, translations/ui-inventory/zh_TW.json
=> Update translation strings as of 20200217T172736

CHANGELOG.md, src/components/HoldingsRecordFilters/HoldingsRecordFilters.js, src/components/InstanceFilters/InstanceFilters.js, src/components/ItemFilters/ItemFilters.js
This PR also takes care of UIIN-968, UIIN-969, UIIN-970.
https://issues.folio.org/browse/UIIN-967
https://issues.folio.org/browse/UIIN-968
https://issues.folio.org/browse/UIIN-969
https://issues.folio.org/browse/UIIN-970
=> UIIN-967: Filter instance, holding and item records by suppress: No

CHANGELOG.md, src/components/InstanceFilters/InstanceFilters.js, src/components/InstanceFilters/instanceFilterRenderer.js, src/filterConfig.js
https://issues.folio.org/browse/UIIN-824
=> UIIN-824: filter instances by nature of content

CHANGELOG.md, src/filterConfig.js, test/bigtest/network/config.js, test/bigtest/network/factories/holding.js, test/bigtest/tests/filters/holdings/search-field-filter-test.js, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-858
=> UIIN-858: Filter instance by Call number, eye readable via holdings segment

CHANGELOG.md, src/filterConfig.js, test/bigtest/network/config.js, test/bigtest/network/factories/item.js, test/bigtest/tests/filters/items/search-field-filter-test.js, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-990
=> UIIN-990: Filter instance by call number via items segment

CHANGELOG.md, package.json, src/ViewInstance.js, src/components/ConnectedTitle/ConnectedTitle.js, src/components/ConnectedTitle/index.js, src/components/InstancePlugin/InstancePlugin.js, src/components/InstancePlugin/index.js, src/components/TitleLabel/TitleLabel.js, src/components/TitleLabel/index.js, src/components/UnconnectedTitle/UnconnectedTitle.js, src/components/UnconnectedTitle/index.js, src/components/index.js, src/constants.js, src/contexts/DataContext.js, src/edit/InstanceForm.js, src/edit/precedingTitleFields.js, src/referenceFormatters.js, src/routes/InstancesRoute.js, src/routes/withData.js, src/utils.js, test/bigtest/helpers/setup-application.js, test/bigtest/interactors/instance-edit-page.js, test/bigtest/tests/instance-edit-page-test.js, translations/ui-inventory/en.json
This is the first story related to preceding/succeeding connected and unconnected titles.
This one should take care of preceding connected titles described in https://issues.folio.org/browse/UIIN-960
=> UIIN-960 - Enhance preceding connected titles

CHANGELOG.md, src/ViewInstance.js, src/components/ConnectedTitle/ConnectedTitle.js, src/components/InstancesList/InstancesList.js, src/components/UnconnectedTitle/UnconnectedTitle.js, src/edit/precedingTitleFields.js, src/routes/InstancesRoute.js, src/routes/withData.js, src/utils.js, test/bigtest/interactors/instance-edit-page.js, test/bigtest/network/config.js, test/bigtest/network/scenarios/default.js, test/bigtest/tests/instance-edit-page-test.js
Add support for unconnected preceding titles.
https://issues.folio.org/browse/UIIN-950
=> UIIN-950: Add support for unconnected preceding titles

translations/ui-inventory/ar.json, translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_SE.json, translations/ui-inventory/en_US.json, translations/ui-inventory/es.json, translations/ui-inventory/es_419.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/he.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/ja.json, translations/ui-inventory/pt_BR.json, translations/ui-inventory/pt_PT.json, translations/ui-inventory/ru.json, translations/ui-inventory/ur.json, translations/ui-inventory/zh_CN.json, translations/ui-inventory/zh_TW.json
=> Update translation strings as of 20200312T133304

src/components/ConnectedTitle/ConnectedTitle.js, src/components/TitleField/TitleField.js
This is one more change I noticed after UIIN-963 was already merged. It fixes title link on the instance form.
https://issues.folio.org/browse/UIIN-963
=> Fix title link on instance form. Refs UIIN-963

translations/ui-inventory/ar.json, translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_SE.json, translations/ui-inventory/en_US.json, translations/ui-inventory/es.json, translations/ui-inventory/es_419.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/he.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/ja.json, translations/ui-inventory/pt_BR.json, translations/ui-inventory/pt_PT.json, translations/ui-inventory/ru.json, translations/ui-inventory/ur.json, translations/ui-inventory/zh_CN.json, translations/ui-inventory/zh_TW.json
=> Update translation strings as of 20200314T132532

translations/ui-inventory/ru.json
=> Update translation strings as of 20200316T134017

.gitignore, package.json, src/ViewInstance.js, src/index.js, src/routes/QuickMarcRoute.js, src/routes/index.js, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIQM-1 …
=> UIQM-1 Open quickMARC editor from instance record

translations/ui-inventory/en.json
https://issues.folio.org/browse/UIQM-1
=> UIQM-1 fix edit quickMarc action label

CHANGELOG.md, package.json, src/edit/items/ItemForm.js, src/views/ItemView.js
https://issues.folio.org/browse/UIIN-1021
It turned out that this also fixes a bug described in https://issues.folio.org/browse/UIIN-1029
=> UIIN-1021: Import stripes-util via stripes

package.json, src/ViewInstance.js
https://issues.folio.org/browse/UIQM-9 …
=> UIQM-9 quickMARC permissions

Jenkinsfile, test/bigtest/interactors/holdings-create-page.js, test/bigtest/interactors/holdings-edit-page.js, test/bigtest/interactors/holdings-view-page.js, test/bigtest/interactors/instance-create-page.js, test/bigtest/interactors/instance-edit-page.js, test/bigtest/interactors/instance-view-page.js, test/bigtest/interactors/inventory.js, test/bigtest/interactors/item-create-page.js, test/bigtest/interactors/item-edit-page.js, test/bigtest/interactors/item-page.js, test/bigtest/interactors/item-view-page.js, test/bigtest/network/config.js, test/bigtest/tests/filters/holdings/search-field-filter-test.js, test/bigtest/tests/filters/instances/search-field-filter-test.js, test/bigtest/tests/filters/items/item-status-filter-test.js, test/bigtest/tests/filters/items/search-field-filter-test.js, test/bigtest/tests/holdings-view-page-test.js, test/bigtest/tests/instances-index-test.js, test/bigtest/tests/item-edit-page-test.js
https://issues.folio.org/browse/UIIN-1005
* Refactor `HeaderDropdown` interactor
* Added some timeouts 
* Cleanup some tests to bring them up to date with the actual code
The tests were passing for me locally but it seems like they also fail from time to time (similar to what is happening in ui-users).
=> UIIN-1005: Turn on tests

translations/ui-inventory/ar.json, translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_SE.json, translations/ui-inventory/en_US.json, translations/ui-inventory/es.json, translations/ui-inventory/es_419.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/he.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/ja.json, translations/ui-inventory/pt_BR.json, translations/ui-inventory/pt_PT.json, translations/ui-inventory/ru.json, translations/ui-inventory/ur.json, translations/ui-inventory/zh_CN.json, translations/ui-inventory/zh_TW.json
=> Update translation strings as of 20200319T202257

PULL_REQUEST_TEMPLATE.md, src/ViewInstance.js, test/bigtest/interactors/instance-view-page.js, test/bigtest/tests/instance-view-page-test.js
https://issues.folio.org/browse/UIQM-12 …
=> UIQM-12 Edit in quickMARC when metadata source is MARC

translations/ui-inventory/ar.json, translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_SE.json, translations/ui-inventory/en_US.json, translations/ui-inventory/es.json, translations/ui-inventory/es_419.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/he.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/ja.json, translations/ui-inventory/pt_BR.json, translations/ui-inventory/pt_PT.json, translations/ui-inventory/ru.json, translations/ui-inventory/ur.json, translations/ui-inventory/zh_CN.json, translations/ui-inventory/zh_TW.json
=> Update translation strings as of 20200403T124750

translations/ui-inventory/ru.json, translations/ui-inventory/ur.json
=> Update translation strings as of 20200406T162815

translations/ui-inventory/ar.json, translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_SE.json, translations/ui-inventory/en_US.json, translations/ui-inventory/es.json, translations/ui-inventory/es_419.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/he.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/ja.json, translations/ui-inventory/pt_BR.json, translations/ui-inventory/pt_PT.json, translations/ui-inventory/ru.json, translations/ui-inventory/ur.json, translations/ui-inventory/zh_CN.json, translations/ui-inventory/zh_TW.json
=> Update translation strings as of 20200409T134057

CHANGELOG.md, src/filterConfig.js, test/bigtest/network/config.js, test/bigtest/tests/filters/holdings/search-field-filter-test.js, test/bigtest/tests/filters/instances/search-field-filter-test.js, test/bigtest/tests/filters/items/search-field-filter-test.js, translations/ui-inventory/en.json
This new option 'ISNB, normalized' allows searching for Instance records by the "normalized" value of 'ISBN' and 'Invalid ISBN' identifiers. Story [UIIN-647](https://issues.folio.org/browse/UIIN-647).
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …
=> UIIN-647: Add ability to search by `ISBN, normalized` option

CHANGELOG.md, src/ViewInstance.js, test/bigtest/interactors/instance-view-page.js, test/bigtest/tests/instance-view-page-test.js
https://issues.folio.org/browse/UIIN-1024 …
=> UIIN-1024 Instance. Remove The Edit pen icon in the top pane

CHANGELOG.md, src/views/ItemView.js, test/bigtest/interactors/item-view-page.js, test/bigtest/tests/item-view-page-test.js
https://issues.folio.org/browse/UIIN-1026 …
=> UIIN-1026 Item. Remove The Edit pen icon in the top main pane

CHANGELOG.md, src/ViewHoldingsRecord.js
https://issues.folio.org/browse/UIIN-1025 …
=> UIIN-1025  Holdings. Remove The Edit pen icon in the top main pane.

src/ViewInstance.js
https://issues.folio.org/browse/UIIN-1077
Code was duplicated inadvertently during a previous merge.
=> UIIN-1077: Remove duplicate code

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/routes/buildManifestObject.js, test/bigtest/helpers/wait.js, test/bigtest/interactors/inventory.js, test/bigtest/tests/export-to-csv-test.js, translations/ui-inventory/en.json
Show error callout when saving file with the instance UUIDs fails in the scope of the [UIDEXP-55](https://issues.folio.org/browse/UIDEXP-55).
- API error is simulated with devtools
Ideally, all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to …
=> UIDEXP-55: Show error callout when saving file with the instance UUIDs fails

CHANGELOG.md, src/components/InstanceFilters/InstanceFilters.js, src/filterConfig.js, test/bigtest/interactors/filters/date-range-filter.js, test/bigtest/interactors/filters/index.js, test/bigtest/interactors/inventory.js, test/bigtest/network/config.js, test/bigtest/tests/filters/instances/instance-filters-test.js, translations/ui-inventory/en.json
Add the ability to filter instances by date updated. Story [UIIN-790](https://issues.folio.org/browse/UIIN-790).
The `Date updated` filter implementation was based upon the use of the DateRangeFilter component from the `stripes-smart-components` module.
=> UIIN-790: Add filter for instance date updated

CHANGELOG.md, src/constants.js, translations/ui-inventory/en.json
Add ability to search item by claimed returned status.
https://issues.folio.org/browse/UIIN-957
=> UIIN-957: Add ability to search item by claimed returned status

translations/ui-inventory/ru.json
=> Update translation strings as of 20200521T142352

translations/ui-inventory/fr_FR.json
=> Update translation strings as of 20200526T141248

src/utils.js
I thought I fixed this one in https://github.com/folio-org/ui-inventory/pull/1032 but apparently I didn't exactly opposite to what that issue was describing 😮. So this PR should actually address it.
https://issues.folio.org/browse/UIIN-891
=> UIIN-891: Do not show marked missing, or withdrawn for claimed returned

CHANGELOG.md, package.json, src/views/ItemView.js, test/bigtest/helpers/monkey-patch-run.js, test/bigtest/index.js, test/bigtest/interactors/item-view-page.js, test/bigtest/network/config.js
Add permission for marking an item withdrawn.
This PR also includes some additional work to make sure the BigTest tests are passing.
https://issues.folio.org/browse/UIIN-889
=> UIIN-889: Add permission for marking an item withdrawn

translations/ui-inventory/ar.json, translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_SE.json, translations/ui-inventory/en_US.json, translations/ui-inventory/es.json, translations/ui-inventory/es_419.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/he.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/ja.json, translations/ui-inventory/pt_BR.json, translations/ui-inventory/pt_PT.json, translations/ui-inventory/ru.json, translations/ui-inventory/ur.json, translations/ui-inventory/zh_CN.json, translations/ui-inventory/zh_TW.json
=> Update translation strings as of 20200608T134746

CHANGELOG.md, src/components/TitleField/TitleField.js, src/components/UnconnectedTitle/UnconnectedTitle.js, src/edit/InstanceForm.js, src/edit/precedingTitleFields.js, src/edit/succeedingTitleFields.js
https://issues.folio.org/browse/UIIN-1128
to disable preceding/succeeding fields and + sign button , when Instance is controlled by Source MARC
Add `isDisabled` prop to `UnconnectedTitle` component, which is passing from `InstanceForm` component
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
=> UIIN-1128: Disable fields in Preceding/Succeeding section, when Instance is controlled by Source MARC

src/Instance/InstanceDetails/InstanceClassificationView/InstanceClassificationView.js, src/Instance/InstanceDetails/InstanceClassificationView/index.js, src/Instance/InstanceDetails/InstanceElecAccessView/InstanceElecAccessView.js, src/Instance/InstanceDetails/InstanceElecAccessView/index.js, src/Instance/InstanceDetails/InstanceRelationshipView/InstanceRelationshipView.js, src/Instance/InstanceDetails/InstanceRelationshipView/index.js, src/Instance/InstanceDetails/InstanceRelationshipView/utils.js, src/Instance/InstanceDetails/InstanceSubjectView/InstanceSubjectView.js, src/Instance/InstanceDetails/InstanceSubjectView/index.js, src/Instance/InstanceDetails/index.js, src/Instance/index.js, src/ViewInstance.js, src/referenceFormatters.js
https://issues.folio.org/browse/UIIN-1103
to avoid copy-paste in instances split screen implementation
move views in small separate components
more refactoring
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially …
=> UIIN-1103 Show two instance records as a split screen - ViewInstance refactoring

CHANGELOG.md, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-1104 …
=> UIIN-1104 Add Item screen : Incorrect aria label

CHANGELOG.md, src/components/InstanceFilters/InstanceFilters.js, src/filterConfig.js, test/bigtest/interactors/inventory.js, test/bigtest/network/config.js, test/bigtest/tests/filters/instances/instance-filters-test.js, translations/ui-inventory/en.json
Add the ability to filter Instance records by Source option. Story [UIIN-1132](https://issues.folio.org/browse/UIIN-1132).
=> UIIN-1132: Add filter for instance source

CHANGELOG.md, src/Instance/InstanceDetails/InstanceContributorsView/InstanceContributorsView.js, src/Instance/InstanceDetails/InstanceDetails.js, src/Instance/InstanceDetails/InstanceTitleData/TitleSeriesStatements.js, src/Instance/InstanceDetails/index.js, src/Instance/InstanceDetails/utils.js, src/Instance/InstanceMovement/InstanceMovement.js, src/Instance/InstanceMovement/InstanceMovementContainer.js, src/Instance/InstanceMovement/index.js, src/Instance/InstanceMovement/useInstance.js, src/Instance/index.js, src/ViewInstance.js, src/index.js, src/routes/InstanceMovementRoute.js, src/routes/index.js, test/bigtest/interactors/holdings-create-page.js, test/bigtest/interactors/holdings-edit-page.js, test/bigtest/interactors/instance-movement-page.js, test/bigtest/interactors/instance-view-page.js, test/bigtest/network/config.js, test/bigtest/tests/holdings-create-page-test.js, test/bigtest/tests/holdings-edit-page-test.js, test/bigtest/tests/holdings-view-page-test.js, test/bigtest/tests/instance-movement-page-test.js
https://issues.folio.org/browse/UIIN-1103
1. Instance details component to avoid copy paste on new screen
2. New route that displays 2 instances 
move items/holding to separate routes to support them on split screen …
=> UIIN-1103 Show two instance records as a split screen

translations/ui-inventory/ru.json
=> Update translation strings as of 20200624T182544

CHANGELOG.md, src/components/InstancesList/InstancesList.js, test/bigtest/interactors/inventory.js, test/bigtest/tests/instances-index-test.js
Clear detail record pane after new search is performed.
https://issues.folio.org/browse/UIIN-1074
=> UIIN-1074: Clear detail record pane after new search is performed

CHANGELOG.md, package.json, src/ViewInstance.js, src/ViewMarc.js, test/bigtest/network/config.js
* UIIN-1158 Update Requests to SRS for v4
Refs [UIIN-1158](https://issues.folio.org/browse/UIIN-1158)
=> UIIN-1158 Update Requests to SRS for v4 (#1072)

CHANGELOG.md
https://issues.folio.org/browse/UIIN-1111
was implemented previously
While it's helpful for …
=> UIIN-1111 Continue working in Inventory after moving holding(s) and/or item(s)

CHANGELOG.md, src/utils.js
https://issues.folio.org/browse/UIIN-1188
=> UIIN-1188: Show new request action for checked out items.

CHANGELOG.md, src/utils.js
https://issues.folio.org/browse/UIIN-1187
=> UIIN-1187: Show new request action for on order items

CHANGELOG.md, src/Instance/ItemsList/ItemsList.js, src/Instance/ItemsList/utils.js, test/bigtest/mocks/items.js, test/bigtest/tests/instance-view-page-test.js, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-1124
This adds a column for effective location to the item list that appears in the instance detail view.
=> UIIN-1124: Add effective location to the item list table

src/Instance/InstanceMarc/InstanceMarc.css
https://issues.folio.org/browse/UIIN-1112 …
=> UIIN-1112 fix View Source table styles

CHANGELOG.md, src/Instance/InstanceEdit/InstanceEdit.js, src/Instance/InstanceEdit/index.js, src/Instance/InstanceMovement/InstanceMovementDetails/InstanceMovementDetails.js, src/Instance/InstanceMovement/InstanceMovementDetails/InstanceMovementDetailsActions.js, src/Instance/index.js, src/ViewInstance.js, src/index.js, src/routes/InstanceEditRoute.js, src/routes/index.js, src/utils.js, test/bigtest/interactors/instance-edit-page.js, test/bigtest/interactors/instance-movement-page.js, test/bigtest/tests/instance-edit-page-test.js, test/bigtest/tests/instance-movement-page-test.js
https://issues.folio.org/browse/UIIN-1116
Edit Instance page is moved to separate route to navigate from another inventory places without list/details loading
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially …
=> UIIN-1116 Action menu edit in split screen instance records

CHANGELOG.md, src/ViewInstance.js
Make sure a resource is present before validating it.
Refs [UIIN-1203](https://issues.folio.org/browse/UIIN-1203), [STCON-111](https://issues.folio.org/browse/STCON-111)
=> UIIN-1203 validate presence of resource

CHANGELOG.md, src/components/InstancePlugin/InstancePlugin.js, src/components/UnconnectedTitle/UnconnectedTitle.js
https://issues.folio.org/browse/UIIN-1128
to disable preceding/succeeding fields and + sign button , when Instance is controlled by Source MARC
Add `isDisabled` prop to `UnconnectedTitle` component, which is passing from `InstanceForm` component
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
=> UIIN-1128: Fix disabling + sign

CHANGELOG.md, package.json, src/routes/ItemRoute.js, src/utils.js, src/views/ItemView.js, test/bigtest/interactors/item-edit-page.js, test/bigtest/interactors/item-view-page.js, test/bigtest/interactors/pane-footer.js, test/bigtest/network/config.js, test/bigtest/tests/item-edit-page-test.js, test/bigtest/tests/item-view-page-test.js, test/bigtest/tests/settings/hrid-handling/hrid-handling-test.js
Change request status to `Open - not yet filled` for item with request status `Awaiting delivery` when item is being marked as missing.
https://issues.folio.org/browse/UIIN-1206
This PR also includes a new endpoint for marking an item as missing:
https://s3.amazonaws.com/foliodocs/api/mod-inventory/inventory.html#inventory_items__itemid__mark_missing_post
=> UIIN-1206: Change request status for Awaiting delivery items

translations/ui-inventory/ar.json, translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_SE.json, translations/ui-inventory/en_US.json, translations/ui-inventory/es.json, translations/ui-inventory/es_419.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/he.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/ja.json, translations/ui-inventory/pt_BR.json, translations/ui-inventory/pt_PT.json, translations/ui-inventory/ru.json, translations/ui-inventory/ur.json, translations/ui-inventory/zh_CN.json, translations/ui-inventory/zh_TW.json
=> Update translation strings as of 20200727T130814

translations/ui-inventory/ar.json, translations/ui-inventory/fr_FR.json
=> Update translation strings as of 20200728T124214

translations/ui-inventory/pt_BR.json, translations/ui-inventory/ru.json
=> Update translation strings as of 20200728T221039

translations/ui-inventory/pt_BR.json
=> Update translation strings as of 20200804T150835

translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_US.json, translations/ui-inventory/es.json, translations/ui-inventory/es_419.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/he.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/ja.json, translations/ui-inventory/pt_BR.json, translations/ui-inventory/pt_PT.json, translations/ui-inventory/ru.json, translations/ui-inventory/ur.json, translations/ui-inventory/zh_CN.json, translations/ui-inventory/zh_TW.json
=> Update translation strings as of 20200806T130626

CHANGELOG.md, src/constants.js
Add new item status for use in filters etc.
Refs [UIIN-1006](https://issues.folio.org/browse/UIIN-1006)
=> UIIN-1006 add aged to lost status

translations/ui-inventory/ar.json, translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_SE.json, translations/ui-inventory/en_US.json, translations/ui-inventory/es.json, translations/ui-inventory/es_419.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/he.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/ja.json, translations/ui-inventory/pt_BR.json, translations/ui-inventory/pt_PT.json, translations/ui-inventory/ru.json, translations/ui-inventory/ur.json, translations/ui-inventory/zh_CN.json, translations/ui-inventory/zh_TW.json
=> Update translation strings as of 20200807T145751

src/Instance/InstanceMovement/InstanceMovementDetails/InstanceMovementDetails.js
https://issues.folio.org/browse/UIIN-1120 …
=> UIIN-1120 fix edit permission on movement screen

CHANGELOG.md, src/Instance/InstanceMovement/InstanceMovement.js, src/Instance/MoveHoldingContext/MoveHoldingContext.js, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-1226 …
=> UIIN-1226 Confirm items before moving to different holdings and/or instances

src/Instance/HoldingsList/Holding/Holding.js, src/Instance/HoldingsList/Holding/MoveToDropdown/MoveToDropdown.js
https://issues.folio.org/browse/UIIN-1127 …
=> UIIN-1127 Fix MoveToDropdown to show correct labels

translations/ui-inventory/ar.json, translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_SE.json, translations/ui-inventory/en_US.json, translations/ui-inventory/es.json, translations/ui-inventory/es_419.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/he.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/ja.json, translations/ui-inventory/pt_BR.json, translations/ui-inventory/pt_PT.json, translations/ui-inventory/ru.json, translations/ui-inventory/ur.json, translations/ui-inventory/zh_CN.json, translations/ui-inventory/zh_TW.json
=> Update translation strings as of 20200901T173106

translations/ui-inventory/ar.json, translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_SE.json, translations/ui-inventory/en_US.json, translations/ui-inventory/es.json, translations/ui-inventory/es_419.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/he.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/ja.json, translations/ui-inventory/pt_BR.json, translations/ui-inventory/pt_PT.json, translations/ui-inventory/ru.json, translations/ui-inventory/ur.json, translations/ui-inventory/zh_CN.json, translations/ui-inventory/zh_TW.json
=> Update translation strings as of 20200910T134908

src/settings/FastAdd/FastAddSettings.js
https://issues.folio.org/browse/UIIN-1211
Add the ability to re-select the "Select instance status" option in the dropdown menu according to the latest changes in the description.
=> UIIN-1211: Make "Select instance status" option available

CHANGELOG.md, package.json
Refs [UIIN-1252](https://issues.folio.org/browse/UIIN-1252)
=> UIIN-1252 increment react-intl to v5

CHANGELOG.md, src/views/ItemView.js
https://issues.folio.org/browse/UIIN-1250
https://issues.folio.org/browse/UIIN-1002
While …
=> UIIN-1002 UIIN-1250 Implement easy way to copy HRID, Barcode in the Item record

CHANGELOG.md, src/ViewHoldingsRecord.js
https://issues.folio.org/browse/UIIN-1001 …
=> UIIN-1001 Implement easy way to copy HRID in the Holdings record

CHANGELOG.md, src/Instance/InstanceDetails/InstanceAdministrativeView/InstanceAdministrativeView.js
https://issues.folio.org/browse/UIIN-1000 …
=> UIIN-1000 Implement easy way to copy HRID in the Holdings record

translations/ui-inventory/fr_FR.json
=> Update translation strings as of 20200922T125348

CHANGELOG.md, package.json, src/settings/HoldingsSourcesSettings.js, src/settings/index.js, test/bigtest/interactors/settings/holdings-sources/holdings-sources.js, test/bigtest/network/config.js, test/bigtest/network/factories/holdings-source.js, test/bigtest/network/models/holdings-source.js, test/bigtest/network/serializers/holdings-source.js, test/bigtest/tests/settings/holdings-sources/holdings-sources-test.js, translations/ui-inventory/en.json
Add Holdings sources to settings.
https://issues.folio.org/browse/UIIN-1229
=> UIIN-1229: Add Holdings sources to settings

CHANGELOG.md, src/Holding/CreateHolding/CreateHolding.js, src/ViewHoldingsRecord.js, src/edit/holdings/HoldingsForm.js, src/routes/withData.js, src/settings/HoldingsSourcesSettings.js, test/bigtest/interactors/holdings-edit-page.js, test/bigtest/tests/holdings-edit-page-test.js, translations/ui-inventory/en.json
Add Holdings source to holdings view and edit screens:
https://issues.folio.org/browse/UIIN-1123
=> UIIN-1123: Add Holdings source to holdings view and edit screens

CHANGELOG.md, src/Instance/HoldingsList/HoldingsListContainer.js, src/ViewHoldingsRecord.js, src/contexts/index.js, src/index.js, src/providers/DataProvider.js, src/providers/index.js, src/routes/CreateHoldingRoute.js, src/routes/CreateItemRoute.js, src/routes/InstanceEditRoute.js, src/routes/InstanceMovementRoute.js, src/routes/InstancesRoute.js, src/routes/ItemRoute.js
Move dictionary data fetching above the Router to avoid refetching the same data when switching between different routes.
https://issues.folio.org/browse/UIIN-1265
=> UIIN-1265: Move dictionary data fetching above router

translations/ui-inventory/fr_FR.json
=> Update translation strings as of 20200930T202600

src/ViewInstance.js
https://issues.folio.org/browse/UIIN-977 …
=> UIIN-977 Show questionmark only when length is undefined

CHANGELOG.md, package.json, test/bigtest/tests/item-view-page-test.js
Fix permission for mark as missing action.
https://issues.folio.org/browse/UIIN-1272
=> UIIN-1272: Fix permission for mark as missing action

CHANGELOG.md, src/Instance/InstanceMovement/InstanceMovementDetails/InstanceMovementDetailsActions.js, src/common/hooks/useGoBack.js
https://issues.folio.org/browse/UIIN-1289 …
=> UIIN-1289 Closing the 'View MARC' record takes you to a different app instead of the Instance details, sometimes.

CHANGELOG.md, src/Instance/ItemsList/ItemsList.js, src/Instance/ItemsList/utils.js, test/bigtest/tests/instance-view-page-test.js
https://issues.folio.org/browse/UIIN-1251 …
=> UIIN-1251 Instance record (detailed view). Add copy number to item list

CHANGELOG.md, src/Instance/HoldingsList/Holding/Holding.js, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-1254 …
=> UIIN-1254 Instance record (detailed view). Add holdings copy number to holdings accordion

translations/ui-inventory/ar.json, translations/ui-inventory/ca.json, translations/ui-inventory/da.json, translations/ui-inventory/de.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_SE.json, translations/ui-inventory/en_US.json, translations/ui-inventory/es.json, translations/ui-inventory/es_419.json, translations/ui-inventory/es_ES.json, translations/ui-inventory/fr.json, translations/ui-inventory/fr_FR.json, translations/ui-inventory/he.json, translations/ui-inventory/hi_IN.json, translations/ui-inventory/hu.json, translations/ui-inventory/it_IT.json, translations/ui-inventory/ja.json, translations/ui-inventory/ko.json, translations/ui-inventory/pl.json, translations/ui-inventory/pt_BR.json, translations/ui-inventory/pt_PT.json, translations/ui-inventory/ru.json, translations/ui-inventory/ur.json, translations/ui-inventory/zh_CN.json, translations/ui-inventory/zh_TW.json
=> Update translation strings as of 20201007T234658

CHANGELOG.md, src/components/ItemFilters/ItemFilters.js, test/bigtest/interactors/routes/items-route.js, test/bigtest/tests/filters/items/item-status-filter-test.js
https://issues.folio.org/browse/UIIN-1224
Switching between `<CheckboxFilter>` and `<MultiSelectFilter>` is super easy -- barely an inconvenience. Everything just works!
=> UIIN-1224: Use <MultiSelectFilter> for item status filtering

translations/ui-inventory/fr_FR.json
=> Update translation strings as of 20201013T203429

src/components/ModalContent/ModalContent.js, test/bigtest/tests/item-view-page-test.js, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-1294
This is an addition to #1207. The content of the open requests link was fixed according to the comment in Jira.
=> UIIN-1294: Fix the content of open requests link

CHANGELOG.md, src/components/UnconnectedTitle/UnconnectedTitle.js, src/edit/InstanceForm.js, src/edit/alternativeTitles.js, src/edit/childInstanceFields.js, src/edit/contributorFields.js, src/edit/electronicAccessFields.js, src/edit/noteFields.js, src/edit/parentInstanceFields.js, src/edit/publicationFields.js, src/edit/publicationFrequencyFields.js, src/edit/publicationRangeFields.js, src/edit/seriesFields.js
Use `TextArea` for some input fields on instance form.
https://issues.folio.org/browse/UIIN-1278
=> UIIN-1278: Use TextArea for some input fields on instance form.

CHANGELOG.md, src/Instance/InstanceDetails/InstanceDetails.js, src/ViewInstance.js, src/components/HelperApp/HelperApp.js, src/components/HelperApp/index.js, translations/ui-inventory/en.json
Assign tags to Instance
https://issues.folio.org/browse/UIIN-307
While it's helpful for …
=> UIIN-307 assign tags to instance

CHANGELOG.md, src/components/HelperApp/HelperApp.js, src/components/InstanceFilters/InstanceFilters.js, src/components/InstanceFilters/instanceFilterRenderer.js, src/filterConfig.js, src/providers/DataProvider.js, test/bigtest/network/config.js, test/bigtest/network/factories/instance.js, translations/ui-inventory/en.json
Filter by tags on Instances list
https://issues.folio.org/browse/UIIN-763
While it's helpful …
=> UIIN-763 Filter Instance by Tags

CHANGELOG.md, package.json, src/ViewHoldingsRecord.js, src/edit/contributorFields.js, src/edit/noteFields.js
https://issues.folio.org/browse/UIIN-308 …
=> UIIN-308 Assign tags to Inventory Holdings

CHANGELOG.md, src/components/HoldingsRecordFilters/HoldingsRecordFilters.js, src/components/HoldingsRecordFilters/holdingsRecordFilterRenderer.js, src/components/InstanceFilters/InstanceFilters.js, src/components/TagsFilter/TagsFilter.js, src/components/TagsFilter/index.js, src/filterConfig.js
Filter by Tags on Holdings tab of Instances list
https://issues.folio.org/browse/UIIN-764 …
=> UIIN-764 filter instances by holding records tags

CHANGELOG.md, src/components/ItemFilters/ItemFilters.js, src/components/ItemFilters/itemFilterRenderer.js, src/components/ItemFilters/itemFilterRenderer.test.js, src/filterConfig.js
Filter Item by Tags
https://issues.folio.org/browse/UIIN-765
While it's helpful for …
=> UIIN-765 Filter Item by Tags

CHANGELOG.md, package.json, src/ViewHoldingsRecord.js, src/routes/ItemRoute.js, src/views/ItemView.js
https://issues.folio.org/browse/UIIN-309 …
=> UIIN-309 Assign tags to Inventory Items

src/components/HoldingsRecordFilters/HoldingsRecordFilters.js, src/components/InstanceFilters/InstanceFilters.js, src/components/ItemFilters/ItemFilters.js, src/components/TagsFilter/TagsFilter.js, src/providers/DataProvider.js
https://issues.folio.org/browse/UIIN-763 …
=> UIIN-763 add sorting to tags on client side

CHANGELOG.md, package.json, src/components/InstancesList/InstancesList.js, test/bigtest/tests/filters/instances/instances-list-test.js
Implement records selection on the inventory search screen in the scope of the [UIIN-1350](https://issues.folio.org/browse/UIIN-1350).
=> UIIN-1350: Implement records selection on the inventory search screen 

jest.config.js, package.json, src/components/ItemFilters/itemFilterRenderer.test.js, src/components/TagsFilter/TagsFilter.js, src/components/TagsFilter/TagsFilter.test.js
open accordion if tags filter is not empty.
https://issues.folio.org/browse/UIIN-765
`closedByDefault` works only at mounting time. `selectedValues` is always undefined at mounting time, so we can't simply check `selectedValues` and I check directly filters from url
Ideally all of the PRs involved in breaking changes would be merged in the same day to …
=> UIIN-765 fix opened state of filter accordion

CHANGELOG.md, src/edit/items/ItemForm.js
https://issues.folio.org/browse/UIIN-1280
Just like UIIN-1279, etc., but for the item record.
=> UIIN-1280: Replace TextFields with TextAreas for scrollability (UIIN-1280)

CHANGELOG.md, package.json, src/components/InstancesList/InstancesList.js, test/bigtest/interactors/routes/instances-route.js, test/bigtest/tests/filters/instances/instances-list-test.js, translations/ui-inventory/en.json
Add selected instances count in the subheader in the scope of the [UIIN-1364](https://issues.folio.org/browse/UIIN-1364).
=> UIIN-1364: Add selected instances count in the sub header

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/components/InstancesList/instances.css
[UIIN-1356](https://issues.folio.org/browse/UIIN-1356) …
=> UIIN-1356 Result list. Align text in the columns in the top

package.json
Set inventory-record-bulk interface to the correct version (UIIN-1368)
=> UIIN-1368: Set inventory-record-bulk interface to the correct version

CHANGELOG.md, src/settings/ClassificationTypesSettings.js, src/settings/ContributorTypesSettings.js, src/settings/FormatsSettings.js, src/settings/IdentifierTypesSettings.js, src/settings/InstanceStatusTypesSettings.js, src/settings/ModesOfIssuanceSettings.js, src/settings/NatureOfContentTermsSettings.js, src/settings/ResourceTypesSettings.js
https://issues.folio.org/browse/UIIN-1373
As part of #1243, the `sourceSuppressor` util function was created. This PR eliminates duplication of a piece of code in `Settings` by using this function.
=> UIIN-1373: Refactor the suppress actions into a single util function

CHANGELOG.md, jest.config.js, package.json, src/components/ItemFilters/itemFilterRenderer.test.js, src/components/SelectedRecordsModal/SelectedRecordsModal.test.js, src/components/TagsFilter/TagsFilter.test.js, test/jest/__mock__/currencyData.mock.js, test/jest/__mock__/documentCreateRange.mock.js, test/jest/__mock__/index.js, test/jest/__mock__/matchMedia.mock.js, test/jest/__mock__/stripesConfig.mock.js, test/jest/__mock__/stripesCore.mock.js, test/jest/__mock__/stripesIcon.mock.js, test/jest/__mock__/stripesSmartComponents.mock.js, test/jest/babel.config.js, test/jest/helpers/Harness.js, test/jest/helpers/mockOffsetSize.js, test/jest/helpers/prefixKeys.js, test/jest/helpers/renderWithIntl.js, test/jest/helpers/translationsProperties.js, test/jest/jest-transformer.js, test/jest/jest.setup.js
In scope of [UIIN-1375](https://issues.folio.org/browse/UIIN-1375).
Added jest setup, covered `SelectedRecordsModal` and fixed existing tests.
=> UIIN:1375: Add jest setup, cover SelectedRecordsModal and adjust existing tests

CHANGELOG.md, src/components/HoldingsRecordFilters/HoldingsRecordFilters.js, src/components/InstanceFilters/InstanceFilters.js, src/components/ItemFilters/ItemFilters.js, src/utils.js
Fix type ahed for location filters:
https://issues.folio.org/browse/UIIN-1393
https://issues.folio.org/browse/UIIN-1395
=> UIIN-1393,UIIN-1395: Fix type ahead for location filters

src/RemoteStorage/Provider.js, translations/ui-inventory/en.json
UIIN 1321 small fixes
While it's helpful for reviewers to help identify potential problems, …
=> UIIN 1321 small fixes

test/bigtest/interactors/inventory.js, test/bigtest/tests/instances-index-test.js
There is one single test which fails randomly. This PR is trying to address it.
=> Adjust inventory test

CHANGELOG.md, src/utils.js, test/bigtest/tests/item-view-page-test.js
https://issues.folio.org/browse/UIIN-1306
Added ability to create a new request on the item with status `Restricted` in the `Actions` menu on the Item View page.
=> UIIN-1306: Show new request option for restricted item

CHANGELOG.md, src/settings/HRIDHandling/HRIDHandlingForm.js, src/settings/HRIDHandling/HRIDHandlingSettings.js, test/bigtest/mocks/hridSettings.js, test/bigtest/tests/settings/hrid-handling/hrid-handling-test.js
Connect the "Remove leading zeroes from HRID" field to the form to send this field to the server.
* Wrap `Checkbox` in the `Field` component …
=> UIIN-1413: Connect the "Remove leading zeroes from HRID" field to the form

CHANGELOG.md, src/ViewInstance.js, src/components/ImportRecordModal/ImportRecordModal.js, translations/ui-inventory/en.json
Fixes UIIN-1424.
Also, in passing, belatedly add change-logging for UIIN-1426.
=> Modify language of Import Record modal when updating a record.

package.json, src/Instance/HoldingsList/Holding/Holding.js, src/Instance/HoldingsList/Holding/HoldingContainer.js, src/Instance/HoldingsList/Holding/MoveToDropdown/MoveToDropdown.js, src/Instance/HoldingsList/HoldingsList.js, src/Instance/HoldingsList/HoldingsListContainer.js, src/Instance/InstanceDetails/InstanceDetails.js, src/Instance/InstanceDetails/InstanceTitleData/InstanceTitleData.js, src/Instance/InstanceMovement/HoldingMovementList/HoldingsListMovement.js, src/Instance/InstanceMovement/InstanceMovement.js, src/Instance/InstanceMovement/InstanceMovementContainer.js, src/Instance/InstanceMovement/InstanceMovementDetails/InstanceMovementDetails.js, src/Instance/InstanceMovement/InstanceMovementDetails/InstanceMovementDetailsContainer.js, src/Instance/ItemsList/DropZone.js, src/Instance/ItemsList/ItemsList.js, src/Instance/MoveHoldingContext/MoveHoldingContext.js, src/ViewInstance.js, src/components/RepeatableField/FieldRow.js, src/components/TitlesView/TitlesView.js, src/edit/InstanceForm.js, src/edit/common/LocationSelectionWithCheck.js, src/edit/items/ItemForm.js, src/routes/InstanceMovementRoute.js, src/settings/HRIDHandling/HRIDHandlingForm.js, src/settings/HRIDHandling/HRIDHandlingSettings.js, src/settings/StatisticalCodeSettings.js, src/views/ItemView.js
preliminary refactoring for https://issues.folio.org/browse/UIIN-1406
- fix console errors
- code clean-up
- use local stripes-cli
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …
=> UIIN-1406 preliminary refactoring

CHANGELOG.md, src/views/ItemView.js
https://issues.folio.org/browse/UIIN-816
=> UIIN-816: Display shelving order on the item record

CHANGELOG.md, src/settings/TargetProfileDetail.js, src/settings/TargetProfileForm.js, translations/ui-inventory/en.json
=> In "Z39.50 target profiles" settings, support the `targetOptions` field

CHANGELOG.md, src/Instance/HoldingsList/Holding/HoldingAccordion.js, src/Instance/ItemsList/ItemsList.js, src/components/InstancesList/InstancesList.js, src/components/InstancesList/instances.css, test/bigtest/interactors/instance-view-page.js, test/bigtest/interactors/inventory.js, test/bigtest/network/config.js, test/bigtest/network/factories/instance.js, test/bigtest/tests/filters/instances/instance-filters-test.js, test/bigtest/tests/instance-view-page-test.js
This PR reverts commits 61602ed9f2b6df46ce78801b84353e89ee204e56 and 40af8aec50006d18dd4a3e6e894d1c8a0907cf23.
=> Revert UIIN-1380 and UIIN-1381 "Add warn icon for Suppressed from discovery and Staff suppressed"

src/Instance/Move/ConfirmationModal.js, src/Instance/Move/index.js, src/Instance/Move/useItems.js, src/Instance/MoveHoldingContext/MoveHoldingContext.js, src/Instance/MoveItemsContext/Confirmation.js, src/Instance/MoveItemsContext/MoveItemsContext.js
https://issues.folio.org/browse/UIIN-1406 …
=> UIIN-1406 fix Move ConfirmationModal confirmLabel translation, refactor

CHANGELOG.md, src/Instance/InstanceDetails/InstanceAdministrativeView/InstanceAdministrativeView.js, src/Instance/InstanceDetails/InstanceDetails.js, src/ViewHoldingsRecord.js, src/views/ItemView.js, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-1379
This PR also refactors work done in https://issues.folio.org/browse/UIIN-1377 and https://issues.folio.org/browse/UIIN-1378 based on feedback from PO.
=> UIIN-1379: Add visual display when item is suppressed from discovery

src/Instance/InstanceDetails/InstanceAdministrativeView/InstanceAdministrativeView.js, src/Instance/InstanceDetails/InstanceDetails.js, src/View.css, src/ViewHoldingsRecord.js, src/views/ItemView.js, translations/ui-inventory/en.json
This PR includes couple more changes to:
https://issues.folio.org/browse/UIIN-1377
https://issues.folio.org/browse/UIIN-1378
https://issues.folio.org/browse/UIIN-1379
based on a feedback from PO.
=> UIIN-1377: Update visual displays

src/Instance/InstanceDetails/SubInstanceList/SubInstanceList.js, src/hooks/useCallout.js, translations/ui-inventory/en.json
This PR is a continuation of UIIN-1044 and UIIN-1045 based on some feedback from PO. It adds ability to copy HRID.
https://issues.folio.org/browse/UIIN-1044
https://issues.folio.org/browse/UIIN-1045
=> UIIN-1044: Add ability to copy hrid

CHANGELOG.md, src/Holding/CreateHolding/CreateHolding.js, src/Item/CreateItem/CreateItem.js, src/ViewHoldingsRecord.js, src/views/ItemView.js
Add callout after item or holdings record are saved.
This PR takes care of UIIN-1485 and UIIN-1486:
https://issues.folio.org/browse/UIIN-1485
https://issues.folio.org/browse/UIIN-1486
=> UIIN-1485: Add callout after item or holdings record are saved

package.json
https://issues.folio.org/browse/UIIN-1512 …
=> UIIN-1512 Update "remote-storage-mappings" interface

CHANGELOG.md, src/Instance/Move/ConfirmationModal.js, src/Instance/Move/useItems.js, src/Instance/MoveHoldingContext/MoveHoldingContext.js, src/Instance/MoveItemsContext/Confirmation.js, src/components/ImportRecordModal/ImportRecordModal.js, src/edit/common/LocationSelectionWithCheck.js, src/edit/holdings/HoldingsForm.js, src/edit/items/ItemForm.js, src/settings/HRIDHandling/HRIDHandlingSettings.js, src/settings/TargetProfileForm.js
Prefer @folio/stripes exports to private paths when importing components.
https://issues.folio.org/browse/UIIN-1516
=> UIIN-1516: Fix stripes import paths

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIIN-1528
=> UI in 1528

CHANGELOG.md, src/Instance/InstanceEdit/InstanceEdit.js, src/Instance/InstanceEdit/InstanceEdit.test.js, test/fixtures/index.js, test/fixtures/instance.js, test/jest/__mock__/stripesConfig.mock.js, test/jest/__mock__/stripesCore.mock.js, test/jest/__mock__/stripesSmartComponents.mock.js, test/jest/helpers/translationsProperties.js, text.txt, translations/ui-inventory/en.json
Show error modal when saving instance fails.
https://issues.folio.org/browse/UIIN-1527
=> UIIN-1527: Show error modal when saving instance fails

CHANGELOG.md, src/Instance/InstanceDetails/InstanceDetails.js, src/Instance/InstanceDetails/SubInstanceGroup/SubInstanceGroup.js
https://issues.folio.org/browse/UIIN-1534
=> UIIN-1534: Unfold instance relationship accordion when relationships are present.

CHANGELOG.md, src/settings/StatisticalCodeSettings.js
Types were retrieved without being sorted. That was not helpful.
Refs [UIIN-1547](https://issues.folio.org/browse/UIIN-1547)
=> UIIN-1547 sort statistical code types

CHANGELOG.md, package.json, src/Holding/ViewHolding/HoldingAquisitions/HoldingAquisitions.js, src/Holding/ViewHolding/HoldingAquisitions/HoldingAquisitions.test.js, src/Holding/ViewHolding/HoldingAquisitions/fixtures.js, src/Holding/ViewHolding/HoldingAquisitions/index.js, src/Holding/ViewHolding/HoldingAquisitions/useHoldingOrderLines.js, src/Holding/ViewHolding/HoldingAquisitions/useHoldingOrderLines.test.js, src/ViewHoldingsRecord.js, src/edit/holdings/HoldingsForm.js, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-574 …
=> UIIN-574 Holdings record. Show connected holding POLs in acq accordion

CHANGELOG.md, src/edit/holdings/HoldingsForm.js
Populate a value in Source field when View/Edit Inventory Holdings Record
[UIIN-1548](https://issues.folio.org/browse/UIIN-1548)
=> UIIN-1548: View/Edit Inventory Holdings Record | Populate a value in Source field

CHANGELOG.md, src/components/InstancesList/InstancesList.js
Fix instance duplication when child or parent records are present
https://issues.folio.org/browse/UIIN-1562
=> UIIN-1562: Fix instance duplication when child or parent records are present

CHANGELOG.md, src/ViewHoldingsRecord.js
Fix Holdings record showing incorrect source value
[UIIN-1570](https://issues.folio.org/browse/UIIN-1570)
=> UIIN-1570: Inventory Holdings record is populated with Source = MARC although there is no underlying SRS record

CHANGELOG.md, package.json
UIIN-1568 Align dependency versions affected by Inventory's Optimistic locking
=> UIIN-1568 Align dependency versions affected by Inventory's Optimistic locking

src/ViewHoldingsRecord.js, src/views/ItemView.js
https://issues.folio.org/browse/UIIN-1411?focusedCommentId=110488&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-110488
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …
=> UIINV-1411 Edit Holding and Item shortcuts

CHANGELOG.md, src/Instance/HoldingsList/Holding/HoldingAccordion.js, src/Instance/HoldingsList/Holding/HoldingAccordion.test.js, src/Instance/HoldingsList/Holding/HoldingButtonsGroup.js, src/hooks/useHoldingItemsQuery.js, src/hooks/useHoldingItemsQuery.test.js, test/jest/__mock__/stripesCore.mock.js
https://issues.folio.org/browse/UIIN-1617 …
=> UIIN-1617 Item count bug when there are multiple holdings on an instance

CHANGELOG.md, src/Holding/ViewHolding/HoldingReceivingHistory/HoldingReceivingHistory.js, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-1632 …
=> UIIN-1632 Update Received piece table columns

CHANGELOG.md, src/ViewHoldingsRecord.js
Delete Inventory and MARC holdings records when record Source = MARC.
Issue: [UIIN-1559](https://issues.folio.org/browse/UIIN-1559)
=> UIIN-1559: Delete an Inventory Holdings record Source = MARC

CHANGELOG.md, src/Instance/InstanceMovement/InstanceMovementContainer.js
Add request for updating `004` field for MARC holdings
Issue: [UIIN-1633](https://issues.folio.org/browse/UIIN-1633)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
=> UIIN-1633: Add ability to move MARC holdings between instances

CHANGELOG.md, src/Holding/ViewHolding/HoldingReceivingHistory/HoldingReceivingHistory.js, src/Holding/ViewHolding/HoldingReceivingHistory/HoldingReceivingHistory.test.js, src/constants.js
https://issues.folio.org/browse/UIIN-1824 …
=> UIIN-1824 Allow user to sort receiving history table

CHANGELOG.md, package.json, src/views/ItemView.js
Add permission for marking item as `In process`
https://issues.folio.org/browse/UIIN-1654
=> UIIN-1654: Add permission for marking item as In process.

src/components/InstancesList/InstancesList.test.js, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-1845 …
=> UIIN-1845: Rename Save Holdings UUIDs to Save holdings UUIDs

CHANGELOG.md, src/edit/holdings/HoldingsForm.js
Disable delete button in mapped repeatable fields
While it's helpful for reviewers to help …
=> UIIN-1853: Holdings record with source MARC - do not allow user to delete mapped field values

CHANGELOG.md, package.json, src/Instance/InstanceDetails/InstanceAcquisition/InstanceAcquisition.js, src/Instance/InstanceDetails/InstanceAcquisition/InstanceAcquisition.test.js, src/Instance/InstanceDetails/InstanceAcquisition/fixtures.js, src/Instance/InstanceDetails/InstanceAcquisition/index.js, src/Instance/InstanceDetails/InstanceAcquisition/useInstanceAcquisition.js, src/Instance/InstanceDetails/InstanceAcquisition/useInstanceAcquisition.test.js, src/Instance/InstanceDetails/InstanceDetails.js, src/utils.js, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-1835 …
=> UIIN-1835 display Order information on Instance record

src/Item/ViewItem/ItemAcquisition/ItemAcquisition.js
https://issues.folio.org/browse/UIIN-1858 …
=> UIIN-1858 Item acquisitions - update values

src/Instance/InstanceDetails/InstanceAcquisition/InstanceAcquisition.js, src/Instance/InstanceDetails/InstanceAcquisition/useInstanceAcquisition.js
https://issues.folio.org/browse/UIIN-1835?focusedCommentId=118945&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-118945
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …
=> UIIN-1835 order PO lines by date ordered

src/views/ItemView.js
https://issues.folio.org/browse/UIIN-1858 …
=> UIIN-1858 Hide acq accordion when item is not connected to order line

CHANGELOG.md, src/Holding/DuplicateHolding/DuplicateHolding.js, src/Holding/DuplicateHolding/DuplicateHolding.test.js, src/Holding/DuplicateHolding/index.js, src/Holding/EditHolding/EditHolding.js, src/Holding/EditHolding/EditHolding.test.js, src/Holding/EditHolding/index.js, src/Holding/index.js, src/ViewHoldingsRecord.js, src/ViewHoldingsRecord.test.js, src/ViewInstance.js, src/hooks/index.js, src/hooks/useHoldingMutation/index.js, src/hooks/useHoldingMutation/useHoldingMutation.js, src/hooks/useHoldingMutation/useHoldingMutation.test.js, src/index.js, src/routes/DuplicateHoldingRoute.js, src/routes/DuplicateHoldingRoute.test.js, src/routes/EditHoldingRoute.js, src/routes/EditHoldingRoute.test.js, src/routes/ViewHoldingRoute.js, src/routes/ViewHoldingRoute.test.js, src/routes/index.js, test/bigtest/tests/holdings-edit-page-test.js
The root reason for this pull request is https://issues.folio.org/browse/UIIN-1866.
Combining layers and shortcuts causes unexpected bugs like the one above. If there is no shortcut handler (e.g. for duplication) for any layer, it is pulled from the parent component. This is logical, but not always expected - the user, being in the holding's view, will be confused by using `Cmd + C` shortcut and seeing as a result the form for creating an instance instead of holding. Or an user applies `Option + N` shortcut in the holding's edit form  - as a result, he will be redirected to the form for creating a new instance - it's confusing. 
This problem could be solved by adding handlers for the necessary shortcuts or stubs for unnecessary ones, but this approach is unstable and may require …
=> UIIN-1866 Holdings. Keyboard shortcuts does not act on the holdings

src/views/ItemView.js
https://issues.folio.org/browse/UIIN-1858 …
=> UIIN-1858 Item Acq accordion should be opened by default

CHANGELOG.md, src/Holding/ViewHolding/HoldingAquisitions/HoldingAquisitions.js, src/Holding/ViewHolding/HoldingAquisitions/useHoldingOrderLines.js, src/Holding/ViewHolding/HoldingReceivingHistory/HoldingReceivingHistory.js, src/ViewHoldingsRecord.js, src/common/hooks/index.js, src/common/hooks/useControlledAccordion/index.js, src/common/hooks/useControlledAccordion/useControlledAccordion.js, src/common/hooks/useControlledAccordion/useControlledAccordion.test.js
https://issues.folio.org/browse/UIIN-1869 …
=> UIIN-1869 Fix The Acquisition accordion is not unfolded automatically when there is data to be shown

CHANGELOG.md, package.json
Support okapi interfaces `circulation` `12.0`
* Title level requests changes affect ui-requests (UIREQ) without breaking change for this module.
* The implementation of title level requests requires data migration to allow for a single queue of requests, whether item or title level (https://issues.folio.org/browse/UXPROD-3330).
https://issues.folio.org/browse/UIIN-1861
=> UIIN-1861: Also support `circulation` `12.0`

CHANGELOG.md, src/Instance/InstanceDetails/InstanceAdministrativeView/AdministrativeNoteList.js, src/Instance/InstanceDetails/InstanceAdministrativeView/InstanceAdministrativeView.js, src/edit/InstanceForm.js, src/edit/administrativeNodeFields.test.js, src/edit/administrativeNoteFields.js, test/jest/helpers/renderWithRouter.js, translations/ui-inventory/en.json
UIIN-1442 - Add new data element administrative note
https://issues.folio.org/browse/UIIN-1442
Edit Form:
Instance View:
=> UIIN-1442 - Add new administrative note data element 

CHANGELOG.md, src/filterConfig.js, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-1879 …
=> UIIN-1879 Add Browse call numbers option

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/components/InstancesList/InstancesList.test.js, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-1887 …
=> UIIN-1887: Browse form

src/components/InstancesList/InstancesList.js, src/filterConfig.js, translations/ui-inventory/en.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_US.json
https://issues.folio.org/browse/UIIN-1883 …
=> UIIN-1883 Call number browse result list - add columns

src/components/InstancesList/InstancesList.js
https://issues.folio.org/browse/UIIN-1887 …
=> UIIN-1887:Browse form

src/components/InstancesList/InstancesList.js, src/filterConfig.js
https://issues.folio.org/browse/UIIN-1894 …
=> UIIN-1894 Browse subjects form

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/filterConfig.js, src/routes/InstancesRoute.js
Approach
- Nested Browse filter options and browse columnsets within objects.
- used `browseModeOptions` as a single source for both rendering the SearchField dropdown values and checking the query parameters for applicable values.
Refs [UIIN-1892](https://issues.folio.org/browse/UIIN-1892)
Ideally all of the PRs involved in breaking changes would be …
=> UIIN-1892 - Browse by subject - columns. nest browse filter options and column sets

src/routes/buildManifestObject.js
https://issues.folio.org/browse/UIIN-1884
Fix field after updating the object in filterConfig.js
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
=> UIIN-1884: Call number browse result list - populate results

CHANGELOG.md, package.json, src/ViewInstance.js, src/components/ViewInstance/MenuSection/NewInstanceRequestButton.js, src/components/ViewInstance/MenuSection/NewInstanceRequestButton.test.js, src/components/ViewInstance/MenuSection/RequestsReorderButton.js, src/components/ViewInstance/MenuSection/RequestsReorderButton.test.js, src/constants.js, src/routes/ItemRoute.js, src/views/ItemView.js, test/jest/__mock__/stripesCore.mock.js, translations/ui-inventory/en.json
* Create title level request from Instance record. Refs UIIN-1620.
* Inventory action menu link View & reorder queue. Refs UIIN-1881.
* This is feature branch for merge all associated commits that was reviewed separately
https://issues.folio.org/browse/UXPROD-1796 - Title Level Requests Complete (part 1)
https://issues.folio.org/browse/UIIN-1901
=> Title level requests

CHANGELOG.md, src/components/InstancesList/InstancesList.js
https://issues.folio.org/browse/UIIN-1904 …
=> UIIN-1904: Filters/facets on Subject browse form

CHANGELOG.md, src/edit/holdings/HoldingsForm.js
https://issues.folio.org/browse/UIIN-1159 …
=> UIIN-1159 New/Edit Holdings Page - Accessibility Error: IDs of active elements must be unique

CHANGELOG.md, src/edit/holdings/HoldingsForm.js, src/edit/holdings/note.js
https://issues.folio.org/browse/UIIN-1648 …
=> UIIN-1648 Create/Edit Holdings record > No indication that field(s) is required

CHANGELOG.md, src/edit/instanceFormatFields.js, src/edit/languageFields.js, src/edit/natureOfContentFields.js
Certain ARIA roles must be contained by particular parents
https://issues.folio.org/browse/UIIN-1154
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
=> UIIN-1154: New/Edit Instance Page - Accessibility Error: Certain ARIA roles must be contained by particular parents

src/components/InstancesList/InstancesList.js, src/components/InstancesList/InstancesList.test.js
https://issues.folio.org/browse/UIIN-1882 …
=> UIIN-1882 Add missed prop

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/components/InstancesList/InstancesList.test.js
https://issues.folio.org/browse/UIIN-1913 …
=> UIIN-1913: Browse form - Reset all button

CHANGELOG.md, src/components/CheckboxFacet/CheckboxFacetList.css, src/components/CheckboxFacet/CheckboxFacetList.js, src/components/InstancesList/InstancesList.js, test/bigtest/interactors/inventory.js
The problem is - Axe check says:
Form elements must have labels
https://www.w3.org/WAI/tutorials/forms/labels/#note-on-hiding-elements …
=> UIIN-1144 Accessibility Error: Form elements must have labels. Inventory landing page.

CHANGELOG.md, src/components/InstancesList/InstancesList.js
https://issues.folio.org/browse/UIIN-1922 …
=> UIIN-1922: Matching call number should be in bold

CHANGELOG.md, src/Instance/InstanceDetails/InstanceAdministrativeView/StatisticalCodesList.js, src/Instance/InstanceDetails/InstanceClassificationView/InstanceClassificationView.js, src/Instance/InstanceDetails/InstanceContributorsView/InstanceContributorsView.js, src/Instance/InstanceDetails/InstanceIdentifiersView/InstanceIdentifiersView.js, src/Instance/InstanceDetails/InstanceTitleData/AlternativeTitlesList.js, src/Instance/ItemsList/ItemsList.js, src/components/TitlesView/TitlesView.js
- Accessibility Error: IDs of the elements must be unique.
- Refs: https://issues.folio.org/browse/UIIN-1145
- Pass `columnIdPrefix` prop to `MultiColumnList` to create unique `ids`.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to …
=> UIIN-1145: Accessibility Error: IDs of the elements must be unique

CHANGELOG.md, package.json
While it's helpful for reviewers to help identify potential problems, ensuring that it's …
=> UIIN-1940 Add browse permissions

CHANGELOG.md, src/Instance/InstanceDetails/InstanceAdministrativeView/InstanceAdministrativeView.js, src/Instance/InstanceDetails/InstanceAdministrativeView/InstanceAdministrativeView.test.js, src/Instance/ItemsList/ItemBarcode.js, src/Instance/ItemsList/tests/ItemBarcode.test.js, src/components/ItemFilters/ItemFilters.js, src/constants.js
- The highlight of search results is not specific to the given search but now highlight all kinds of data in the record
- Refs: https://issues.folio.org/browse/UIIN-1454
- Render `Instance HRID` with `Highlighter` component when `instance` is searched by `Instance HRID`.
- Highlight `Barcode` only when `item` is searched by `Barcode`
Ideally all of the PRs …
=> UIIN-1454: Add Highlighter for Instance HRID

CHANGELOG.md, src/Instance/InstanceDetails/InstanceAcquisition/InstanceAcquisition.js, src/Item/ViewItem/ItemAcquisition/ItemAcquisition.js, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-1946 …
=> UIIN-1946 update Date ordered label to Date opened

CHANGELOG.md, src/Holding/ViewHolding/HoldingAquisitions/HoldingAquisitions.js, src/Holding/ViewHolding/HoldingAquisitions/HoldingAquisitions.test.js, src/ViewHoldingsRecord.js, src/edit/holdings/HoldingsForm.js
https://issues.folio.org/browse/UIIN-1943 …
=> UIIN-1943 Missing Field - Receipt status under the Edit Holdings View

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIIN-1972 …
=> UIIN-1972 search.holdings.ids.collection.get permission missing from package.json

CHANGELOG.md, src/routes/buildManifestObject.js
https://issues.folio.org/browse/UIIN-1957 …
=> UIIN-1957: Browse form has hardcoded limit of the returned records

CHANGELOG.md, src/components/InstancesList/InstancesList.js
https://issues.folio.org/browse/UIIN-1960 …
=> UIIN-1960: Incorrect rendering of returned records

CHANGELOG.md, src/components/InstancesList/InstancesList.js
https://issues.folio.org/browse/UIIN-1961 …
=> UIIN-1961 Browse form flickers

src/components/InstancesList/InstancesList.js
Previous and next navigation of a large list of search results (100+) has stopped working
https://issues.folio.org/browse/UIIN-1951 …
=> UIIN-1951: Previous and next navigation of a large list of search results (100+) has stopped working

CHANGELOG.md, src/components/InstancesList/InstancesList.js
Facets in Browse subjects and call numbers appear after reload page
https://issues.folio.org/browse/UIIN-1965
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
=> UIIN-1965: Facets in Browse subjects and call numbers appear after reload page

CHANGELOG.md, src/routes/buildManifestObject.js
https://issues.folio.org/browse/UIIN-1990 …
=> UIIN-1990 Remove expandAll parameter from browse requests

CHANGELOG.md, package.json, src/index.js
Remove react-hot-loader
https://issues.folio.org/browse/UIIN-1981
=> UIIN-1981: Remove react-hot-loader

CHANGELOG.md, package.json, src/ViewInstance.js, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-547 …
=> UIIN-547 Action for creating an order from instance

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/providers/DataProvider.js
https://issues.folio.org/browse/UIIN-2038 …
=> UIIN-2038: Cannot read properties of undefined (reading 'shelfKey')

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, src/Instance/InstanceMovement/InstanceMovementContainer.js
Refs [UIIN-2049](https://issues.folio.org/browse/UIIN-2049)
=> UIIN-2049 bump CI node version to 16

src/components/InstancesList/InstancesList.js
https://issues.folio.org/browse/UIIN-2038 …
=> UIIN-2038:Cannot read properties of undefined (reading 'shelfKey')

CHANGELOG.md, src/components/InstancesList/InstancesList.js
https://issues.folio.org/browse/UIIN-1912 …
=> UIIN-1912 Browse form - first and last record navigation

CHANGELOG.md, src/Instance/HoldingsList/Holding/HoldingButtonsGroup.test.js
Created Jest/RTL test for HoldingButtonsGroup
[UIIN-1673](https://issues.folio.org/browse/UIIN-1673)
=> UIIN-1746: Create Jest/RTL test for HoldingButtonsGroup

src/edit/items/ItemForm.js, src/settings/ContributorTypesSettings.test.js, test/jest/__mock__/stripesSmartComponents.mock.js
create Jest/RTL test for ContributorTypesSettings.js
[UIIN-1673](https://issues.folio.org/browse/UIIN-1673)
=> UIIN-1673 create Jest/RTL test for ContributorTypesSettings

CHANGELOG.md, src/ViewHoldingsRecord.js
https://issues.folio.org/browse/UIIN-2101
=> UIIN-2101: Fix reference to instanceSource name.

CHANGELOG.md, src/components/InstancesList/InstancesList.js
https://issues.folio.org/browse/UIIN-2093 …
=> UIIN-2093:Browse call numbers records found count is non-sensical

CHANGELOG.md, src/filterConfig.js
The `Contributors` search should return more specific results.
[UIIN-2134](https://issues.folio.org/browse/UIIN-2134)
https://user-images.githubusercontent.com/77053927/181795964-5e100422-2cdb-454a-a5dd-f8d78bf7f606.mp4 …
=> UIIN-2134: Browse contributors: # of results on the list is not the same as what the Contributors search returns

CHANGELOG.md, translations/ui-inventory/en.json
After changes in this this ticket [MSEARCH-401](https://issues.folio.org/browse/MSEARCH-401), we can't search/browse call-numbers by shelving order (shelfKey).
So it's more accurate to rename `Effective call number (item), shelving order` -> `Effective call number (item)`
[UIIN-2151](https://issues.folio.org/browse/UIIN-2151)
Ideally all of the PRs …
=> UIIN-2151: Remove shelving order in search option

CHANGELOG.md, src/components/InstancesList/InstancesList.js
https://issues.folio.org/browse/UIIN-2131 …
=> UIIN-2131 Clearing filters after clicking "Previous"/"Next" buttons in Inventory tab on Browse form

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/routes/buildManifestObject.js, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-2171 …
=> UIIN-2171 Fix clicking on the row by returning shelving order

src/components/InstancesList/InstancesList.js
https://issues.folio.org/browse/UIIN-2171 …
=> UIIN-2171 Use shelfKey when navigating through call number browse

CHANGELOG.md, src/routes/buildManifestObject.js
https://issues.folio.org/browse/UIIN-2143 …
=> UIIN-2143: Escape quotes in search string

CHANGELOG.md, package.json, src/components/BrowseResultsPane/BrowseResultsPane.js, src/components/BrowseResultsPane/BrowseResultsPane.test.js, src/components/BrowseResultsPane/index.js, src/components/InstancesList/InstancesList.js, src/components/SearchModeNavigation/SearchModeNavigation.js, src/components/SearchModeNavigation/SearchModeNavigation.test.js, src/components/SearchModeNavigation/index.js, src/components/index.js, src/constants.js, src/index.js, src/routes/BrowseRoute/BrowseRoute.js, src/routes/BrowseRoute/BrowseRoute.test.js, src/routes/BrowseRoute/index.js, src/routes/index.js, src/views/BrowseInventory/BrowseInventory.js, src/views/BrowseInventory/BrowseInventory.test.js, src/views/BrowseInventory/index.js, src/views/index.js, test/jest/helpers/translationsProperties.js, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-2193
Add a new route to move the "Browse" logic to a separate page.
- Define a new route `inventory/browse`
- Add `stripes-acq-components` to deps (To reuse existing hooks, components and utils)
- Create base components for "Browse" functionality (For now it's just a blank page with two panes)
- Create toggle component (`<SearchModeNavigation>`) to switch between "Search" and "Browse" modes
- Add `<SearchModeNavigation>` to "Search" and "Browse" pages
- Add unit test to new components
<details>
<summary>Preview</summary>
</details>
If there are breaking changes, …
=> UIIN-2193 Define new route for Inventory "Browse" page

CHANGELOG.md, src/Instance/InstanceDetails/InstanceContributorsView/InstanceContributorsView.css, src/Instance/InstanceDetails/InstanceContributorsView/InstanceContributorsView.js, src/Instance/InstanceDetails/InstanceContributorsView/InstanceContributorsView.test.js, src/Instance/InstanceDetails/InstanceDetails.js
Add a link to the MARC authority app when an `Instance` record with source = `MARC` is linked to an authority record. 
[UIIN-2180](https://issues.folio.org/browse/UIIN-2180)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …
=> UIIN-2180: View Instance record | Contributors accordion | Show authorized indicator for each contributor

CHANGELOG.md, src/ViewInstance.js
Reorder the action menu on the instance view.
https://issues.folio.org/browse/UIIN-2097
=> UIIN-2097: Reorder the action menu on the instance view

CHANGELOG.md, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-2165
Fix `effectiveCallNumber` translation.
=> UIIN-2165: Fix effectiveCallNumber translation

CHANGELOG.md, src/components/InstancesList/InstancesList.js
Remove the ability to sort by publishers.
https://issues.folio.org/browse/UIIN-2200
=> UIIN-2200: Remove the ability to sort by publishers

CHANGELOG.md, src/routes/buildManifestObject.js
[UIIN-2201](https://issues.folio.org/browse/UIIN-2201) …
=> UIIN-2201: Escape quotes in browse string

CHANGELOG.md, src/filterConfig.js, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-2198
Add HRID and UUID to keyword search for instance, holdings and item.
=> UIIN-2198: Add HRID and UUID to keyword search for instance, holdings and item

src/components/InstancesList/InstancesList.js, src/hooks/useInventoryBrowse/useInventoryBrowse.js
I want a clean slate before I start work on UIIN-2197.
=> Disable some ESLint warnings

CHANGELOG.md, src/edit/InstanceForm.js, src/edit/electronicAccessFields.js, src/edit/holdings/HoldingsForm.js, src/edit/holdings/note.js, src/edit/items/ItemForm.js
Add ability to choose blank state for all select fields on the holdings form.
https://issues.folio.org/browse/UIIN-2121
=> UIIN-2121: Add ability to choose blank state for all select fields

CHANGELOG.md, src/filterConfig.js, translations/ui-inventory/en.json
Add ability to search by circulation notes in items
https://issues.folio.org/browse/UIIN-945
=> UIIN-945: Add ability to search by circulation notes in items

CHANGELOG.md, src/ViewHoldingsRecord.test.js, src/components/ImportRecordModal/ImportRecordModal.js, src/hooks/useInventoryBrowse/useInventoryBrowse.js, src/routes/InstancesRoute.test.js, src/settings/TargetProfiles.js
=> Fetch up to 1000 SRI sources, sorted by name

src/components/BrowseInventoryFilters/BrowseInventoryFilters.test.js, src/components/BrowseResultsList/BrowseResultsList.test.js, src/components/MissedMatchItem/MissedMatchItem.test.js, src/hooks/useBrowseValidation/useBrowseValidation.test.js, src/hooks/useInventoryBrowse/useInventoryBrowse.test.js, src/views/BrowseInventory/BrowseInventory.js, src/views/BrowseInventory/BrowseInventory.test.js
https://issues.folio.org/browse/UIIN-2203
Add unit tests to new components, related to #1798 
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
=> UIIN-2203 Add unit tests to new components of 'Browse' functionality

CHANGELOG.md, src/components/BrowseInventoryFilters/BrowseInventoryFilters.js, src/components/BrowseResultsList/BrowseResultsList.css, src/components/BrowseResultsList/BrowseResultsList.js, src/components/BrowseResultsList/constants.js, src/components/BrowseResultsList/getBrowseResultsFormatter.js, src/components/BrowseResultsList/getBrowseResultsFormatter.test.js, src/components/BrowseResultsPane/BrowseResultsPane.js, src/hooks/useInventoryBrowse/constants.js, src/hooks/useInventoryBrowse/useInventoryBrowse.js, src/hooks/useInventoryBrowse/useInventoryBrowse.test.js, src/views/BrowseInventory/BrowseInventory.js
https://issues.folio.org/browse/UIIN-2202
- Add updates and fixes, that have been made for browse functionality;
- Add ability to use pagination. Update `useInventoryBrowse` hook to support page changing;
- Update unit tests. …
=> UIIN-2202 Add pagination for results list in `Browse` page

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/routes/InstancesRoute.test.js
https://issues.folio.org/browse/UIIN-2211 …
=> UIIN-2211 Quick instances export - add a select all option to Inventory search results

src/components/InstancesList/InstancesList.js, src/routes/InstancesRoute.test.js
https://issues.folio.org/browse/UIIN-2211
scenario №6 …
=> UIIN-2211 Remove limit of exported records

CHANGELOG.md, src/ViewHoldingsRecord.js
https://issues.folio.org/browse/UIIN-2229 …
=> UIIN-2229 Missing holdings' source is populated in the UI with instance's source

CHANGELOG.md, src/components/InstancesList/InstancesList.js
https://issues.folio.org/browse/UIIN-2240 …
=> UIIN-2240 Selecting a row with multiple Call number entries is failed

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIIN-2241 …
=> UIIN-2241 'Inventory: Create order from instance' also grants delete POL permission

CHANGELOG.md, src/ViewInstance.js
Always display the actual record version in the URL (`relatedRecordVersion`).
see [pool request](https://github.com/folio-org/ui-quick-marc/pull/408)
[UIIN-2244](https://issues.folio.org/browse/UIIN-2244)
[UIQM-319](https://issues.folio.org/browse/UIQM-319)
[UIQM-319 pool request](https://github.com/folio-org/ui-quick-marc/pull/408)
Ideally all of the PRs …
=> UIIN-2244: Not actual "relatedRecordVersion" value sends when user saves "MARC Bib" record

CHANGELOG.md, src/ViewInstance.js, src/ViewInstance.test.js, src/components/BrowseInventoryFilters/BrowseInventoryFilters.js, src/components/BrowseResultsList/BrowseResultsList.js, src/components/BrowseResultsList/BrowseResultsList.test.js, src/components/InstancesList/InstancesList.js, src/components/InstancesList/InstancesList.test.js, src/components/InstancesList/instances.css, src/components/SearchModeNavigation/SearchModeNavigation.js, src/filterConfig.js, src/hooks/useInventoryBrowse/useInventoryBrowse.js, src/routes/InstancesRoute.js, src/routes/InstancesRoute.test.js, src/routes/buildManifestObject.js, src/views/BrowseInventory/BrowseInventory.js, src/withFacets.js, test/jest/__mock__/stripesCore.mock.js
https://issues.folio.org/browse/UIIN-2186
- show toggle between "Search" and "Browse" pages;
- provide `InstancesList` with location state `browseSearch` to identify that instance(s) was opened from "Browse" page and add ability to return back to the last browse results;
- hide "move ..." actions from instance details action menu if instance was opened from the Browse page (use `openedFromBrowse` prop in `IntsanceView`);
- highlight the record in Browse results list after return back to the "Browse" page (use `itemToView` to identify the MCL row);
- clean up old code related to browse functionality (`InstancesList.js`, `InstancesRoute.js`, `buildManifestObject.js`,  `instances.css`,  `filterConfig.js`);
- update unit tests.
Before merging this PR, please go through the following list and …
=> UIIN-2186 Browse refactor: Show instance result in third pane when Number of titles = 1

src/components/InstanceFilters/instanceFilterRenderer.js, src/filterConfig.js, src/routes/InstancesRoute.js, src/withFacets.js
https://issues.folio.org/browse/UIIN-2259
https://issues.folio.org/browse/UIIN-2186
While …
=> UIIN-2186 UIIN-2259 Search options for holdings and item segment has been wiped out

src/components/InstancesList/InstancesList.js, src/routes/InstancesRoute.test.js
[UIIN-2234](https://issues.folio.org/browse/UIIN-2234) …
=> UIIN-2234: Revert commit that was intended for Orchid

src/settings/ModesOfIssuanceSettings.test.js
Refs:
Ticket: [UIIN-1726]
URL: https://issues.folio.org/browse/UIIN-1726
=> create Jest/RTL test for ModesOfIssuanceSettings.js

src/settings/MaterialTypesSettings.test.js
Refs: Ticket [UIIN-1794]
https://issues.folio.org/browse/UIIN-1794
=> create Jest/RTL test for MaterialTypesSettings.js

src/settings/ResourceTypesSettings.test.js
Refs:
Ticket- [UIIN-1791]
URL: https://issues.folio.org/browse/UIIN-1791
=> UIIN-1791 create Jest/RTL test for ResourceTypesSettings.js

src/settings/StatisticalCodeTypes.test.js
Refs:
Ticket: [UIIN-1788]
URL: https://issues.folio.org/browse/UIIN-1788
=> UIIN-1788 create Jest/RTL test for StatisticalCodeTypes.js

src/settings/NatureOfContentTermsSettings.test.js
Refs:
Ticket: [UIIN-1754]
URL:  https://issues.folio.org/browse/UIIN-1754
=> create Jest/RTL test for NatureOfContentTermsSettings.js

src/settings/ClassificationTypesSettings.test.js
Refs:
Ticket - [UIIN-1753]
URL: https://issues.folio.org/browse/UIIN-1753
=> UIIN-1753 create Jest/RTL test for ClassificationTypesSettings.js

src/settings/URLRelationshipSettings.test.js
Refs:
Ticket: [UIIN-1729]
URL: https://issues.folio.org/browse/UIIN-1729
=> UIIN-1729 create Jest/RTL test for URLRelationshipSettings.js

src/settings/HoldingsTypeSettings.test.js
Refs:
Ticket- [UIIN-1748]
URL: https://issues.folio.org/browse/UIIN-1748
=> create Jest/RTL test for HoldingsTypeSettings.js

src/settings/HoldingsSourcesSettings.test.js
Refs:
Ticket: [UIIN-1759]
URL: https://issues.folio.org/browse/UIIN-1759
=> UIIN-1759 create Jest/RTL test for HoldingsSourcesSettings.js

src/settings/IdentifierTypesSettings.test.js
Refs:
Ticket: [UIIN-1681]
URL: https://issues.folio.org/browse/UIIN-1681
=> create Jest/RTL test for IdentifierTypesSettings.js

CHANGELOG.md, src/constants.js, src/settings/HRIDHandling/HRIDHandlingForm.js, test/bigtest/helpers/formatDateString.js, test/bigtest/interactors/settings/hrid-handling/hrid-handling.js, test/bigtest/mocks/hridSettings.js, test/bigtest/tests/settings/hrid-handling/hrid-handling-test.js
To add the Created/Updated by and when widget to the HRID Settings page
- Render `ViewMetaData` component
- Add tests
https://issues.folio.org/browse/UIIN-2139
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially …
=> UIIN-2139: Add create/update widget to HRID Settings page

CHANGELOG.md, src/filterConfig.js
https://issues.folio.org/browse/UIIN-2274
This PR reverts to `all` operator for title (All)  index.
=> UIIN-2274: Revert back to 'all' operator for title (All) index

src/ViewInstanceWrapper.test.js
create Jest/RTL test for ViewInstanceWrapper.js
Refs: [UIIN-1727](https://issues.folio.org/browse/UIIN-1727)
=> UIIN-1727: create Jest/RTL test for ViewInstanceWrapper.js

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIIN-2273
=> UIIN-2273: Add inventory-storage.bound-with-parts.collection.get to inventory: All permissions

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIIN-2273
=> UIIN-2273: Add inventory-storage.bound-with-parts.collection.get to inventory: View instances

CHANGELOG.md, src/index.js, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-2265 …
=> UIIN-2265 Inventory | App Context menu | Add new option | Inventory app search

src/ConnectedInstance/makeConnectedInstance.test.js
Refs:
ui-inventory
Ticket- [UIIN-1755]
URL: https://issues.folio.org/browse/UIIN-1755
=> UIIN-1755 create Jest/RTL test for makeConnectedInstance.js

src/validation.test.js
Jest/RTL test for validation.js
Refs: [UIIN-1690](https://issues.folio.org/browse/UIIN-1690)
=> UIIN-1690: Jest/RTL Tests for validation.js

src/Instance/utils.test.js
Jest/RTL tests for src/Instance/utils.js
Refs: [UIIN-1777](https://issues.folio.org/browse/UIIN-1777)
=> UIIN-1777: Create Jest/RTL tests for src/Instance/utils.js

CHANGELOG.md, package.json
[UIIN-2283](https://issues.folio.org/browse/UIIN-2283) …
=> UIIN-2283: Users with browse permissions can delete inventory records

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIIN-2280 …
=> UIIN-2280 Include browse permissions into Inventory permissions

src/components/InstancesList/InstancesList.js, src/constants.js, src/filterConfig.js, src/routes/buildManifestObject.js, src/utils.js
https://issues.folio.org/browse/UIIN-2036
This is a continuation of work from https://github.com/folio-org/ui-inventory/pull/1911 
This PR adds support for additional item indexes (isbn, issn, hrid, id) when searching and opening a single item.
=> UIIN-2036: Add support for more item indexes

CHANGELOG.md, src/settings/TargetProfiles.js
* Remove typo in toasts Z39.50
* Replace `entryLabel={this.props.label}` with `entryLabel={<FormattedMessage id="ui-inventory.targetProfile" />}`
[UIIN-2256](https://issues.folio.org/browse/UIIN-2256)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …
=> UIIN-2265: Fix toasts text in Z39.50 Settings

src/Instance/HoldingsList/Holding/HoldingContainer.js, src/Instance/ItemsList/ItemsListRow.js, src/components/HoldingsRecordFilters/HoldingsRecordFilters.js, src/components/InstanceFilters/InstanceFilters.js, src/components/InstanceFilters/InstanceFiltersBrowse/InstanceFiltersBrowse.js, src/components/InstancesList/InstancesList.js, src/components/ItemFilters/ItemFilters.js, src/settings/TargetProfileDetail.js, src/settings/TargetProfileDetail.test.js, src/settings/TargetProfileForm.test.js
=> Lintstones! Meet the Lintstones!

CHANGELOG.md, src/settings/TargetProfileDetail.js
To fix accessibility issues on the ISRI Z39.50 integration profile: View
- Add `columnIdPrefix` to MCLs to make ids unique
- Create STCOM-1074 ticket to fix remaining issues
- Fix eslint warnings
https://issues.folio.org/browse/UIIN-2251
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
=> UIIN-2251: Make ids for job profiles tables unique

src/components/ImportRecordModal/ImportRecordModal.js
To fix title of modal and job profiles sorting
- Change the title for Overlays
- Fix query for job profiles sorting
- Fix eslint issues …
=> UIIN-2253: ISRI: Update the Inventory modal for ISRI single/multi source Overlays

CHANGELOG.md, src/settings/TargetProfileForm.js, src/settings/TargetProfileForm.test.js, translations/ui-inventory/en.json
To add an info icon to remind users not to assign MARC Holdings/Authority job profiles to ISRI Z39.50 targets.
- Render info icons next to `Job profiles for create/update` labels
- Add unit tests
https://issues.folio.org/browse/UIIN-2306
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
=> UIIN-2306: ISRI: Add job profile-related info icons to Z39.50 create/edit screen

CHANGELOG.md, src/Instance/InstanceDetails/InstanceContributorsView/InstanceContributorsView.js, src/components/BrowseResultsList/BrowseResultsList.test.js, src/components/BrowseResultsList/getBrowseResultsFormatter.js
Open an authorized record after clicking on the `MARC Authority` icon.
[UIIN-2302](https://issues.folio.org/browse/UIIN-2302)
[ui-quick-marc](https://github.com/folio-org/ui-quick-marc/pull/446)
https://user-images.githubusercontent.com/77053927/214104578-ce51c591-8dff-4f1e-9d4a-00f627d2a8b0.mp4
Ideally all of the PRs involved in breaking changes would be …
=> UIIN-2302: Reference MARC Authority record is opened when user clicks on the "MARC Authority" icon next to the controlled field

CHANGELOG.md, package.json, src/components/BrowseResultsList/getBrowseResultsFormatter.js, src/components/BrowseResultsList/getBrowseResultsFormatter.test.js, src/hooks/useInventoryBrowse/constants.js
Update `browse` interface and align related changes
https://issues.folio.org/browse/UIIN-2296
- update interfaces versions;
- update search param for `subjects` browse;
- update formatter to get appropriate field from content data (`value` instead of `subject`);
- update unit tests
Ideally all of the PRs involved in breaking changes would be merged in the …
=> UIIN-2296 Align the module with API breaking change (browse)

package.json
While it's helpful for reviewers to help identify potential problems, ensuring that it's …
=> Fix interface version

CHANGELOG.md, src/components/BrowseResultsList/utils.js
https://issues.folio.org/browse/UIIN-2314
https://issues.folio.org/browse/UIIN-2296
Another place, that have to be updated according to "search" API changes
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as …
=> UIIN-2314 Align subjects query building with API changes

CHANGELOG.md, src/components/InstancesList/InstancesList.js
[UIIN-2304](https://issues.folio.org/browse/UIIN-2304) …
=> UIIN-2304: Hide Export to json option in Action menu

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIIN-2319 …
=> UIIN-2319 Bump `@folio/stripes-acq-components` version to `4.0.0`

CHANGELOG.md, src/views/ItemView.js, src/views/ItemView.test.js, translations/ui-inventory/en.json
Add an information icon next to `Effective call number` and `Shelving order`.
[UIIN-2307](https://issues.folio.org/browse/UIIN-2307)
https://user-images.githubusercontent.com/77053927/215778275-3f05c0b1-6a92-4772-a050-a7eccc34dbe3.mp4
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
=> UIIN-2307: Create info popovers on call number fields in item record

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIIN-2303
Bump stripes to 8.0.0 for Orchid/2023-R1
=> UIIN-2303: Bump stripes to 8.0.0 for Orchid/2023-R1

package.json
Whoops; missed stripes-connect in #1963
Refs [UIIN-2303](https://issues.folio.org/browse/UIIN-2303)
=> UIIN-2303 correctly bump stripes-connect to 8.1.0

src/Item/hooks/useItem/useItem.test.js
Fix linting errors I introduced in #1985.
https://issues.folio.org/browse/UIIN-2326
=> UIIN-2326 Fix linting errors on useItem.test.js

src/edit/formUtils.test.js
Refs:
Ticket: UIIN-1781
create Jest/RTL test for formUtils.js
URL: https://issues.folio.org/browse/UIIN-1781
=> UIIN-1781 create Jest/RTL test for formUtils.js

src/Instance/InstanceMovement/InstanceMovementDetails/InstanceMovementDetailsContainer.test.js
REFS:
UIIN-1803
InstanceMovementDetailsContainer
URL: https://issues.folio.org/browse/UIIN-1803
=> UIIN-1803 JEST/RTL test cases for InstanceMovementDetailsContainer

src/edit/editionFields.test.js
Create Jest/RTL test for editionFields.js
[UIIN-1792](https://issues.folio.org/browse/UIIN-1792)
=> UIIN-1792 create Jest/RTL test for editionFields.js

src/reports/InTransitItemsReport.test.js
Create Jest/RTL test for InTransitItemReport.js
Refs: [UIIN-1693](https://issues.folio.org/browse/UIIN-1693)
=> UIIN-1693 create Jest/RTL test for InTransitItemReport.js

src/Instance/InstanceDetails/InstanceRelationshipView/utils.test.js
REFS: UIIN-1724
utils
URL: https://issues.folio.org/browse/UIIN-1724
=> UIIN-1724 JEST/RTL test cases for utils

src/referenceFormatters.test.js
Refs: 
UIIN-1738
referenceFormatters
URL: https://issues.folio.org/browse/UIIN-1738
=> UIIN-1738 JEST/RTL test cases for the referenceFormatters

src/common/hooks/useConfirmationModal.test.js
References:
UIIN-1804
useConfirmationModal
url: https://issues.folio.org/browse/UIIN-1804
=> UIIN-1804 JEST/RTL test cases for useConfirmationModal

src/facetUtils.test.js
UIIN-1610 JEST/RTL test cases for facetUtils
REFS: https://issues.folio.org/browse/UIIN-1610
=> UIIN-1610 JEST/RTL test cases for facetUtils

src/RemoteStorageService/Warning.test.js
UIIN-1795 JEST/RTL test case of Warning
REF: https://issues.folio.org/browse/UIIN-1795
=> UIIN-1795 JEST/RTL test case for Warning

src/Instance/InstanceDetails/InstanceClassificationView/InstanceClassificationView.test.js
Refs:
UIIN-1742 
create Jest/RTL test for InstanceClassificationView.js
URL: https://issues.folio.org/browse/UIIN-1742
=> UIIN-1742 create Jest/RTL test for InstanceClassificationView.js

src/Instance/InstanceDetails/InstanceElecAccessView/InstanceElecAccessView.test.js
Refs:
UIIN-1780
create Jest/RTL test for InstanceElecAccessView.js
URL: https://issues.folio.org/browse/UIIN-1780
=> UIIN-1780 create Jest/RTL test for InstanceElecAccessView.js

src/Instance/HoldingsList/HoldingsList.test.js
UIIN-1685 JEST/RTL test case for HoldingsList
References:
URL: https://issues.folio.org/browse/UIIN-1685
=> UIIN-1685 JEST/RTL test case for HoldingsList

src/Instance/InstanceDetails/InstanceNotesView/InstanceNotesView.test.js
UIIN-1787 JEST/RTL test case for InstanceNotesView
REF: https://issues.folio.org/browse/UIIN-1787
=> UIIN-1787 JEST/RTL test case for InstanceNotesView

src/Instance/InstanceDetails/InstanceDescriptiveView/InstanceDescriptiveView.test.js
UIIN-1672 JEST/RTL test case for InstanceDescriptiveView
REF: https://issues.folio.org/browse/UIIN-1672
=> UIIN-1672 JEST/RTL test case for InstanceDescriptiveView

src/Instance/ItemsList/DropZone.test.js
UIIN-1736 JEST/RTL test cases for DropZone
References:
url: https://issues.folio.org/browse/UIIN-1736
=> UIIN-1736 JEST/RTL test cases for DropZone

src/providers/HoldingsProvider.test.js
create Jest/RTL test for HoldingsProvider.js
Refs: [UIIN-1709](https://issues.folio.org/browse/UIIN-1709)
=> UIIN-1709: create Jest/RTL test for HoldingsProvider.js

src/Instance/InstanceDetails/SubInstanceGroup/SubInstanceGroup.test.js
Refs:
Ticket: UIIN-1716 create Jest/RTL test for SubInstanceGroup.js
URL: https://issues.folio.org/browse/UIIN-1716
=> UIIN-1716 create Jest/RTL test for SubInstanceGroup.js

CHANGELOG.md, src/components/BrowseResultsPane/BrowseResultsPane.js, src/hooks/useInventoryBrowse/useInventoryBrowse.js, src/hooks/useInventoryBrowse/useInventoryBrowse.test.js, src/views/BrowseInventory/BrowseInventory.js
https://issues.folio.org/browse/UIIN-2299 …
=> UIIN-2299 Browse results in Inventory are not cleared when browse input field is cleared

src/contexts/DataContext.test.js
Create Jest/RTL test for src/contexts/DataContext.js
Refs: [UIIN-1717](https://issues.folio.org/browse/UIIN-1717)
=> UIIN-1717 create Jest/RTL test for src/contexts/DataContext.js

src/edit/holdings/RemoteStorageWarning.test.js, test/jest/__mock__/stripesSmartComponents.mock.js
Create Jest/RTL test for src/edit/holdings/RemoteStorageWarning.js
Refs: [UIIN-1805](https://issues.folio.org/browse/UIIN-1805)
=> UIIN-1805 create Jest/RTL test for RemoteStorageWarning.js

src/Instance/InstanceDetails/InstanceAdministrativeView/StatisticalCodesList.test.js
Create JEST/RTL tests for StatisticalCodesList.js
Refs: [UIIN-1786](https://issues.folio.org/browse/UIIN-1786)
=> UIIN-1786: Create JEST/RTL tests for StatisticalCodesList.js

src/Instance/ViewRequests/useFetchItems.test.js
UIIN-1723 JEST/RTL test cases for useFetchItems
URL: https://issues.folio.org/browse/UIIN-1723
=> UIIN-1723 JEST/RTL test cases for useFetchItems

CHANGELOG.md, src/Instance/InstanceDetails/InstanceRelationshipView/InstanceRelationshipView.test.js, src/Instance/InstanceEdit/ChildInstanceFields/ChildInstanceFields.test.js, src/Instance/InstanceEdit/InstanceEdit.test.js, src/Instance/InstanceEdit/ParentInstanceFields/ParentInstanceFields.test.js, src/ViewInstance.test.js, src/components/BrowseInventoryFilters/BrowseInventoryFilters.js, src/components/BrowseInventoryFilters/BrowseInventoryFilters.test.js, src/components/HoldingsRecordFilters/HoldingsRecordFilters.test.js, src/components/InstanceFilters/InstanceFilters.test.js, src/components/InstanceFilters/InstanceFiltersBrowse/instanceFiltersBrowse.test.js, src/components/InstancesList/InstancesList.test.js, src/components/ItemFilters/ItemsFilters.test.js, src/edit/holdings/HoldingsForm.test.js, src/edit/items/ItemForm.test.js, src/routes/InstancesRoute.test.js, src/views/ItemView.test.js, test/jest/__mock__/index.js, test/jest/__mock__/stripesConnect.mock.js, test/jest/__mock__/stripesCore.mock.js
https://issues.folio.org/browse/UIIN-2367
=> UIIN-2367: Avoid private paths in stripes-core imports

src/hooks/useCallout.test.js
Create Jest/RTL test for useCallout.js
Refs: [UIIN-1743](https://issues.folio.org/browse/UIIN-1743)
=> UIIN-1743 Create Jest/RTL test for useCallout.js

src/Instance/InstanceDetails/InstanceDescriptiveView/DescriptiveFormatsList.test.js
Refs:
UIIN-1749 create Jest/RTL test for DescriptiveFormatsList.js
URL: https://issues.folio.org/browse/UIIN-1749
=> UIIN-1749 create Jest/RTL test for DescriptiveFormatsList.js

src/common/hooks/useFacets.test.js
UIIN-1584 create JEST/RTL test cases for useFacets.js
URL: https://issues.folio.org/browse/UIIN-1584
=> UIIN-1584 create JEST/RTL test cases for useFacets.js

CHANGELOG.md, src/Holding/ViewHolding/HoldingReceivingHistory/HoldingReceivingHistory.js, src/Holding/ViewHolding/HoldingReceivingHistory/HoldingReceivingHistory.test.js
[UIIN-2411](https://issues.folio.org/browse/UIIN-2411) - display chronology column in receiving history accordion section
- add a `chronology` column for the visible columns section
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to …
=> UIIN-2411 - display chronology column in receiving history

CHANGELOG.md, package.json, test/bigtest/network/factories/request.js
Also support circulation 14.0
Field fulfilmentPreference was renamed to fulfillmentPreference. This changes do not affect current module.
https://issues.folio.org/browse/UIIN-2412
=> UIIN-2412: Also support circulation 14.0

CHANGELOG.md, package.json, src/Instance/InstanceMovement/InstanceMovementContainer.js, src/Instance/InstanceMovement/InstanceMovementContainer.test.js
Fix the `records-editor/records` request by adding the correct `_actionType`.
[UIIN-2431](https://issues.folio.org/browse/UIIN-2431)
https://github.com/folio-org/ui-inventory/assets/77053927/3ceb22d3-2f27-4156-ab68-a080240560ab
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
=> UIIN-2431: Fix the `records-editor/records` request by adding the correct `_actionType`.

CHANGELOG.md, src/components/FilterNavigation/FilterNavigation.js, src/components/InstancesList/InstancesList.js, src/components/InstancesList/InstancesList.test.js, src/constants.js, translations/ui-inventory/en.json
Added sort options in Actions for Instance/Holdings/Item
[UIIN-2357](https://issues.folio.org/browse/UIIN-2357)
1. Start at default sort by title, changing in menu sorts with selected option
https://github.com/folio-org/ui-inventory/assets/128044179/db569cf4-b3db-4ae8-8937-f2e8f47e5d37
2. Selected sort options are remember between switch instance/browse/item tab
https://github.com/folio-org/ui-inventory/assets/128044179/2e2f0fde-1e2b-4656-b743-5abfc2d35075
- Do JIRAs exist to …
=> UIIN-2357 Added sort options in Actions for Instance/Holdings/Item

CHANGELOG.md, src/edit/statisticalCodeFields.js
[UIIN-2420](https://issues.folio.org/browse/UIIN-2420)
* If user try to edit Items and adding empty statistical code field and clicking Save button, then error appeared 
* Added `validation` prop to Statistical code field
* Added `placeholder` prop to Statistical code field
* Removed default option from data options
Ideally all of the PRs involved in …
=> UIIN-2420: Add validation to statistical code field & disable default option

CHANGELOG.md, src/ViewInstance.js, src/ViewInstance.test.js, translations/ui-inventory/en.json
[UIIN-2430](https://issues.folio.org/browse/UIIN-2430) …
=> UIIN-2430: Quick export from instance detail view

CHANGELOG.md, translations/ui-inventory/en.json
* Some Inventory menu action options have been added/adjusted, but are not in sentence case
[UIIN-2436](https://issues.folio.org/browse/UIIN-2436)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …
=> UIIN-2436: Adjust the sentence case for some Inventory action options

CHANGELOG.md, src/edit/items/ItemForm.js
https://issues.folio.org/browse/UIIN-2282
leverage cookie-based authentication in all API requests, removing the request header x-okapi-token and adding the request option credentials: "include" in all FOLIO API requests. …
=> UIIN-2282: leverage cookie-based authentication in all API requests

CHANGELOG.md, src/components/FilterNavigation/FilterNavigation.js, src/components/InstancesList/InstancesList.test.js, src/settings/CallNumberTypes.js, src/settings/CallNumberTypes.test.js, test/jest/__mock__/stripesSmartComponents.mock.js
Remove the Edit and Delete icons to do nothing with the system call number types.
[UIIN-2385](https://issues.folio.org/browse/UIIN-2385) …
=> UIIN-2385: Restrict modifying and deleting system call number types.

CHANGELOG.md, src/constants.js, src/settings/AlternativeTitleTypesSettings.js, src/settings/CallNumberTypes.js, src/settings/CallNumberTypes.test.js, src/settings/ClassificationTypesSettings.js, src/settings/ContributorTypesSettings.js, src/settings/FormatsSettings.js, src/settings/HoldingsNoteTypesSettings.js, src/settings/HoldingsSourcesSettings.js, src/settings/HoldingsTypeSettings.js, src/settings/IdentifierTypesSettings.js, src/settings/InstanceNoteTypesSettings.js, src/settings/InstanceStatusTypesSettings.js, src/settings/ItemNoteTypesSettings.js, src/settings/LoanTypesSettings.js, src/settings/MaterialTypesSettings.js, src/settings/ModesOfIssuanceSettings.js, src/settings/NatureOfContentTermsSettings.js, src/settings/ResourceTypesSettings.js, src/settings/StatisticalCodeSettings.js, src/settings/StatisticalCodeTypes.js, src/settings/URLRelationshipSettings.js, src/utils.js
https://issues.folio.org/browse/UIIN-2482
Prevent editing or deleting controlled vocabulary settings with the "consortium" source.
Note: applied for the settings from the [list](https://wiki.folio.org/display/FOLIJET/Consortium+manager+settings)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
=> UIIN-2482 Prevent editing of shared settings from outside "Consortium manager"

src/constants.js
Fix advanced search indexes for identifier and call number
[UIIN-1920](https://issues.folio.org/browse/UIIN-1920)
=> UIIN-1920 Fix some advanced search indexes

CHANGELOG.md, src/common/hooks/useInstanceQuery/useInstanceQuery.js
"Something went wrong" screen appears when adding Item to Holdings
- Set default value to optional arg
https://issues.folio.org/browse/UIIN-2534
=> UIIN-2534: "Something went wrong" screen appears when adding Item to Holdings

CHANGELOG.md, src/components/InstanceFilters/InstanceFiltersBrowse/InstanceFiltersBrowse.js, src/components/InstanceFilters/InstanceFiltersBrowse/instanceFiltersBrowse.test.js, src/constants.js, src/withFacets.js
Show Effective location facet for all Call Number browse sub-options.
Need to change `callNumber` to corresponding field in `withFacets` when browsing by call numbers ,but this requires BE changes first
https://github.com/folio-org/ui-inventory/assets/19309423/89b57965-f16c-4315-8262-f1c6ee19715e
[UIIN-2499](https://issues.folio.org/browse/UIIN-2499)
=> UIIN-2499 Show Effective location facet for all Call Number browse sub-options.

CHANGELOG.md, src/ViewInstance.js, src/ViewInstance.test.js, src/components/ActionItem/ActionItem.js, src/components/ActionItem/ActionItem.test.js, src/components/ActionItem/index.js, src/components/index.js
To hide some action items on the instance details pane from the central tenant user.
- Implement `ActionItem` component to render action dropdown items
- Do not show `Move items within an instance`, `Move holdings/items to another instance`, `New order`, `View requests`, `Add MARC holdings record` action items if a user is in the central tenant
- Refactor `ViewInstance` `Action menu` unit tests
https://issues.folio.org/browse/UIIN-2498
=> UIIN-2498: Consortial Central Tenant: Handling of Instance Action Menu options

package.json
Add permission to instance view for `useUserTenantPermissions`.
[UIIN-2540](https://issues.folio.org/browse/UIIN-2540)
=> UIIN-2540: Add permission to instance view for useUserTenantPermissions.

CHANGELOG.md, src/Instance/HoldingsList/Holding/HoldingAccordion.js, src/Instance/ItemsList/ItemsListContainer.js
* Display correct number of items in the Instance's Holdings accordion because RMB sends estimated total of items
* Is duplicated by PR #2252 
* Set `limit=0` to get exact number of items in `HoldingAccordion` component
* Create separate request to get exact number of items in `ItemsListContainer` component to avoid bugs when interact with pagination
[UIIN-2550](https://issues.folio.org/browse/UIIN-2550)
https://github.com/folio-org/ui-inventory/assets/85172747/b28156eb-9665-4cb6-9459-1bfa91197bde
https://github.com/folio-org/ui-inventory/assets/85172747/c961d070-878b-48a7-9a29-65ce74c5a55e
=> UIIN-2550: Display correct number of items in the Instance's Holdings accordion

CHANGELOG.md, src/components/InstanceFilters/InstanceFiltersBrowse/InstanceFiltersBrowse.js, src/components/InstanceFilters/InstanceFiltersBrowse/instanceFiltersBrowse.test.js, src/filterConfig.js
Add Inventory Browse facet for Call numbers (item) on Shared vs Not shared Instances
https://github.com/folio-org/ui-inventory/assets/19309423/14c02e2f-8c57-43c7-af42-b068a827cfe0
[UIIN-2407](https://issues.folio.org/browse/UIIN-2407)
=> UIIN-2407 Add Inventory Browse facet for Call numbers (item) on Shared vs Not shared Instances

src/ViewInstance.js, src/ViewInstance.test.js
Follow-up PR
Fixed unsuccessful request handling
=> UIIN-2460: Fix unsuccessful request handling

src/components/HoldingsRecordFilters/HoldingsRecordFilters.js, src/components/InstanceFilters/InstanceFilters.js, src/components/InstanceFilters/InstanceFiltersBrowse/InstanceFiltersBrowse.js, src/components/ItemFilters/ItemFilters.js
Show Held by facets in central tenant
[UIIN-2395](https://issues.folio.org/browse/UIIN-2395)
=> UIIN-2395 Show Held By facet in central tenant

CHANGELOG.md, src/ViewInstance.js, translations/ui-inventory/en.json
Add an Inventory UI permission that will allow a user to share a local instance with other members in their consortium.
- A new BE visible permission `Inventory: Share local instance with consortium` was added to mod-consortia
- Check for this permission if a user is a member tenant and wants to promote a local instance to be shared then display Share local instance action
- Add translation for the permission
https://issues.folio.org/browse/UIIN-2571
=> UIIN-2571: Add permission to promote a local instance to shared

src/components/HeldByFacet/HeldByFacet.js, src/components/HeldByFacet/index.js, src/components/HoldingsRecordFilters/HoldingsRecordFilters.js, src/components/InstanceFilters/InstanceFilters.js, src/components/InstanceFilters/InstanceFiltersBrowse/InstanceFiltersBrowse.js, src/components/ItemFilters/ItemFilters.js, src/components/index.js
Add an input field for the `Held by` facet.
Created a separate component for the facet in order to add missed props only in one place.
Missed props in the `CheckboxFacet`: 
- `isFilterable` - adds an input field for facet;
- `onSearch` - filters options when a user searches through facet's input field;
- `onFetch` - fetch all options when the user focuses the facet's input field. When the user opens the facet for the first time, the request for the facets is made with a limitation of only 6 options, when the user puts a cursor into the input field, the request is made for all options. This was how it was originally intended.
[UIIN-2416](https://issues.folio.org/browse/UIIN-2416)
=> UIIN-2416: Add an input field for the 'Held by' facet.

src/Instance/InstanceDetails/InstanceDetails.js
To remove duplicated code that was left after resolving merge-conflicts
=> UIIN-2523: Remove duplicated Consortial holdings accordion

CHANGELOG.md, src/components/InstanceFilters/InstanceFiltersBrowse/InstanceFiltersBrowse.js, src/components/InstanceFilters/InstanceFiltersBrowse/instanceFiltersBrowse.test.js
Hide Held by facet in Inventory contributor and subject browse until back-end implementation is done
[UIIN-2591](https://issues.folio.org/browse/UIIN-2591)
=> UIIN-2591 Hide Held by facet in Inventory contributor and subject browse

src/settings/CallNumberTypes.js, src/settings/CallNumberTypes.test.js
Centralized management of consortium settings should be restricted to the Consortium tenant.
One settings section to prevent was missed - Call number types.
The changelog has been updated in the initial PR - #2199 .
Prevent editing and deleting call number types with source `consortium`.
https://issues.folio.org/browse/UIIN-2482
https://github.com/folio-org/ui-inventory/assets/88109087/611699fb-c08e-45c1-a614-d871dfe056b0
=> UIIN-2482 Prevent editing of shared call number types settings from outside 'Consortium manager'

CHANGELOG.md, src/Instance/InstanceEdit/InstanceField/InstanceField.js
=> Release v10.0.6

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/components/InstancesList/InstancesList.test.js, src/views/BrowseInventory/BrowseInventory.js, translations/ui-inventory/en.json
Inventory app > Search and Browse Results > Update HTML page title with search term entered
https://github.com/folio-org/ui-inventory/assets/19309423/be3e487c-da2e-4311-99bd-4bc30572efe4
[UIIN-2581](https://issues.folio.org/browse/UIIN-2581)
https://github.com/folio-org/stripes-core/pull/1377
=> UIIN-2581: Inventory app > Search and Browse Results > Update HTML page title with search term entered

CHANGELOG.md, src/ViewInstance.js, src/components/InstancesList/InstancesList.js
[UIIN-2660](https://issues.folio.org/browse/UIIN-2660)
Here we just added condition for ` export marc` based on permission from `ui-data-export`
=> UIIN-2660: Users with data export view only permission

src/ViewInstance.test.js
One test is failing due to timeout. Increased timeout to 10s.
=> Increase timeout for a failing test

CHANGELOG.md
=> Release v10.0.8

CHANGELOG.md, package.json, translations/ui-inventory/en.json
[UIIN-2705](https://issues.folio.org/browse/UIIN-2705)
=> UIIN-2705: Rename permission for Staff suppressed facet

CHANGELOG.md, test/jest/__mock__/index.js, test/jest/__mock__/resizeObserver.mock.js
[UIIN-2738](https://issues.folio.org/browse/UIIN-2738)
=> UIIN-2738: Mock ResizeObserver to fix failed tests

CHANGELOG.md, package.json
[UIIN-2761](https://issues.folio.org/browse/UIIN-2761) - xBump up okapi interfaces for `pieces` (3.0)
=> UIIN-2761: Bump up okapi interfaces for `pieces` (3.0)

CHANGELOG.md, package.json
[UIIN-2761](https://issues.folio.org/browse/UIIN-2761) - UIIN-2761: update package.json with interfaces piece `3.0`
Updating the piece version according to the discussion here. after https://github.com/folio-org/ui-inventory/pull/2393#discussion_r1472876597
=> UIIN-2761: update package.json with interfaces piece `3.0`

CHANGELOG.md
=> Release v10.0.11

src/hooks/useInventoryBrowse/useInventoryBrowse.js
`keepPreviousData` was calculated incorrectly. It depended on `prevSearchIndex` which updated on every render
Now we set `prevSearchIndex` only when Browse request is called
Also it included `hasFilters` which was `true` when `qindex` or `query` are set. Now `hasFilters=true` only when actual filters are selected
https://github.com/folio-org/ui-inventory/assets/19309423/83c84005-e6e3-4ebe-a039-a6cea1c098c0
[UIIN-2802](https://folio-org.atlassian.net/browse/UIIN-2802)
=> UIIN-2802 Set prevSearchIndex when perfoming Browse, not when changing option (follow-up)

CHANGELOG.md, package.json
=> Release v11.0.1

CHANGELOG.md
=> Release v10.0.13

CHANGELOG.md, package.json, src/constants.js, src/filterConfig.js
=> Release v11.0.4

CHANGELOG.md, src/Holding/EditHolding/EditHolding.js, src/common/hooks/useHolding/useHolding.js, src/edit/InstanceForm.css, src/edit/InstanceForm.js, src/edit/holdings/HoldingsForm.css, src/edit/holdings/HoldingsForm.js, src/edit/holdings/HoldingsForm.test.js
Edit Inventory Holdings: Display a Save & keep editing button
https://github.com/folio-org/ui-inventory/assets/19309423/7f3f13e4-e487-4703-acb9-607db1332d5e
[UIIN-2404](https://folio-org.atlassian.net/browse/UIIN-2404)
=> UIIN-2404 Edit Inventory Holdings: Display a Save & keep editing button

src/components/InstancesList/InstancesList.js, src/components/InstancesList/InstancesList.test.js
Follow-up PR.
Translate search options on the main page.
`formatSearchableIndex` was hardcoded to use `ui-inventory` to translate search options. The `prefix` variable is legacy code.
[UIIN-2781](https://folio-org.atlassian.net/browse/UIIN-2781)
=> UIIN-2781: Translate search options.

CHANGELOG.md, package.json
The Spitfire team is going to introduce the changes that will lead to the API major version update in this PR [mod-inventory-storage#1024](https://github.com/folio-org/mod-inventory-storage/pull/1024).
- Upgrade "holdings-storage" API version
https://folio-org.atlassian.net/browse/UIIN-2926
=> UIIN-2926: "holdings-storage" API version upgrade

CHANGELOG.md, src/Item/EditItem/EditItem.js, src/Item/hooks/useItem/useItem.js, src/edit/items/ItemForm.css, src/edit/items/ItemForm.js, src/edit/items/ItemForm.test.js
Edit Inventory Items: Display a Save & keep editing button
https://github.com/folio-org/ui-inventory/assets/19309423/e42a23f7-dbde-4a5d-99ce-92463e7bcf6c
[UIIN-2456](https://folio-org.atlassian.net/browse/UIIN-2456)
=> UIIN-2456 Edit Inventory Items: Display a Save & keep editing button

src/Holding/EditHolding/EditHolding.js, src/Holding/EditHolding/EditHolding.test.js, src/Instance/InstanceEdit/InstanceEdit.js, src/Instance/InstanceEdit/InstanceEdit.test.js, src/Item/EditItem/EditItem.js, src/Item/EditItem/EditItem.test.js, src/Item/hooks/useItem/useItem.js, src/common/hooks/useHolding/useHolding.js, src/common/hooks/useInstance.js
use isFetching property to know when Instance/Holdings/Items is loading
`isLoading` is true only for initial load, but we need to know when records are re-fetched
[UIIN-2404](https://folio-org.atlassian.net/browse/UIIN-2404)
=> UIIN-2404 use isFetching property to know when Instance/Holdings/Items is loading (follow-up)

CHANGELOG.md, src/Instance/InstanceDetails/InstanceClassificationView/InstanceClassificationView.js, src/Instance/InstanceDetails/InstanceClassificationView/InstanceClassificationView.test.js, test/jest/__mock__/stripesSmartComponents.mock.js
Instance record > Classification accordion > Display a clipboard icon next to classification number
https://github.com/folio-org/ui-inventory/assets/19309423/7988913a-12fd-4fda-8748-03f7f7a4f915
[UIIN-2580](https://folio-org.atlassian.net/browse/UIIN-2580)
=> UIIN-2580 Instance record > Classification accordion > Display a clipboard icon next to classification number

CHANGELOG.md, src/Instance/ItemsList/ItemsList.js
The visual appearance of the Inventory app's instance pane has changed with more padding compared to the previous version in orchid. After Poppy upgrade, we noticed that the barcode column now occupies much more space when viewing items in an Inventory search. It’s so wide that we can hardly see any other useful information and have to scroll even more than before. And columns aren’t even resizable.
- Remove `columnWidth`
https://folio-org.atlassian.net/browse/UIIN-2925
=> UIIN-2925: Make item barcode column narrower

CHANGELOG.md, src/ViewInstance.js, src/utils.js
[https://folio-org.atlassian.net/browse/UIIN-2966](https://folio-org.atlassian.net/browse/UIIN-2966)
=> UIIN-2966 Enable View Source option for Linked Data source

CHANGELOG.md, src/edit/InstanceForm.js
[https://folio-org.atlassian.net/browse/UIIN-2967](https://folio-org.atlassian.net/browse/UIIN-2967)
=> UIIN-2967: Edit Instance for Linked Data source

CHANGELOG.md, src/ViewInstance.js, src/ViewInstance.test.js, src/constants.js
https://folio-org.atlassian.net/browse/UIIN-2965
=> UIIN-2965: Enable 'Edit in Linked Data Editor' option to Action dropdown

src/common/hooks/useBoundPieces/useBoundPieces.js
=> UIIN-2760 fix bound pieces item field

CHANGELOG.md, src/ViewInstance.js, src/constants.js
https://folio-org.atlassian.net/browse/UIIN-2978
=> UIIN-2978: Edit in LDE when source=MARC

CHANGELOG.md, src/Instance/HoldingsList/Holding/MoveToDropdown/MoveToDropdown.js, src/Instance/HoldingsList/Holding/MoveToDropdown/MoveToDropdown.test.js
Currently, if no items are selected during items movement within an instance, a user can still click on the Move to button, but the dropdown will be empty which is confusing, I suggest disabling the button in such case.
- Disable the "Move to" button when movement is within the instance and there are no items selected or there are no holdings to move to
- Update tests
https://folio-org.atlassian.net/browse/UIIN-2995
=> UIIN-2995: Disable Move to button if no items selected or no more holdings exists within an instance

CHANGELOG.md, src/views/BrowseInventory/BrowseInventory.js, src/views/BrowseInventory/BrowseInventory.test.js
For environment `https://folio-perf-quesnelia-okapi.ci.folio.org`: in order to revisit some of the issues related to browsing Local, Other scheme, and SuDoc call numbers, we need to hide these options from Call number browse. This way we can address known issues, especially with sorting. 
[UIIN-2923](https://folio-org.atlassian.net/browse/UIIN-2923)
=> UIIN-2923: Hide call number type options for Local, Other scheme, and SuDoc for perf environment.

src/index.js, src/routes/InstancesRoute.js, src/routes/InstancesRoute.test.js
in https://github.com/folio-org/stripes-inventory-components/pull/66 `tenantId` required prop was introduced
add `tenantId` prop for `InstanceRoute` component
=> UIIN-2923 pass tenantId in InstancesRoute

src/index.js
=> UIIN-2923 fix inventory navigation after tenantId introduction

CHANGELOG.md, src/ViewInstance.js, src/components/InstancesList/InstancesList.js
https://folio-org.atlassian.net/browse/UIIN-3003
Here we updated the required permissions for `quick export`, since we updated permissions in `data-export`
=> UIIN-3003: Update required permissions for quick export of instances

CHANGELOG.md, translations/ui-inventory/en.json
https://folio-org.atlassian.net/browse/UIIN-3007
=> UIIN-3007: Change casing of 'Linked data editor' label.

src/components/ViewSource/ViewSource.js
use Data export: Can upload files, export, download files and view logs to check for Export
[UIIN-3012](https://folio-org.atlassian.net/browse/UIIN-3012)
=> UIIN-3012 use Data export: Can upload files, export, download files and view logs to check for Export (follow-up)

CHANGELOG.md
[UIIN-3015](https://folio-org.atlassian.net/browse/UIIN-3015)
=> Release v11.0.5

package.json
Allow a user without edit permission (Settings (Inventory): Can view and edit general settings) to have the settings applied.
Add the `Display settings` view permissions to the `Inventory: View instances, holdings, and items` permission.
[UIIN-2722](https://folio-org.atlassian.net/browse/UIIN-2722)
=> UIIN-2722: Add the `Display settings` view permissions to the `Inventory: View instances, holdings, and items` permission (follow-up PR).

src/Instance/InstanceDetails/InstanceDescriptiveView/InstanceDescriptiveView.js, src/Instance/InstanceDetails/InstanceDescriptiveView/InstanceDescriptiveView.test.js, src/Instance/InstanceDetails/InstanceDetails.js
Show Date Type, Date1 and Date2 on Instance View page
[UIIN-2849](https://folio-org.atlassian.net/browse/UIIN-2849)
=> UIIN-2849 Show Date Type, Date1 and Date2 on Instance View page (follow-up)

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/components/InstancesList/InstancesList.test.js, src/settings/DisplaySettings/DisplaySettings.test.js, src/utils.js, test/fixtures/instances.js, test/jest/__mock__/stripesInventoryComponents.mock.js, translations/ui-inventory/en.json
Add the ability to sort Search results by Date.
https://github.com/folio-org/stripes-inventory-components/pull/75
[UIIN-2850](https://folio-org.atlassian.net/browse/UIIN-2850)
https://github.com/user-attachments/assets/c5917f83-6f87-4bb8-9bd7-bc95abed5a3a
=> UIIN-2850: Add ability to sort Search results by Date.

CHANGELOG.md, src/components/InstancesList/InstancesList.test.js, src/components/SelectedRecordsModal/SelectedRecordsModal.js, src/routes/InstancesRoute.test.js, src/views/ItemView.js, src/views/ItemView.test.js, test/jest/__mock__/stripesComponents.mock.js
fix tests
[UIIN-3045](https://folio-org.atlassian.net/browse/UIIN-3045)
=> UIIN-3045: Mock Modal from stripes-components; fix tests.

CHANGELOG.md, src/index.js, src/routes/InstancesRoute.js
Fix eslint warnings
https://folio-org.atlassian.net/browse/UIIN-3064
=> UIIN-3064: Fix eslint warnings

src/utils.js
=> UIIN-2932: User affiliation and service point information missing when affiliation changes in Inventory (follow-up)

CHANGELOG.md, src/Instance/MoveHoldingContext/MoveHoldingContext.js, src/Instance/MoveHoldingContext/utils.js, src/Instance/MoveHoldingContext/utils.test.js, src/ViewHoldingsRecord.js, src/ViewHoldingsRecord.test.js, translations/ui-inventory/en.json
[UIIN-3063](https://folio-org.atlassian.net/browse/UIIN-3063): ECS: Item affiliation cannot be changed when it is attached to a local order
https://github.com/user-attachments/assets/b0195733-2a57-42a1-be3d-240426e05dc5
=> UIIN-3063: ECS: Item affiliation cannot be changed when it is attached to a local order

src/Instance/MoveHoldingContext/MoveHoldingContext.js
UIIN-3046: ECS Fix move holding to instance page refreshing issue(Follow up) https://folio-org.atlassian.net/browse/UIIN-3046?focusedCommentId=235665
https://github.com/user-attachments/assets/840a3776-f5d1-4ef2-be94-77607b316ea3
https://github.com/user-attachments/assets/023df527-d901-4c25-bca6-3d8b3dca57c3
=> UIIN-3046: ECS Fix move holding to instance page refreshing issue(Follow up)

CHANGELOG.md, src/Instance/InstanceDetails/InstanceDetails.js, src/Instance/InstanceDetails/InstanceDetails.test.js, src/views/VersionHistory/VersionHistory.js
Add Version history button and Version history pane to details view of Instance.
The list of version history cards will be created in scope of [UIIN-3174](https://folio-org.atlassian.net/browse/UIIN-3173).
- Added VersionHistory component to InstanceDetails component to create version history pane.
- Added VersionHistoryButton as lastMenu for instance details pane.
- Added unit tests
- Fixed existing warnings in unit tests for instance details pane
https://folio-org.atlassian.net/browse/UIIN-3170
=> UIIN-3170: Add Version history button and Version history pane to details view of Instance

CHANGELOG.md, src/edit/InstanceForm.js
Users without this permission will be able to see but NOT edit the 'Set for deletion' checkbox in Instance Edit view
The ‘Set for deletion’ checkbox should be greyed out and uneditable for users who don’t have the necessary permission.
- Grey out Set for deletion field if no permission.
https://folio-org.atlassian.net/browse/UIIN-3260
=> UIIN-3260: Update Inventory: Set records for deletion permission's effect on ‘Set for deletion’ checkbox in Instance Edit view

package.json
A user with `Settings (Inventory): Can view and edit general settings` permission should be able to view the `Version history` settings.
https://folio-org.atlassian.net/browse/UIIN-3213?focusedCommentId=255233
=> UIIN-3213: Add permission `audit.config.groups.settings.collection.get` to `Settings (Inventory): Can view and edit general settings` (follow-up).

CHANGELOG.md, src/ViewHoldingsRecord.js, src/hooks/useUpdateOwnershipMutation/useUpdateOwnershipMutation.js
* Display more detailed error message instead of "Server communication problem. Please try again"
[UIIN-3339](https://folio-org.atlassian.net/browse/UIIN-3339)
=> UIIN-3339: Display more detailed error message when updating ownership for holdings fails

src/edit/common/CommonAdditionalCallNumbersFields.js, src/utils.js
removes a c&p error which added a bad field.
handles removing a callNumberTypeId by removing the value instead of adding an empty string.
=> UIIN-3327 UIIN-3328 fixes a bug in additonalCallNumber handling

CHANGELOG.md, src/Instance/ViewInstance/ViewInstance.js, src/Instance/ViewInstance/components/InstanceModals/InstanceModals.js, src/Instance/hooks/useImportRecord/useImportRecord.js, src/Instance/hooks/useImportRecord/useImportRecord.test.js
* After overlaying the instance green success message does not appear. The instance is not updated. The green success message should appear. The updated instance is displayed in the 3rd pane.
* Pass args to API call.
* Update endpoint to overlay instance.
[UIIN-3450](https://folio-org.atlassian.net/browse/UIIN-3450)
https://github.com/user-attachments/assets/ef29156a-357c-4d19-9520-cb06cb38c19f
=> UIIN-3450: Fix instance overlaying issues

src/views/BrowseInventory/BrowseInventory.js
don't apply default Held By filter when a page loads with some filters already applied
[UIIN-3457](https://folio-org.atlassian.net/browse/UIIN-3457)
=> UIIN-3457 don't apply default Held By filter when a page loads with some filters already applied (follow-up)
