package.json
react-bootstrap isn't even in use in this repo any longer so we can prune it.
=> removing an unused dependency

CHANGELOG.md, Instances.js, ViewInstance.js, edit/InstanceForm.js, edit/creatorFields.js, test/ui-testing/new_title.js, utils.js
Reverts folio-org/ui-inventory#16
We do _eventually_ want to remove the `creator` field list, but currently it's still required by the backend. Jumped the gun a bit.
=> Revert "rm creator. Fixes UIIN-30"

CHANGELOG.md, Instances.js
In a CQL join clause, the entire clause must be quoted and the pieces of each clause should be quoted and escaped. Because the query is generated in JavaScript, we need to pass through the literal escape string, i.e. backslash-quote, to CQL.
=> Pass escape sequence through to CQL. Fixes UIIN-55

CHANGELOG.md, edit/holdings/HoldingsForm.js
Bug fix for [UIIN-54](https://issues.folio.org/browse/UIIN-54).  A `<Pane>` uses the attribute `onClose`, not `onClick`, to accept its on-close callback.
=> Correctly close 'Add holdings' pane. Fixes UIIN-54.

CHANGELOG.md, Instances.js
Bug fix for [UIIN-32](https://issues.folio.org/browse/UIIN-32). This was otherwise handled in #53; this fixes the typo on line 131.
=> Sort contributor types correctly. Refs UIIN-32

Instances.js
By passing in the new `maxSortKeys={1}` property: see STSMACOM-45.
Fixes UIIN-66.
=> Limit sorting to single-column at a time

CHANGELOG.md, Instances.js
UIIN-58 introduced show-single-result functionality, but that broke
some things, so it was made optional and off by default in STSMACOM-52.
This turns that option on.
Refs [UIIN-58](https://issues.folio.org/browse/UIIN-58), [STSMACOM-52](https://issues.folio.org/browse/STSMACOM-52).
=> restore show-single-result functionality.

CHANGELOG.md, edit/items/ItemForm.js
Whoops; must hydrate objects in validation tests for new item-records.
=> fix item-record validation for new items. Refs UIIN-61

Holdings.js, Items.js, ItemsPerHoldingsRecord.js, ViewHoldingsRecord.js, ViewInstance.js, ViewItem.js
Don't manully push onto props.history; use the anointed resource to read
and write URL state.
Refs [UIIN-122](https://issues.folio.org/browse/UIIN-122) but sadly does not actually fix it; it still takes two clicks on the backbutton to return to the previous page after viewing an item-detail page. 
Fixes [UIIN-123](https://issues.folio.org/browse/UIIN-123) item-detail should be a bookmarkable URL, [UIIN-124](https://issues.folio.org/browse/UIIN-124) holdings-detail should be a bookmarkable URL, [UIIN-128](https://issues.folio.org/browse/UIIN-128) holdings-edit regression.
=> don't manipulate history object directly

ViewHoldingsRecord.js, ViewItem.js
Adds the `<ViewMetadata>` component to Holding and Item views, in order to show info about when the record was created and last updated.
https://issues.folio.org/browse/UIIN-98
https://issues.folio.org/browse/UIIN-99
=> UIIN-98 & UIIN-99: Show metadata for holdings and items

translations/en.json
`<SearchAndSort>` relies on the translation key `resultCount`, which was not present. 
Refs [UIIN-100](https://issues.folio.org/browse/UIIN-100)
=> add missing translation key. Refs UIIN-100

CHANGELOG.md, Items.js
Briefly, I thought I could knock out [UIIN-148](https://issues.folio.org/browse/UIIN-148) (open item details in new tab) and [UIIN-122](https://issues.folio.org/browse/UIIN-122) (history is pushed twice when viewing item details from an external link), but alas that's not the case. 
This PR gets us down to a single handler for row-clicks, however, so that's something.
=> item double history push. Refs UIIN-122 

CHANGELOG.md, package.json, settings/ContributorTypesSettings.js, settings/FormatsSettings.js, settings/MaterialTypesSettings.js, settings/ResourceTypesSettings.js, settings/index.js, translations/en.json
- Added `code` as a field to Contributor Types, Resource Types, and Formats.
- Added `source` as a field to Contributor Types, Resource Types, Formats and Material Types.
- Split the Inventory settings into sections.
- Bumped requirement on `stripes-smart-components` in order to get [this PR's functionality](https://github.com/folio-org/stripes-smart-components/pull/171).
=> UIIN-149, UIIN-150, UIIN-151, UIIN-152: Added code and source fields to Settings pages

package.json, settings/ContributorTypesSettings.js, settings/FormatsSettings.js, settings/MaterialTypesSettings.js, settings/ResourceTypesSettings.js
Using the new `itemTemplate` [functionality provided here](https://github.com/folio-org/stripes-components/pull/376).
=> Settings: Default to a source of 'local' for newly-created types

CHANGELOG.md, ItemsPerHoldingsRecord.js, ViewHoldingsRecord.js, ViewInstance.js, ViewItem.js
Displaying metadata on the holdings- and item-edit forms requires
passing in stripes so we can connect those forms, but it was not being
passed in all locations where those forms are instantiated.
Refs [UIIN-191](https://issues.folio.org/browse/UIIN-191)
=> pass missing props.stripes to forms

CHANGELOG.md, ViewItem.js
Also, sort them by name.
Fixes UIIN-213.
=> Retrieve up to 40 loan-types for editing dropdown

CHANGELOG.md, test/ui-testing/inventorySearch.js
The old tests were unreliable. I dunno why that element they waited for
never seemed to trigger a rerender, but it didn't. Waiting for the
clear-all element instead of the clear-field element seems reliable.
Reliable tests are better than unreliable tests.
Fixes [UIIN-306](https://issues.folio.org/browse/UIIN-306)
=> wait for more reliable elements

CHANGELOG.md, src/ViewHoldingsRecord.js, src/ViewInstance.js, src/ViewItem.js, src/utils.js
`craftLayerUrl()` assists with `<SearchAndSort>`'s routing, and will be deprecated for any other use (modules should define their own routes, instead of relying on `<SearchAndSort>` to do it for them).
=> Copy craftLayerUrl() from stripes-components

CHANGELOG.md, package.json
In this release:
* Remove `instance.instanceFormatId`, add `instance.instanceFormatIds` (UIIN-330)
* Fix case-sensitive tests. Fixes UIIN-329.
* Add electronic access relationship reference data (UIIN-316)
* Requires: `inventory` interface (7.0) and `instance-storage` interface (5.0) (UIIN-316)
* Remove notes helper app (STRIPES-558)
* Copy `craftLayerUrl()` from `stripes-components` (Part of FOLIO-1547)
* Add dependency to stripes v1.0.0 to package.json. (Part of FOLIO-1547)
=> Release v 1.4.0

CHANGELOG.md, src/utils.js
The `stripes-components` `craftLayerUrl()` was deprecated from `stripes-components`, since routing is not the responsibility of a component library.
In the `stripes-components` version, `location` was accessed from `this.props`: https://github.com/folio-org/stripes-components/blob/3926f3c6e566b67a9876872dc952198b0d009992/util/craftLayerUrl.js
Now that it's passed in directly, it can get in a state where location is not yet defined. Check added to return null from `craftLayerUrl()` if `location` is not yet available.
=> Fix craftLayerUrl() loading state

CHANGELOG.md, src/ViewItem.js, src/utils.js
Uses out-of-the-box `react-intl` constructs instead of deprecated functions consumed off the `stripes` god object.
=> STCOR-267 Replace formatDateTime with <FormattedTime>

CHANGELOG.md, src/settings/ContributorTypesSettings.js, src/settings/FormatsSettings.js, src/settings/LoanTypesSettings.js, src/settings/MaterialTypesSettings.js, src/settings/ResourceTypesSettings.js
`<ControlledVocab>` now requires the sortby prop.
Refs [STSMACOM-139](https://issues.folio.org/browse/STSMACOM-139)
=> provide sortby clause to ControlledVocab

CHANGELOG.md, src/Instances.js
It looks like `resourceData.query.query` is undefined in some cases (I'm still not sure what those cases are). This PR sets the `term` to an empty string in cases when `query=undefined` in order to fix these kind of situations:
`query: (title="undefined*" or contributors adj "\"name\": \"undefined*\"" or identifiers adj "\"value\": \"undefined*\"") sortby title`
=> Default term to empty string in cases when query is undefined. Fixes UIIN-371.

test/ui-testing/new_title.js
The title attribute is being phased out so tests must hang off other
elements.
Refs [STCOM-296](https://issues.folio.org/browse/STCOM-296)
=> don't hang tests off title attribute

src/ViewInstance.js
Fixes https://issues.folio.org/browse/UIIN-384
https://github.com/folio-org/ui-inventory/pull/325 added `<div data-test-instance-details>` to the root of the instance view component to provide an easy point to hang a testing interactor. `<Paneset>`s need their direct children to be `<Pane>`s, so the layout calculations for the instance view were thrown off.
Move the `<div>` down one level to be a child of the `<Pane>`.
- `<Pane>` width calculations are relying on JavaScript that's throwing occasional performance warnings in Chrome. That needs some TLC.
- Maybe `<Pane>` should pass on all given props (like a `data-test-*` attribute) to its top-level div? Would've also prevented this issue from being introduced.
=> UIIN-384 Move data-test- div to fix pane layout

src/ItemsPerHoldingsRecord.js, src/ViewItem.js, src/edit/items/ItemForm.js, test/bigtest/interactors/item-create-page.js, test/bigtest/interactors/item-edit-page.js, test/bigtest/interactors/item-view-page.js, test/bigtest/network/config.js, test/bigtest/tests/item-edit-page-test.js, test/bigtest/tests/item-view-page-test.js, translations/ui-inventory/en.json
Add pane header dropdowns to Item create, edit pages. Also, replace text of the 'copy' drop-down action item with 'duplicate'.
- Create and pass `menuActionItems` prop with items to `Pane` component.
- Add tests to check dropdowns functionality
##Screenshots
Item details page:
New item create page:
Item edit page:
=> STCOM-396: Implement Pane header dropdown for Item pages

package.json
Depend on multiple versions of inventory interfaces
after merge -- but not release -- of inventory module changes.
=> Depend on multiple interface version for transition MODINVSTOR-231

test/bigtest/network/models/loan-type.js, test/bigtest/network/models/material-type.js, translations/ui-inventory/en.json
The BigTest output was pretty noisy with errors and warnings.
- Add `copyItem` translation to English
- Add missing mirage model declarations
- `A11y: please supply a string to the <Layer> prop 'contentLabel' for assistive technology users`: can be handled with https://issues.folio.org/browse/UIIN-381
- The CQL parser copied from https://github.com/indexdata/cql-js seems to have trouble parsing some of the query strings
=> Cleanup test output

src/ViewInstance.js
Renamed getActionMenu to createActionMenuGetter for better clarity of what's going on since we are passing the instance into the curried function.
=> Renamed getActionMenu to createActionMenuGetter

CHANGELOG.md, src/edit/InstanceForm.js
`<Checkbox>` fields need the `type="checkbox"` prop in order to
correctly cast their values.
Fixes [UIIN-417](https://issues.folio.org/browse/UIIN-417)
=> correctly show inventory-edit checkbox statuses

CHANGELOG.md, src/ViewItem.js
Add description of pieces to item detail screen.
https://issues.folio.org/browse/UIIN-447
=> Add description of pieces to item detail screen. Fixes UIIN-447.

CHANGELOG.md, test/bigtest/interactors/inventory.js
MCL recently changed how it uses some ARIA properties and the downstream
tests need to reflect this.
Refs [STRIPES-597](https://issues.folio.org/browse/STRIPES-597), [STCOM-365](https://issues.folio.org/browse/STCOM-365)
=> update BigTest interactor for MCL

CHANGELOG.md, src/edit/holdings/HoldingsForm.js
Add subheadings to the locations accordion on the holding record view.
https://issues.folio.org/browse/UIIN-416
=> Add subheadings to the locations accordion on the holding record view. Fixes UIIN-416.

test/ui-testing/filters.js
folio-org/stripes-components/pull/862 uses `kebabCase()` on checkbox ids
to make sure they are consistently formatted. This helps avoid illegal
values like `foo bar` but it also changed legal values like `Foo-Bar` to
`foo-bar` and that wasn't reflected in the tests. Until now!
Refs [STCOM-476](https://issues.folio.org/browse/STCOM-476)
=> checkbox-ids are all lowercase

package.json, src/Instances.js, src/ItemsPerHoldingsRecord.js, src/ViewHoldingsRecord.js, src/ViewInstance.js, src/ViewItem.js, src/withLocation.js
This PR is an attempt to replace navigation based on query resource with the tools provided by react-router. It should fix issues found in STCOM-302. 
I'm pretty sure the naming in the Location HOC (and perhaps `withLocation` name) could be improved. I wonder if you can come up with a better naming. 
I primary wanted to see if we can get rid of query resource completely and replace it with the set of navigation helpers (perhaps these helpers could be moved up to stripes-core eventually).
=> Replace query resource with react-router history push. Refs STCOM-302

src/ViewHoldingsRecord.js, src/ViewItem.js, src/ViewMarc.js, src/edit/holdings/HoldingsForm.js, src/edit/items/ItemForm.js, test/bigtest/interactors/item-edit-page.js, test/bigtest/tests/item-edit-page-test.js
In this PR I have updated how paneTitles are implemented in various components.
The primary purpose is to improve the design and ensure consistency across all modules.
=> Updated PaneHeaders in various components

src/ItemsPerHoldingsRecord.js
The problem is, an item form layer is created for each and every holdingsRecord when an add-item button is clicked, and the last layer (and thus holdingsRecord ID) wins.
In this PR, the current holdingsRecord ID is passed through the button and put on a "global variable"/resource that is queried before rendering any edit form layer, in order to only render the intended layer. 
Merely wondering, would using a 'resource' like this be best practice these days?
=> Ensure new item associated with intended holdingsRecord UIIN-492

package.json
It appears that a previous commit inadvertently added a dependency on an
unreleased version of react-intl-safe-html. In fact, that CI version is
the same as the formally released version, 1.0.2.
Fixes [UIIN-500](https://issues.folio.org/browse/UIIN-500)
=> use an officially released version

CHANGELOG.md, src/ViewHoldingsRecord.js
It looks like some of the lookup resources were refetched without the order in `ViewHoldingsRecord`. Most of them were already accessible via `parentResources` props from `Instances`:
https://github.com/folio-org/ui-inventory/blob/master/src/Instances.js#L222-L240
https://issues.folio.org/browse/UIIN-421
=> Fix alphabetical order of lookup tables. Fixes UIIN-421.

CHANGELOG.md, src/Instances.js
Don't append `*` to search terms automatically; let the user determine
if they want this. The way CQL is translated, a search for `foo` will
return things like `the foo and the bar` but not `foobar`.
Fixes [UIIN-481](https://issues.folio.org/browse/UIIN-481)
=> don't append wildcards to search terms

CHANGELOG.md, src/ViewItem.js
Lookup tables were missing their order-by and limit clauses.
Fixes [UIIN-522](https://issues.folio.org/browse/UIIN-522)
=> add missing sort clauses to lookup tables

CHANGELOG.md, src/edit/contributorFields.js
It's a boolean, not a string, as of [MODINV-117](https://issues.folio.org/browse/MODINV-117).
Fixes [UIIN-556](https://issues.folio.org/browse/UIIN-556)
=> send contributors.primary as correct type

test/ui-testing/test.js
This test is failing in CI but runs fine locally and behaves
differently locally where it creates a new item with title "0" whereas
in CI the barcode is being appended to the title.
There are many other places where we successfully create new instances
in tests so disabling this one is not a concern. The test behavior is a
puzzle but I don't think it indicates a problem with ui-inventory code.
=> temp disable new_title test

test/ui-testing/filters.js, test/ui-testing/search.js, test/ui-testing/test.js
Tests must accomodate the fact that inventory no longer shows any rows
until a search term or filter is applied. See #593.
Refs [UIIN-79](https://issues.folio.org/browse/UIIN-79)
=> UIIN-79: do not show results by default

CHANGELOG.md, package.json, src/components/RepeatableField/FieldRow.js, src/edit/holdings/note.js, src/edit/items/ItemForm.js
- Updated checkbox in item notes form to render label vertically and updated the column width to take up less space and leave more room for the input fields instead
- Updated RepeatableField component to allow for changing column widths
**Note:** The RepeatableField-component will soon be replaced with the matching component from stripes-components so the change of the RepeatableField-component within UI-Inventory is only temporary. Similar functionality will be possible when using the RepeatableField-component from stripes-components in the future because you will have more control over your row content.
=> UIIN-559: Update item notes form checkbox to render label vertically

src/edit/items/ItemForm.js
I missed this part of the UI in my previous PR.
**Note:** I also added `type: 'checkbox'` for the checkboxes again. I removed this in my last PR but I realized that it's needed for redux-form to treat the inputs as checkboxes.
=> UIIN-559:  Fix Loan and availability -> "Staff only"-checkbox alignment

CHANGELOG.md, test/ui-testing/new-title.js, test/ui-testing/test.js
The test was attempting to insert a value into a read-only field (hrid) and
nightmare handled this by leaving mouse-focus on the previous field,
causing the hrid value to be appended to the previously-focused field,
which would then cause the final search step to fail because the title
would not match the search string.
Fixes [UIIN-557](https://issues.folio.org/browse/UIIN-557)
=> UIIN-557 repair and enable new-title test

src/edit/holdings/HoldingsForm.js
The new-holdings-record button was named new-item-record. That ain't right. Practically, this change has absolutely no effect, but it reduces the cognitive dissonance when writing tests.
=> rename new-holdings-record button

CHANGELOG.md, package.json, src/Instances.js
RMB v26 provides a new search syntax for array values which is
implemented here for contributors and identifiers. It's hard to
overstate how happy I am about this.
Search syntax details at [RMB-380](https://issues.folio.org/browse/RMB-380); official documentation in the [rmb repository](https://github.com/folio-org/raml-module-builder/tree/master/cql2pgjson#-relation-modifiers-for-array-searches).
Fixes [UIIN-618](https://issues.folio.org/browse/UIIN-618), [UIIN-621](https://issues.folio.org/browse/UIIN-621), [UIIN-623](https://issues.folio.org/browse/UIIN-623), [UIIN-624](https://issues.folio.org/browse/UIIN-624)
=> UIIN-618 new search array syntax

package.json
Access to inventory settings was inadvertently removed in #613. We don't
need `settings.inventory.enabled` to be a visible permission, but we do
need it to be present so that stripes-core will discover that this
module has settings.
Fixes [UIIN-652](https://issues.folio.org/browse/UIIN-652), Refs [FOLIO-2184](https://issues.folio.org/browse/FOLIO-2184)
=> UIIN-652 restore settings

test/ui-testing/search.js
The `search` test was failing because it was looking for data that did
not exist. Tests should only interact with data they create, and now
this one does: it creates two instance records and searches for them by
title and and contributor.
Fixes [UIIN-656](https://issues.folio.org/browse/UIIN-656)
=> UIIN-656 fix "search" Nightmare test

CHANGELOG.md, src/edit/contributorFields.js
FK fields that contain UUIDs are now validated so an empty string fails
validation. This means an optional field containing a foreign key,
i.e. any field represented by a `<Select>` element, must be omitted from
the response rather than sent as an empty string.
Refs [UIIN-655](https://issues.folio.org/browse/UIIN-655)
=> UIIN-655 omit optional FK fields

src/Items.js
It looks like we have to recalculate the search params on render because they can be changed when applying different search and sort options. 
This change is related to https://issues.folio.org/browse/STSMACOM-232
=> Recalculate search params on rerender. Part of STSMACOM-232

CHANGELOG.md, src/ViewInstance.js
Non-interactive tables should not be presented as though they are
interactive.
Refs [UIIN-643](https://issues.folio.org/browse/UIIN-643)
=> UIIN-643 don't show static elements as interactive

src/ViewHoldingsRecord.js, src/ViewItem.js
Reorganizing so that we could easily pass a string instead of a
`<FormattedMessage>` to `contentLabel` involved wrapping the entire
block returned by `render()` with `<IntlConsumer>`, so we don't need to
wrap individual blocks with it anymore. Wrapping a block with
`<IntlConsumer>` also feels more elegant than with a
`<FormattedMessage>` so those have been cleaned up too.
=> console cleanup

src/edit/InstanceForm.js
the `canEdit` and `canDelete` props look like they were likely
copy-pasted from the above `RepeatableField` fields but they are not
valid props here.
=> don't pass invalid props

CHANGELOG.md, src/edit/holdings/HoldingsForm.js
The "suppress from discovery" checkbox on the holdings form was missing
a required attribute.
Fixes [UIIN-667](https://issues.folio.org/browse/UIIN-667)
=> UIIN-667 preserve checkbox state

test/ui-testing/filters.js
In some environments, the CI tests run with a narrow window and that
causes the DOM structure of the `<MultiSelect>` options to change. In
order to accommodate both narrow and wide windows, this PR changes the
selector so that it will succeed in either environment.
Refs [STCOM-554](https://issues.folio.org/browse/STCOM-554)
=> STCOM-554 more lenient selector is more robust

src/edit/items/ItemForm.js
Copy-number is an array on the backend but exposed as a non-repeatable
field on the front-end. Previously, the raw array was provided to the
`<Field>`, resulting in a prop-types console warning. Rather than converting
back and forth between array and scalar values, we just operate on the
first element of the array.
Replaces #691
=> clean up props-mismatch console warning

CHANGELOG.md, src/ViewItem.js
Damage status recently changed from an enumerable value to a lookup table
value backed by `id` and `name` attributes but the view-item page hadn't
been updated to reflect that and instead still showed the raw ID.
Refs [UIIN-683](https://issues.folio.org/browse/UIIN-683)
=> UIIN-683 show damage status value, not the ID

CHANGELOG.md, src/edit/items/ItemForm.js
Passing a `placeholder` prop to `<Select>` creates a disabled first
element. Here, we want a placeholder, but we want it enabled because
this field is optional.
Fixes [UIIN-696](https://issues.folio.org/browse/UIIN-696)
=> UIIN-696 allow unassigning of temporary loan type

CHANGELOG.md, package.json, src/settings/StatisticalCodeSettings.js
Forms in ui-inventory were converted from redux-form to
react-final-form, but `<ControlledVocab>` is a stripes-smart-component
form, not a ui-inventory form. Hence, its `<Field>` components must be
imported from `redux-form`.
Fixes [UIIN-725](https://issues.folio.org/browse/UIIN-725)
=> UIIN-725 correctly import Field

package.json
Reverts folio-org/ui-inventory#709
Reverting only so we can tag a patch release at tip-of-master; this is the only feature-commit since `v1.12.0` was released and reverting (and then reapplying) a single PR will be easier than cherry-picking everything since this PR onto a release branch. Yes, yes, we may want to investigate a different branching strategy like GitFlow in the long term to mitigate this process. Today, I just need to publish a release.
=> Revert "UIIN-727 update circulation API to v8"

package.json
"location-units" bumped to '2.0'.
=> UIIN-747: Fix the impact of the API change as per MODINVSTOR-315 for ui-inventory.

CHANGELOG.md, src/ViewItem.js
This is kind of a workaround for the issue described in https://issues.folio.org/browse/UIIN-773.
In order to address it properly we would have to fix the routing (get rid of the query resource and refactor search and sort).
The small change introduced in this PR will perform a search for related item in the request app before the creation form will be presented (which is actually a nice to have). As a side effect it should also fix UIIN-773.
=> Add query param to new request url. Part of UIIN-773

src/data/languages.json
It looks like some languages in ISO-639 have two codes: 
https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes
This PR updates the list and brings back the codes we had before to keep it consistent. It also adds more languages.
=> Update list of languages to match with the previous version. Part of UIIN-735.

package.json
Create permission that allows users (typical catalogers) to view instance records being check marked as 'Staff suppress'. Rename permissions according to requirements.
https://issues.folio.org/browse/UIIN-746
https://issues.folio.org/browse/UIIN-401
1. Rename permissions.
2. Add permission ""ui-inventory.item.markMissing".
=> UIIN-746,UIIN-401: Add permission "ui-inventory.instance.viewStaffSuppressed"

src/components/FilterNavigation/FilterNavigation.js, src/components/InstancesList/InstancesList.js, src/components/InstancesList/index.js, src/components/index.js, src/constants.js, src/index.js, src/routes/HoldingsRoute.js, src/routes/InstancesRoute.js, src/routes/ItemsRoute.js, src/routes/index.js, src/routes/withData.js, src/utils.js, src/views/HoldingsView.js, src/views/ItemsView.js, src/views/index.js, test/bigtest/interactors/holdings-edit-page.js, test/bigtest/interactors/instance-view-page.js, test/bigtest/interactors/inventory.js, test/bigtest/interactors/routes/holdings-route.js, test/bigtest/interactors/routes/items-route.js, test/bigtest/network/factories/instance.js, test/bigtest/tests/instances-index-test.js, test/bigtest/tests/mirage/routes/holdings-route-test.js, test/bigtest/tests/mirage/routes/items-route-test.js
This PR separates each search segment introduces in https://github.com/folio-org/ui-inventory/pull/753 into a separate route. I originally thought it wouldn't be possible to do so with SAS but it is by modifying `packageInfo` passed into SAS:
https://github.com/folio-org/ui-inventory/pull/763/files#diff-fd3611f373f0b1a809dc00c54a815ecbR145-R151
With this PR in place it should be a bit easier to refactor ui-inventory into `SearchAndSortQuery` in the future.
=> Another take on UIIN-758 with separate routes. 

src/components/InstancesList/InstancesList.js
The PR fixes a bug where only one filter could be active (when second filter was selected the previous one would clear out). 
Thanks to @Baroquem for spotting this issue!
=> Fix filter selection. Part of UIIN-758

src/ViewInstance.js, test/ui-testing/new-title.js, translations/ui-inventory/en.json
`noteTypeId` is not a required field, hence the display of notes must handle
those that do not specify a type. The previous incarnation would cause
an NPE when the type was undefined.
Refs [UIIN-643](https://issues.folio.org/browse/UIIN-643) / #779
=> UIIN-643 handle empty note-type

test/ui-testing/search.js
The nav-bar based selectors are going away and will be replaced by what
had been the nav-menu-item-selectors.
Refs [STCOR-377](https://issues.folio.org/browse/STCOR-377)
=> STCOR-377 use consistent selector

CHANGELOG.md, src/constants.js, test/bigtest/network/config.js
This PR changes the `=` CQL relation to `all` relation in order to support searching for "Title" with words out of order.
https://issues.folio.org/browse/UIIN-602
=> Allow for searching title with words out of order. Part of UIIN-602

src/components/FilterNavigation/FilterNavigation.js, test/ui-testing/filters.js
Location filters have moved from the default (instance) search segment
to the holdings segment. Likewise, item-status filters have moved to the
items segment.
This refactoring handles those changes and also pulls checkbox-based and
multiselect-based filter tests into their own reusable functions.
Refs [UIIN-679](https://issues.folio.org/browse/UIIN-679)
=> UIIN-679 update integration tests for segments

src/edit/InstanceForm.js, src/edit/holdings/HoldingsForm.js, src/edit/items/ItemForm.js
The exception we currently see in folio-testing is related to the fact that the `initialValues` are not present during the first render. This PR sets `initialValues` to an empty object by default.
Based on the findings from @zburke it looks like platform-core#snapshot uses different versions of final-form / react-final-form which causes this issue. Let's try to provide default value for `initialValues` first to see if this helps. If not we may need to lock the versions.
=> Default initialValues to empty object. Part of UIIN-875

CHANGELOG.md, src/ViewItem.js
Add support of a new field from a server response to maintain the item status date even if item record is edited. [Link](https://issues.folio.org/browse/UIIN-486)
=> UIIN-486: Add new item status date field support

test/ui-testing/filters.js
Previous versions contained `it` blocks in functions called by multiple
tests. This test failed in CI although it ran just fine in other
environments. This refactoring changes the test structure a bit so that
functions called by multiple tests do not contain `it` blocks.
Maybe we'll get lucky and Nightmare will be happy about that?
=> refactor `it` blocks in filter test

CHANGELOG.md, src/Items.js, src/ItemsPerHoldingsRecord.js, src/ViewInstance.js
It looks like there were couple places where the search `segment` was lost when navigating between views. This was causing issues described in  UIIN-886. This PR should fix it.
https://issues.folio.org/browse/UIIN-886
=> Use instance url with the correct search segment. Fixes UIIN-886

CHANGELOG.md, package.json
Rename permission, add required inventory permissions for possibility to use one general permission
with all Inventory perms
--- 
https://issues.folio.org/browse/UIIN-739
=> UIIN-739: Create one common inventory permission

package.json, src/reports/InstancesIdReport.js
Fix timestamp format in file name of instances UIIDs report. [Issue](https://issues.folio.org/browse/UIDEXP-1).
=> UIDEXP-1: Fix timestamp format in file name of instances UIIDs report

CHANGELOG.md, src/components/InstancesList/InstancesList.js, test/bigtest/interactors/inventory.js, test/bigtest/tests/export-to-csv-test.js
Disable saving instances UIIDs option if there are not items in search result in the scope of the [ticket](https://issues.folio.org/browse/UIDEXP-12).
=> UIDEXP-12: Disable saving instances UIIDs option if there are not items in search result

CHANGELOG.md, src/ItemsPerHoldingsRecord.js
The `limit` clause was missing from the `material-types` resource on the
item-edit page, causing it to retrieve only 10 records (the default) at
a time.
Refs [UIIN-946](https://issues.folio.org/browse/UIIN-946)
=> UIIN-946 retrieve up to 1000 material-types

CHANGELOG.md, package.json, test/bigtest/index.js
I have run the tests four times after making these changes. The tests now run, but none of the runs was clean, yielding three, five, ten and seven errors respectively. I don't know what can be done about that.
=> Replace deprecated babel dependencies. Refs UIIN-956, STCOR-381.

src/Items.js
Delete columnWidths property due to the overlapped headers in Item detailed list. [Source](https://issues.folio.org/browse/UIIN-954?focusedCommentId=70320&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-70320).
=> UIIN-954: Delete columnWidths prop due to the overlapped headers

CHANGELOG.md, src/routes/ItemRoute.js, src/routes/withData.js, src/views/ItemView.js
The testing if resources have been loaded under item route was buggy so this PR is trying to address it.
It's part of the work under: https://issues.folio.org/browse/UIIN-955
=> UIIN-955: Improve loading indicator under item route

CHANGELOG.md, src/ViewHoldingsRecord.js, test/bigtest/interactors/inventory.js
https://issues.folio.org/browse/UIIN-845
=> UIIN-845: Omit Former holdings ID when copying holdings record

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/components/InstancesList/instances.css
Reverts folio-org/ui-inventory#935
Original PR contains more changes than it should. As a precaution to prevent mess this PR will be reverted and another PR will be created with only relevant changes.
=> Revert "UIDEXP-32: Add Save icon to the Save Instances UUID"

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/components/InstancesList/instances.css
Add Save icon to the Save Instances UUIDs option in Action menu
[UIDEXP-32](https://issues.folio.org/browse/UIDEXP-32)
=> UIDEXP-32: Add Save icon to the Save Instances UUID (#935)

CHANGELOG.md, src/ViewInstance.js, src/components/TitlesView/TitlesView.js, src/components/TitlesView/index.js, src/components/index.js, test/bigtest/interactors/instance-view-page.js, test/bigtest/tests/instance-view-page-test.js
Display succeeding/preceding titles on instance view. Refs UIIN-961, UIIN-964 and UIIN-952.
https://issues.folio.org/browse/UIIN-952
https://issues.folio.org/browse/UIIN-961
https://issues.folio.org/browse/UIIN-964
=> UIIN-961: Display succeeding/preceding titles on connected and unconnected instance

CHANGELOG.md, package.json, src/components/InstancesList/InstancesList.js, src/routes/buildManifestObject.js, test/bigtest/interactors/inventory.js, test/bigtest/network/config.js, test/bigtest/tests/export-to-csv-test.js
Migrate to a new endpoint to request instances UIIDs to add more IDs to the request file.
Also, there are some extra changes:
- Fixed broken changes to fix tests executions for our purposes (Report and request file generation)
- Added icon for the action item "In transit items report"
- Covered by tests icons display
=> UIDEXP-28: Change endpoint to request instances UIIDs for report generation

CHANGELOG.md, src/components/InstancesList/InstancesList.js, test/bigtest/interactors/inventory.js, test/bigtest/tests/export-to-csv-test.js, translations/ui-inventory/en.json
Add new options with icons to action menu - _Export instances (MARC)_ and _Export instance (JSON)_
Add unit tests
Task: [UIDEXP-33](https://issues.folio.org/browse/UIDEXP-33)
=> UIDEXP-33: Add options to action menu

CHANGELOG.md, src/components/TitleField/TitleField.js, src/components/TitleField/index.js, src/components/index.js, src/edit/precedingTitleFields.js, src/edit/succeedingTitleFields.js, src/utils.js, test/bigtest/interactors/instance-edit-page.js, test/bigtest/tests/instance-edit-page-test.js
Add support for connected and connected succeeding titles.
https://issues.folio.org/browse/UIIN-962
https://issues.folio.org/browse/UIIN-963
=> UIIN-963: Add support for connected and connected succeeding titles

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/reports/exportStringToCSV.js, src/reports/index.js, src/routes/InstancesRoute.js, src/routes/buildManifestObject.js, test/bigtest/interactors/inventory.js, test/bigtest/tests/export-to-csv-test.js, translations/ui-inventory/en.json
- Add CQL search query report generation. [Story](https://issues.folio.org/browse/UIDEXP-2) 
- Add the added action item disabling if there are not instances in the search result. [Story](https://issues.folio.org/browse/UIDEXP-13)
=> UIDEXP-13, UIDEXP-2: Add instances CQL query report generation

src/edit/items/ItemForm.js
This makes validation behavior for item form consistent with instance and holdings forms.
=> UIIN-994: Remove 'validate on blur' param from ItemForm

package.json, src/components/InstancesList/InstancesList.js, src/routes/HoldingsRoute.js, src/routes/InstancesRoute.js, src/routes/ItemsRoute.js
Replace infinite scroll with a "Load more" button in the results list.
Infinite scroll can behave poorly when results lists are long.
Refs [CHAL-91](https://issues.folio.org/browse/CHAL-91)
=> CHAL-91 show "Load more" button

CHANGELOG.md, src/filterConfig.js
This PR is using the new config param called `operator` in order to use `==` for item status:
https://issues.folio.org/browse/UIIN-1048
It also uses correct operator (`==`) for hrid under instances, holdings and items:
https://issues.folio.org/browse/UIIN-1051
https://issues.folio.org/browse/UIIN-1052
https://issues.folio.org/browse/UIIN-1053
=> UIIN-1048: Use correct operator when searching by item status and hrid

CHANGELOG.md, src/filterConfig.js
https://issues.folio.org/browse/UIIN-1057
This PR correctly registers `instanceFormatIds` filter under instances segment.
=> UIIN-1057: Register instanceFormatIds format

CHANGELOG.md, src/components/InstanceFilters/InstanceFilters.js, src/constants.js, src/filterConfig.js, src/utils.js, test/bigtest/interactors/inventory.js, test/bigtest/network/config.js, test/bigtest/network/factories/instance.js, test/bigtest/tests/filters/instances/instance-filters-test.js, translations/ui-inventory/en.json
Add the ability to filter instances by date created. Story [UIIN-788](https://issues.folio.org/browse/UIIN-788).
The `Date created` filter implementation was based on the use of the DateRangeFilter component from the `stripes-smart-components` module.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
=> UIIN-788: Add filter for instance date created

CHANGELOG.md, package.json, src/filterConfig.js
Use `==` instead of `=` when searching by item-status and hrid.
Refs [UIIN-1048](https://issues.folio.org/browse/UIIN-1048)
=> UIIN-1048: Use == when searching by item status and hrid

CHANGELOG.md, package.json, src/edit/items/ItemForm.js, src/views/ItemView.js
Correctly import `@folio/stripes-util` (it's a sub-project of `@folio/stripes`).
This also means we'll get the correct/current version of `effectiveCallNumber`.
Refs [UIIN-1021](https://issues.folio.org/browse/UIIN-1021), [UIIN-1029](https://issues.folio.org/browse/UIIN-1029)
=> UIIN-1021: Import stripes-util via stripes

CHANGELOG.md, src/filterConfig.js, src/utils.js
https://issues.folio.org/browse/UIIN-1064
This PR changes the `buildOptionalBooleanQuery` to use `cql.allRecords=1` in cases when both `yes` and `no` boolean filters are chosen. It also changes the `=` operator to `==` for other cases.
@bohdan-suprun could you please take a look at this and let us know if this looks ok from the server side point of you?
=> UIIN-1064: Improve buildOptionalBooleanQuery performance

CHANGELOG.md, src/views/ItemView.js, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-984
Chalmers reports that 'When looking at an item record the staff finds the field "Item status date" confusing.' They would like it to be associated directly with the item status.
Fixes #984
- [x ] I've added appropriate record to the CHANGELOG.md
- [x ] Duplications on new code is 3% or less
- [x ] There are no major code smells or security issues
- [x ] There are no breaking changes in this PR.
=> UIIN-984: Show item status date with status

CHANGELOG.md, src/components/InstancePlugin/InstancePlugin.css, src/components/InstancePlugin/InstancePlugin.js, src/components/UnconnectedTitle/UnconnectedTitle.js, src/edit/InstanceForm.js, src/validation.js, test/bigtest/tests/instance-edit-page-test.js
Make the title element required for preceding and succeeding titles.
https://issues.folio.org/browse/UIIN-1033
https://issues.folio.org/browse/UIIN-1034
=> UIIN-1033: Make the title element required for preceding and succeeding titles

CHANGELOG.md, src/filterConfig.js
Register `instanceFormatIds` filter. 
Fixes [UIIN-1057](https://issues.folio.org/browse/UIIN-1057).
=> UIIN-1057: Register instanceFormatIds format (#970)

CHANGELOG.md, src/filterConfig.js, src/utils.js
This PR changes the `buildOptionalBooleanQuery` to use `cql.allRecords=1`
in cases when both yes and no boolean filters are chosen. It also changes
the `=` operator to `==` for other cases.
Fixes [UIIN-1064](https://issues.folio.org/browse/UIIN-1064)
=> UIIN-1064: Improve boolean filter performance

CHANGELOG.md, src/components/TitlesView/TitlesView.js, src/utils.js
Make the string to be wrapped with a space symbol in Preceding and Succeeding titles.
Story [UIIN-1036](https://issues.folio.org/browse/UIIN-1036).
=> UIIN-1036: Make the string to be wrapped with a space symbol

src/components/TitlesView/TitlesView.js
https://issues.folio.org/browse/UIIN-1036
Adjust column widths to avoid wrapping even when the width of the browser window is reduced.
Continued https://github.com/folio-org/ui-inventory/pull/1010.
=> UIIN-1036: Columns width adjustment

CHANGELOG.md, package.json
Pin `moment` at `~2.24.0` in light of multiple issues with `2.25.0` ([5489](https://github.com/moment/moment/issues/5489), [5472](https://github.com/moment/moment/issues/5472)).
=> pin moment to ~2.24

CHANGELOG.md, src/components/ConnectedTitle/ConnectedTitle.js
UIIN-1037 Preceding and Succeeding titles. Clicking on connected titles should not open new window
Currently, when users clicking on connected titles (Preceding and Succeeding titles), a new window will be opened which is incorrect. The new page should be opened in the same window. 
JIRA link: https://issues.folio.org/browse/UIIN-1037
Remove the target="_blank" in ConnectedTitles component where the url is rendered to the UI
=> UIIN-1037 don't open links in new windows

src/components/TitlesView/TitlesView.js
UIIN-1037 Preceding and Succeeding titles. Clicking on connected titles should not open new window
Currently, when users clicking on connected titles (Preceding and Succeeding titles), a new window will be opened which is incorrect. The new page should be opened in the same window.
JIRA link: https://issues.folio.org/browse/UIIN-1037
Remove the target="_blank" in ConnectedTitles and TitlesView component where the url is rendered to the UI
=> Removed: target_blank in TitlesView component

CHANGELOG.md, src/filterConfig.js, test/bigtest/network/config.js, test/bigtest/tests/filters/items/search-field-filter-test.js, translations/ui-inventory/en.json
Add ability to search by `Effective call number (item), normalized` option. Refs UIIN-993.
Based on the comments under UIIN-993 the full normalization happens on the backend which made this much easier to setup (Thank you @bohdan-suprun!).
https://issues.folio.org/browse/UIIN-993
=> UIIN-993: Search by call number normalized from item segment

CHANGELOG.md, src/filterConfig.js, test/bigtest/network/config.js, test/bigtest/network/factories/holding.js, test/bigtest/network/factories/instance.js, test/bigtest/tests/filters/holdings/search-field-filter-test.js, translations/ui-inventory/en.json
Add ability to search by `Call number, normalized` option via holdings segment. Story [UIIN-983](https://issues.folio.org/browse/UIIN-983).
=> UIIN-983: Search by call number normalized from holdings segment

CHANGELOG.md, src/constants.js, src/utils.js
Prevent items with the status `Claimed returned` from being marked as missing.
https://issues.folio.org/browse/UIIN-891
=> UIIN-891: Prevent items with the status  from being marked missing.

src/constants.js
It looks like there was an extra space added in "Claimed returned" status causing the search not to work correctly. This PR should address it.
https://issues.folio.org/browse/UIIN-957
=> UIIN-957: Fix filtering by claimed returned status

.gitignore, CHANGELOG.md, src/components/TitleLabel/TitleLabel.js
The request here was for one specific label to not be bold. I decided
the simplest way to fix that would be to apply an element-level style to
the label instructing that specific label not to display in bold. All other
labels will still be bold. I'm pretty sure the code I'm editing is only
used to generate specific labels for preceding and succeeding titles in the
edit view.
https://issues.folio.org/browse/UIIN-1039
- Are the …
=> UIIN-1039: Preceding and Succeeding Titles

src/views/ItemView.js
The additional check for `ui-inventory.items.mark-items-withdrawn` had to be added to make sure the actions menu will be visible. This PR is trying to address that.
https://issues.folio.org/browse/UIIN-889
=> UIIN-889: Add additional perm check for mark withdrawn

CHANGELOG.md, src/constants.js, src/utils.js, src/views/ItemView.js, translations/ui-inventory/en.json
Allow users to search & filter for items with the status Lost and paid. Refs UIIN-895
https://issues.folio.org/browse/UIIN-895
=> UIIN-895: Search for items with lost and paid status

CHANGELOG.md, src/routes/buildManifestObject.js
https://issues.folio.org/browse/UIIN-1046
This is intended to preserve the default sort order of instances, holdings, or item records when sorting or filtering. If no sort order is specified, the query sort order is set to 'title' during the query build.
=> UIIN-1046: Maintain default title sort when searching or filtering

CHANGELOG.md, src/edit/holdings/HoldingsForm.js
UIIN-477 Holdings record. Add space between: Suppress from Discovery and HRID
https://issues.folio.org/browse/UIIN-477
One line space is missing between 'Suppress from Discovery' and the holdings HRID element.
Add `<br>` code between 'Suppress from Discovery' and the holdings HRID element.
=> Holdings record. Add space between: Suppress from Discovery and HRID

CHANGELOG.md, package.json
Increment `@folio/plugin-find-instance` version to `^3` for
compatibility with `@folio/stripes` `4.0`.
=> increment plugin-find-instance to v3

CHANGELOG.md, src/components/TitleField/TitleField.js, src/components/UnconnectedTitle/UnconnectedTitle.js, src/edit/InstanceForm.js, src/edit/precedingTitleFields.js, src/edit/succeedingTitleFields.js
Disable instance records fields in preceding/succeeding section 
when the instance's source is `MARC`. 
Refs UIIN-1128
=> UIIN-1128 Disable some fields when Source is MARC 

CHANGELOG.md, package.json
Increment the `@folio/stripes` peer-dep to `^5.0.0` for `react-router`
`5.2.0` compatibility, and therefore increment other `@folio/stripes-*`
dev-deps as well.
=> increment @folio/stripes to v5.0.0

CHANGELOG.md, src/ViewInstance.js
For some time, ui-inventory hits
/source-storage/records/${inventory-id}/formatted?idType=INSTANCE 
even for records with "source": "FOLIO" rather than only those with "source": "MARC". 
It has the effect of logging lots of errors in the browser console.
- Delete componentDidMount section;
- Update condition related to the record source in the componentDidUpdate section
[UIIN-1190](https://issues.folio.org/browse/UIIN-1190)
=> UIIN-1190 Possible error for Source=FOLIO instances has been fixed

src/Instance/InstanceDetails/InstanceDescriptiveView/InstanceDescriptiveView.js, src/Instance/InstanceDetails/InstanceDescriptiveView/utils.js, src/components/InstanceFilters/InstanceFilters.js, src/edit/languageFields.js
https://issues.folio.org/browse/UIIN-829
My previous solution to localizing language names caused a problem in stripes-components that I overlooked: even though the code worked, the linter complained about the way that I was using useIntl(). This addresses that problem.
=> UIIN-829: Fix problem with use of useIntl() in stripes-components

CHANGELOG.md, src/ViewInstance.js
`Edit in quickMARC` and `View Source` options become grayed out after instance editing.
Get MARC record data after component mounted. When component updated, check if instance record id changed and update MARC record data. …
=> UIIN-1204: Fix Edit in quickMARC and View Source options state after instance editing

CHANGELOG.md, src/filterConfig.js, test/bigtest/network/config.js
https://issues.folio.org/browse/UIIN-1040
Add the ability to search for records in the `Holdings - Call number, eye readable` search option directly by the `callNumber` value.
This was achieved by adding the condition `callNumber == "$ {value}"` to the `CQL query` string.
=> UIIN-1040: Add search only by the call number

test/bigtest/network/serializers/application.js, test/bigtest/network/serializers/holding.js
In the process of migrating from `@bigtest/mirage` to `miragejs` in #1110, we found that Mirage payloads are missing `instanceId`. `miragejs` migration caused `Instances -> instance segment -> remember search results -> should keep search results around after item is closed` test to fail. 
We dug into why this test is failing and found that navigating from search results to instance view had `undefined` in the url. 
After further investigation, we found that `instanceId` was not being included in the payload in tests. 
1. `instanceId` is missing because Instance relationship is not being included in the payload. I added `serializeIds: 'always'` to Application serializer so ensure that relationships are always included. 
2. I changed the Application serializer that's used as a base for all …
=> Use Serializer and explicitely state whats included

src/Instance/InstanceDetails/InstanceDescriptiveView/InstanceDescriptiveView.js, src/Instance/InstanceDetails/InstanceDescriptiveView/utils.js, src/components/InstanceFilters/InstanceFilters.js, src/edit/languageFields.js
https://issues.folio.org/browse/UIIN-829
This PR simplifies the language-name-handling code based on the reworking of the stripes-components languages file (see https://github.com/folio-org/stripes-components/pull/1342)
=> UIIN-829: Improve handling of language names

CHANGELOG.md, src/filterConfig.js, test/bigtest/network/config.js
https://issues.folio.org/browse/UIIN-1041
Add the ability to search for records in the `Item - Effective call number (item), eye readable` search option directly by the `callNumber` value.
This was achieved by adding the condition `effectiveCallNumberComponents.callNumber == "${value}"` to the `CQL query` string.
=> UIIN-1041: Item segment - Add search only by the call number

test/ui-testing/filters.js
I SWEAR THIS IS TRUE: The list of available languages is generated by
stripes-components and changed in
https://github.com/folio-org/stripes-components/pull/1319 as part of
[UIIN-829](https://issues.folio.org/browse/UIIN-829). It turns out the [ISO-639 languages](https://www.loc.gov/standards/iso639-2/ascii_8bits.html), as of 2020-08-19, do not
include simple `Spanish` but only `Spanish; Castilian` which is sort of
non-sensical to me becuase Folio itself is offered in more than one
Spanish dialect/locale (Spanish and Latin American Spanish).
The old filters test used `English` and `Spanish` as test filters, but
since `Spanish` is no longer a legit value, the test failed. Maintenant,
nous parlons Français.
Refs [FOLIO-2727](https://issues.folio.org/browse/FOLIO-2727)
=> FOLIO-2727 change filter languages

CHANGELOG.md, src/components/InstancesList/InstancesList.js
I was asked to change the icon for the fast-add option in the dropdown menu.
Refs: https://issues.folio.org/browse/UIIN-907
=> UIIN-907 Fast add record. Access New fast add template from Inventory

CHANGELOG.md, src/constants.js, translations/ui-inventory/en.json
I removed this from the module's list of item statuses, and the label
from the translation file. I did a module-wide search, and no other page
seemed to be using the label.
Refs: https://issues.folio.org/browse/UIIN-1199
=> UIIN-1199: Remove "Received" from item status search & filter list

src/constants.js, test/bigtest/interactors/routes/items-route.js, test/bigtest/tests/filters/items/item-status-filter-test.js, translations/ui-inventory/en.json
There is more than one place where item-statuses are listed because not
all statuses are available under all circumstances. I missed adding it
to the item-status-filter in #1122.
Refs [UIIN-1006](https://issues.folio.org/browse/UIIN-1006)
=> UIIN-1006 list "Aged to lost" in filters

CHANGELOG.md, src/Instance/HoldingsList/Holding/Holding.js, src/Instance/ItemsList/ItemsList.js, src/Instance/ItemsList/ItemsListContainer.js
https://issues.folio.org/browse/UIIN-1076
Do not show an empty list if there are no items in the given `Holdings` record, and the draggable mode is deactivated.
=> Hide an empty list when there are no items in `Holdings` record

CHANGELOG.md, src/views/ItemView.js
To address this I just removed the if clause that
modifies the loan status string into a link if the
item status is Awaiting Pickup.  Very simple.
refs: https://issues.folio.org/browse/UIIN-1185
=> UIIN-1185: Awaiting pickup is linked on item record

CHANGELOG.md, src/ViewHoldingsRecord.js
I rearranged the items in the holdings screen action menu to make them
consistent with the ordering of items on the other action menus.
Refs: https://issues.folio.org/browse/UIIN-1093
=> UIIN-1093: Holdings record. Actions menu - make order of actions 

CHANGELOG.md, package.json, src/settings/FastAdd/FastAddSettings.js, src/settings/index.js, test/bigtest/interactors/settings/fast-add/fast-add.js, test/bigtest/tests/settings/fast-add/fast-add-test.js
https://issues.folio.org/browse/UIIN-1257
Add the permission for editing the Fast add settings page. Otherwise, this page should display read-only.
=> UIIN-1257: Add permission for editing the Fast add settings page

CHANGELOG.md, src/settings/StatisticalCodeSettings.js, translations/ui-inventory/en.json
UI-inventory was not passing a validator function to the 
controlledVocabulary component, which was causing submission errors.
Those errors were confusing because they have very generic text, leading
to confusion about what was going wrong.  I re-wrote the validation function
to check that the statistical code was unique and hooked it up to the
component. Data is now being validated properly before being passed to the back end. 
Note that there are still some bugs in this particular settings pane that have
to do with CRUD operations-I have filed separate bug reports for those issues.
refs: https://issues.folio.org/browse/UIIN-1259
=> UIIN-1259: Correct data validation in statistical code settings

CHANGELOG.md, src/settings/StatisticalCodeSettings.js
One of the reviewers on the PR request for UIIN-1259 suggested a slight refactor to some of the code I wrote, which I accepted and merged in.  I should have tested it first-it's produced a bug where now, the statistical code field is flagging all entered values as duplicates.  I've reverted the refactor here to my old code, which I know works.
Refs: https://issues.folio.org/browse/UIIN-1259
=> Reverting code refactor

CHANGELOG.md, src/settings/StatisticalCodeSettings.js
This was caused by an incorrect value for the 'shouldRefresh'
option in the data manifest. That value is supposed to be a function,
not a simple boolean. because of this, basically anytime the ControlledVocab
tried to do any write operation, it caused an error. Changing the value to a simple
function that returns a boolean cleared up the problem.
refs:
https://issues.folio.org/browse/UIIN-1269
https://issues.folio.org/browse/UIIN-1268
=> UIIN-1268 error message on deleting a statistical code

CHANGELOG.md, src/settings/StatisticalCodeSettings.js, translations/ui-inventory/en.json
As part of the fix for this issue, it was requested that the validation
code also check that the statistical code name be unique as well as the
code.
refs: https://issues.folio.org/browse/UIIN-1276
=> UIIN-1276 Confusing error when saving duplicate Statistical code

CHANGELOG.md, src/Instance/ItemsList/ItemBarcode.js, test/bigtest/network/scenarios/item-filters.js, test/bigtest/tests/instances-index-test.js
https://issues.folio.org/browse/UIIN-906
This uses `<Highlighter>` to identify the searched-for barcode when an instance is opened.
=> UIIN-906: Highlight search results when searching for item barcode

CHANGELOG.md, src/components/TitleField/TitleField.js
Mark connected preceding and succeeding titles as actually "connected":
https://issues.folio.org/browse/UIIN-1283
=> UIIN-1283: Mark connected preceding and succeeding titles as connected

CHANGELOG.md, src/filterConfig.js
STCOM-492 changed the default query filter action from `=` to `==`.
This is much more efficient at the DB level for most relationship
types, but does not function when only the related value, rather
than the related object, is available on the record, which is the case
here with languages, exposed on an instance record like
```
"languages" : [ "ger", "eng", "spa", "fre", "ita", "dut", "por" ],
```
Refs [UIIN-1287](https://issues.folio.org/browse/UIIN-1287), [STCOM-492](https://issues.folio.org/browse/STCOM-492)
=> UIIN-1287 correctly implement language filter

CHANGELOG.md, src/Instance/ItemsList/ItemBarcode.js
Show `No barcode` for items without barcode
https://issues.folio.org/browse/UIIN-1288
=> Fixes UIIN-128: Show "No barcode" for items without barcode

CHANGELOG.md, package.json
Apps and plugins must depend on the same versions of peer dependencies.
Refs [UIIN-1300](https://issues.folio.org/browse/UIIN-1300)
=> UIIN-1300 update plugins for stripes v5 compat

CHANGELOG.md, src/components/InstancesList/InstancesList.js
Based on the changes in https://issues.folio.org/browse/STSMACOM-350 and https://github.com/folio-org/stripes-smart-components/pull/944 the `onChangeIndex` is not required anymore because changing query index will be handled by `SearchAndSort` internally.
https://issues.folio.org/browse/UIIN-1299
=> UIIN-1299: Remove onChangeIndex prop passed to SearchAndSort.

CHANGELOG.md, src/Instance/InstanceDetails/InstanceRelationshipView/utils.js
Bound-with links included an extraneous trailing slash before appending
`location.search`, causing double slashes when other URLs were
assembled, causing navigation glitches.
Refs [UIIN-1316](https://issues.folio.org/browse/UIIN-1316)
=> UIIN-1316 remove extraneous trailing slash

CHANGELOG.md, src/routes/buildManifestObject.js, src/utils.js
https://issues.folio.org/browse/UIIN-1312
After refactoring done in https://github.com/folio-org/ui-inventory/pull/1177 we lost access to `identifierTypes` via props. Thankfully we can still access them via `resourceData` when building a query.
=> UIIN-1312: Fix search by identifierTypes

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/utils.js, test/bigtest/tests/instance-view-page-test.js
Omit `id` from preceding/succeeding titles when duplicating instance
https://issues.folio.org/browse/UIIN-1324
=> UIIN-1324: Omit id from preceding/succeeding titles when duplicating instance

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/constants.js, test/bigtest/tests/export-to-csv-test.js, translations/ui-inventory/en.json
Add info callout when saving a file with the instance UUIDs takes longer in the scope of the [UIIN-1329](https://issues.folio.org/browse/UIIN-1329).
=> UIIN-1329: Add info callout when saving file with the instance UUIDs takes longer

CHANGELOG.md, src/Holding/CreateHolding/CreateHolding.js, src/Instance/InstanceEdit/InstanceEdit.js, src/Item/CreateItem/CreateItem.js, src/ViewHoldingsRecord.js, src/components/InstancesList/InstancesList.js, src/edit/InstanceForm.js, src/edit/items/ItemForm.js, src/views/ItemView.js
https://issues.folio.org/browse/UIIN-1339
https://issues.folio.org/browse/UIIN-1340
While submitting a form asynchronously FinalForm expects to receive a promise during submission in order to correctly set the `submitting` flag to `true`. 
https://final-form.org/docs/final-form/types/FormState#submitting
This PR is trying to address it.
The `submitting` flag was correctly used in ui-inventory in order to disable submit buttons during submission but the problem was that the flag was never set to `true` causing a "double submission" problem.
=> UIIN-1339: Return promise when submitting instance, holdings record or item form

CHANGELOG.md, src/components/InstancesList/CheckboxColumn/CheckboxColumn.js, src/components/InstancesList/CheckboxColumn/index.js, src/components/InstancesList/InstancesList.js, test/bigtest/interactors/routes/instances-route.js, test/bigtest/tests/filters/instances/instance-filters-test.js, test/bigtest/tests/filters/instances/instances-list-test.js, translations/ui-inventory/en.json
Add select row checkboxes to inventory instance search result in the scope of the [UIIN-1349](https://issues.folio.org/browse/UIIN-1349).
=> UIIN-1349: Add select row checkboxes to inventory instance search result

CHANGELOG.md, src/edit/holdings/HoldingsForm.js, src/edit/holdings/holdingsStatementFields.js, src/edit/holdings/holdingsStatementForIndexesFields.js, src/edit/holdings/holdingsStatementForSupplementsFields.js, src/edit/holdings/note.js
Replace most holding-record `<TextField>` elements with `<TextArea>`s
to allow for long values that can be scrolled.
Refs [UIIN-1279](https://issues.folio.org/browse/UIIN-1279)
=> UIIN-1279 use TextAreas on holdings-record form

CHANGELOG.md, src/ViewHoldingsRecord.js
https://issues.folio.org/browse/UIIN-1310
An easy-peasy bug fix is to reformat the title and replace the comma with a period.
=> UIIN-1310: Update title in Holdings detailed view

CHANGELOG.md, package.json, src/routes/buildManifestObject.js, test/bigtest/network/config.js, test/bigtest/tests/export-to-csv-test.js
Update API endpoint for retrieving instances UUIDs in the scope of the [UIIN-1368](https://issues.folio.org/browse/UIIN-1368).
=> UIIN-1368: Update API endpoint for retrieving instances UUIDs

CHANGELOG.md, src/settings/HoldingsSourcesSettings.js, src/utils.js, test/bigtest/network/factories/holdings-source.js, test/bigtest/tests/settings/holdings-sources/holdings-sources-test.js
https://issues.folio.org/browse/UIIN-1314
In `Settings` -> `Holdings sources` entries with source value `folio` should not be editable.
=> UIIN-1314: Make holdings sources with value folio non-editable

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/components/InstancesList/instances.css, src/constants.js, test/bigtest/interactors/inventory.js, test/bigtest/tests/export-to-csv-test.js, test/bigtest/tests/filters/instances/instances-list-test.js, translations/ui-inventory/en.json
UIIN-1367: Add quick instances UUIDs export limit reached warning in the scope of the [UIIN-1367](https://issues.folio.org/browse/UIIN-1367).
Limit is not exceeded
Limit is
exceeded
=> UIIN-1367: Add quick instances UUIDs export limit reached warning

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/components/SelectedRecordsModal/SelectedRecordsModal.js, src/routes/InstancesRoute.test.js, src/utils.js
Add checkboxes on the show selected instances modal in the scope of the [UIIN-1391](https://issues.folio.org/browse/UIIN-1391).
Note, that `eslint` warnings and errors are not related to my PR so I am not fixing them. Usually fixing them as a part of feature PR is not appreciated. Usually, it should be done as part of dedicated PR so that is why I did not do it here.
=> UIIN-1391: Add checkboxes on the show selected instances modal

src/components/InstancesList/InstancesList.js
We need to pick up our game on lint-policing: when "ignorable" errors begin to proliferate, significant errors get ignored. I fixed some quoting-and-spacing problems.
There still remains an error that mystifies me:
```
/Users/mike/ui-inventory/src/routes/InstancesRoute.test.js
10:23  error  Unable to resolve path to module '@testing-library/user-event'  import/no-unresolved
```
Yet the package file specifies in the `devDependencies`:
```
"@testing-library/user-event": "^12.1.10",
```
If anyone can see what's going wrong here, I'd like to know!
=> Fix trivial ESLint errors

CHANGELOG.md, package.json, src/constants.js, src/views/ItemView.js, test/bigtest/tests/item-view-page-test.js, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-1336
Added new permission that allows users to change the item status to `Intellectual item`.
There was also a little refactoring when checking the visibility of the `Actions` menu.
=> UIIN-1336: Add permission for marking item intellectual

CHANGELOG.md, package.json, src/constants.js, test/bigtest/tests/item-view-page-test.js, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-1335
This PR is almost a copy of the previous #1277 and adds a new permission that allows users to change the item's status to `Restricted`.
=> UIIN-1335: Add permission for marking item restricted

package.json, src/components/InstancesList/InstancesList.js, src/components/InstancesList/InstancesList.test.js, src/storage.js, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-1363
Implement results list column chooser on the instances list view.
It looks like the sonar cloud coverage is still based on the reports generated by the BigTest. 
https://user-images.githubusercontent.com/63545/105518629-86279680-5ca6-11eb-8143-40e7e21459fe.mov
=> UIIN-1363: Implement results list column chooser

CHANGELOG.md, src/constants.js, src/routes/ItemRoute.js, src/views/ItemView.js, test/bigtest/interactors/item-view-page.js, test/bigtest/network/config.js, test/bigtest/tests/item-view-page-test.js
https://issues.folio.org/browse/UIIN-756
The ability to mark items with five new statuses has been added: `In process`, `In process (non-requestable)`, `Long missing`, `Unavailable`, and `Unknown`.
Also, the `constants.js` has been cleaned up a bit so that all statuses are in alphabetical order.
=> UIIN-756: Add ability to mark item with new statuses

package.json
Permission defined twice .. Remove one of them. Fortunately they had same definition. See FOLIO-2989
=> Duplicate ui-inventory.instance.view-staff-suppressed-records

CHANGELOG.md, src/utils.js, src/views/ItemView.js, test/bigtest/tests/item-view-page-test.js
https://issues.folio.org/browse/UIIN-1305
This allows switching between new item statuses according to this [spreadsheet](https://docs.google.com/spreadsheets/d/1el9_XTlpZKNzYqWSoN_XcCQxdgZDxwB_blbSWrcsAL8/edit#gid=0).
=> UIIN-1305: Add ability to switch between new item statuses

CHANGELOG.md, package.json, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-1399
Rename `Settings (Inventory): Display list of settings pages` permission to `Settings (Inventory): View list of settings pages`.
=> UIIN-1399: Rename permission to `Settings (Inventory): View list of settings pages`

CHANGELOG.md, package.json, src/constants.js, src/views/ItemView.js, test/bigtest/tests/item-view-page-test.js, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-1308
https://issues.folio.org/browse/UIIN-894
https://issues.folio.org/browse/UIIN-1307
https://issues.folio.org/browse/UIIN-1326
Added 4 permissions at once for the ability to mark items with statuses ` In process (non-requestable)`, `Long missing`, `Unavailable`, `Unknown`.
=> UIIN-894: Add permission to mark items with four new statuses

src/ViewInstance.js
Fixes an ESLint error, making the whole repository once more lint-clean aside from the ravening horde of `react-hooks/exhaustive-deps` errors.
=> Remove unused prop

CHANGELOG.md, src/filterConfig.js, test/bigtest/network/config.js, test/bigtest/network/factories/alternative-title-type.js, test/bigtest/tests/filters/instances/search-field-filter-test.js
https://issues.folio.org/browse/UIIN-1434
BE part: https://github.com/folio-org/mod-inventory-storage/pull/573
Adding `allTitles` index allows to search not only by `title` field but by all title-related fields: `Alternative title`, `Index title`, and `Series statement`.
=> UIIN-1434: Add ability to search by allTitles index

CHANGELOG.md, src/components/ImportRecordModal/ImportRecordModal.js, src/settings/SingleRecordImport.js, src/settings/TargetProfileDetail.js, src/settings/TargetProfileForm.js, src/settings/TargetProfiles.js, src/settings/index.js, translations/ui-inventory/en.json
The old version simply used `<ControlledVocab>`, which is a real squeeze when you have nine editable fields. The new uses `<EntryManager>` and gives you 
I've retained the old version for now, as well as the new page, since we _know_ it does what we need, albeit in a really horrible way, and it's not impossible that there are surprises lurking in the brand new code. I'll rip out the old version once we have some experience with the new.
Fixes UIUN-1437, or at least constitutes _a_ fix. No doubt we will want to come back to this with some UX insight, and change the arrangement of the fields. But for now, we need something functional.
=> Improved settings page for single-record-import profiles

CHANGELOG.md, karma.conf.js, src/Instance/HoldingsList/Holding/Holding.js, src/Instance/HoldingsList/Holding/HoldingAccordion.js, src/Instance/HoldingsList/Holding/HoldingAccordion.test.js, src/Instance/HoldingsList/Holding/HoldingButtonsGroup.js, src/Instance/ItemsList/ItemsListContainer.js, test/bigtest/interactors/instance-view-page.js, test/bigtest/interactors/item-view-page.js, test/bigtest/tests/instance-view-page-test.js, test/fixtures/items.js
Add item counter to each holdings record accordion. 
https://issues.folio.org/browse/UIIN-803
This took a bit longer because I had to move things around in order to get access to item records on the accordion level.
We could potentially improve this a bit more by fetching items for all holding records in one request.
=> UIIN-803: Add item counter to each holding record accordion

CHANGELOG.md, src/filterConfig.js
Fix instance format filter by changing the default `==` operator to single `=`.
https://issues.folio.org/browse/UIIN-1423
=> UIIN-1423: Fix instance format filter

CHANGELOG.md, translations/ui-inventory/en.json
Change label for duplicate MARC record button from `Duplicate MARC bib record` to `Derive new MARC bib record`
[UIIN-1436](https://issues.folio.org/browse/UIIN-1436)
=> UIIN-1436: Instance Record |  Change Actions menu option Duplicate MARC bibliographic record to Derive new MARC bibliographic record

CHANGELOG.md, src/Instance/HoldingsList/Holding/HoldingAccordion.js, src/Instance/ItemsList/ItemsList.js, src/components/InstancesList/InstancesList.js, src/components/InstancesList/instances.css, test/bigtest/interactors/instance-view-page.js, test/bigtest/interactors/inventory.js, test/bigtest/network/config.js, test/bigtest/network/factories/instance.js, test/bigtest/tests/filters/instances/instance-filters-test.js, test/bigtest/tests/instance-view-page-test.js
https://issues.folio.org/browse/UIIN-1380
Add ability to clearly see when instance/holdings/item marked as Suppressed from discovery.
=> UIIN-1380: Add warn icon for Suppressed from discovery instance/holdings/item

CHANGELOG.md, src/filterConfig.js
Fix nature of content filter by changing the default `==` operator to single `=`.
https://issues.folio.org/browse/UIIN-1441
=> UIIN-1441: Fix nature of content filter

CHANGELOG.md, src/components/InstancesList/InstancesList.js, test/bigtest/network/config.js, test/bigtest/tests/filters/instances/instance-filters-test.js
https://issues.folio.org/browse/UIIN-1381
Add ability to clearly see when instance marked as Staff suppressed.
=> UIIN-1381: Add a warn icon for Staff suppressed instance

CHANGELOG.md, src/Instance/InstanceDetails/InstanceAdministrativeView/InstanceAdministrativeView.js, src/Instance/InstanceDetails/InstanceAdministrativeView/InstanceAdministrativeView.test.js, src/Instance/InstanceDetails/InstanceDetails.js, src/components/WarningMessage/WarningMessage.css, src/components/WarningMessage/WarningMessage.js, src/components/WarningMessage/WarningMessage.test.js, src/components/WarningMessage/index.js, src/components/index.js, translations/ui-inventory/en.json
This PR adds better visual indicators for suppressed instances. It takes care of two stories since they were very similar:
https://issues.folio.org/browse/UIIN-1377
https://issues.folio.org/browse/UIIN-1386
=> UIIN-1377: Add visual display when instance is suppressed from discovery

CHANGELOG.md, package.json
Update the okapi dependency on `data-export` to `4.0`. No information is
available about the breaking changes but in fact the changes were made
some time ago and the interface version only bumped recently, i.e. we've
been using the updated interface for some time now, but it just hadn't
been correctly labeled as updated.
Refs [UIIN-1448](https://issues.folio.org/browse/UIIN-1448)
=> UIIN-1448 rely on data-export interface 4.0

package.json, src/ViewInstance.js, src/components/InstancesList/InstancesList.js
This is fetched in ImportRecordModal.js. That component was already,
rightly, not being included when the the `copycat-imports` interface
is unavailable. We now also omit it if the user doesn't have the
necessary permission, `copycat.profiles.collection.get`.
This permission is added as a sub-permission to
`ui-inventory.single-record-import`, since it's not possible to
perform an import without fetching a copycat profile.
Fixes UIIN-1447.
=> Avoid error message from trying to fetch /copycat/profiles

CHANGELOG.md, package.json
Update deps for compatibility with `@folio/stripes` `v6`, including:
* `@folio/react-intl-safe-html`
* `@folio/plugin-find-instance`
* `@folio/quick-marc`
=> use deps compatible with @folio/stripes v6

CHANGELOG.md, src/providers/DataProvider.js
It is now possible to configure the maximum number of location to
fetch in the Stripes config file, typically `stripes.config.js`, using
the `maxLocationsToLoad` entry in the `config` area.
Fixes UIIN-1480.
=> Configure maximum number of location to fetch in Stripes config

CHANGELOG.md, package.json
The only breaking change in `circulation` `10.0` was the removal of the
`override-check-out-by-barcode` which is not used here, hence continuing
to support `9.0`.
Refs [UIIN-1488](https://issues.folio.org/browse/UIIN-1488)
=> UIIN-1488 also support circulation 10.0

CHANGELOG.md, src/utils.js
The dates on view and edit screens were out of sync because the missing `timeZone`.
https://issues.folio.org/browse/UIIN-1481
=> UIIN-1481: Fix date display on item view

CHANGELOG.md, package.json
`stripes-cli` `2.1.1` locks `stripes-webpack` to `~1.1.0`, avoiding the
`1.2.0` release that adds some helpful things to do with CSV files and
the new react JSX transform but that does not play nice with BigTest for
some developers, making tests impossible to run, and, therefore,
releases impossible to release. This allows tests to be run locally in 
order to prove they run successfully, even when the fail consistently
in CI. 
In CI, do not run `stripes test karma...` since it is known to fail. Instead,
run jest tests only. As above, the BigTest suite may still be run locally in
order to demonstrate that tests pass by copying test output to a PR.
Refs [UIIN-1483](https://issues.folio.org/browse/UIIN-1483), [STCLI-176](https://issues.folio.org/browse/STCLI-176)
=> UIIN-1483 lock stripes-cli to ~2.1.1

CHANGELOG.md, src/views/ItemView.js
The original work (#1323) added the field to the display but
accidentally neglected to configure the `itemData` itself.
Refs [UIIN-816](https://issues.folio.org/browse/UIIN-816), [MODINVSTOR-521](https://issues.folio.org/browse/MODINVSTOR-521)
=> UIIN-816 include shelving order in itemData

src/Instance/InstanceDetails/InstanceDetails.js, src/Instance/InstanceDetails/InstanceRelationshipView/InstanceRelationshipView.js, src/Instance/InstanceDetails/InstanceRelationshipView/InstanceRelationshipView.test.js, src/Instance/InstanceDetails/SubInstanceGroup/SubInstanceGroup.js, src/Instance/InstanceDetails/SubInstanceGroup/index.js, src/Instance/InstanceDetails/SubInstanceList/SubInstanceList.css, src/Instance/InstanceDetails/SubInstanceList/SubInstanceList.js, src/Instance/InstanceDetails/index.js, src/edit/InstanceForm.js, src/hooks/useLoadSubInstances.js, src/utils.js, test/fixtures/childInstances.js, test/fixtures/index.js, test/fixtures/instances.js, translations/ui-inventory/en.json
This PR is a continuation of work done in https://github.com/folio-org/ui-inventory/pull/1354 based on some additional feedback from PO.
The work done here groups child/parent sub instances by relationship type.
https://issues.folio.org/browse/UIIN-1044
https://issues.folio.org/browse/UIIN-1045
=> UIIN-1044: Group sub instances by relationship type

CHANGELOG.md, src/ViewInstance.js
STRIPES-741
This commit adds a `<Pluggable>` to the main Instance action menu to
enable plugins that provide copyright checking functionality to add
themselves to the menu, via the `copyright-permissions-checker` plugin type.
This was added to enable the CLA Permissions Check plugin
(https://github.com/PTFS-Europe/ui-plugin-cla-permissions-check) to add
itself.
Additional state was added to the component to maintain the open status
of a modal that the plugin may present, this state is passed to the
plugin, along with a function to set it.
Since such plugins will require an identifier for the instance to enable
them to check copyright status, a new function getIdentifiers was added
which, when passed an instance's data, will extract a suitable
identifier to pass to the plugin …
=> STRIPES-741: Add <Pluggable> for checking copyright

CHANGELOG.md, src/Instance/InstanceEdit/InstanceEdit.js, src/ViewInstance.js, src/components/CalloutRenderer/CalloutRenderer.js, src/components/CalloutRenderer/index.js, src/components/index.js, src/constants.js, translations/ui-inventory/en.json
https://issues.folio.org/browse/UIIN-1468
The POST request currently does not return the newly created instance so this is kind of a workaround in order to be able to access that record. This is required because the HRID has to be displayed on the callout.
=> UIIN-1468: Add callout after instance record is saved

CHANGELOG.md, package.json
There is a breaking change in mod-circulation (https://github.com/folio-org/mod-circulation/pull/854), circulation interface version will be updated to 11.0.  Other modules should update their dependencies to support this change.
**Do not merge. We have several associated pull request and we need merge them at the same time.**
**API changes**
circulation/override-renewal-by-barcode - will be removed
circulation/renew-by-barcode - request and response will be changed
Current changes will be effect ui-users module
https://issues.folio.org/browse/UIIN-1511
=> UIIN-1511: Update circulation interface dependency to support v11

package.json, test/jest/babel.config.js
Update babel version used by jest/rtl to avoid errors related to: `ReferenceError: React is not defined`
=> Update babel versions

CHANGELOG.md, src/components/FilterNavigation/FilterNavigation.js, src/components/InstancesList/InstancesList.js
Focus on on search box when changing inventory segments. Fixes UIIN-1358.
https://issues.folio.org/browse/UIIN-1358
=> UIIN-1358: Focus on on search box when changing inventory segments

CHANGELOG.md, src/ViewInstance.js
Fix instance MARC record not loading when adding OCLC number. If instance's source is changed from `FOLIO` to `MARC` the marc record was not loaded.
[UIIN-1532](https://issues.folio.org/browse/UIIN-1532)
=> UIIN-1532: quickMARC Latency: Unable to view source, edit or derive MARC bib without a page refresh or new search

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/utils.js
As @nielserik outlined in https://issues.folio.org/browse/UIIN-1546?focusedCommentId=106757&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-106757
The previous implementation was sending a full instance records under `parentInstances` and `childInstances` which was causing issues with incorrect `id` being used. 
This PR parses the `parentInstances` and `childInstances` in order to only send what the server expects:
````js
{
"id"    (id of the Instance we are adding parents/children to)
"title" 
... etc
"parentInstances" : [
{
"id":  (if adding new relation: nothing here or new unique UUID for this relation, if updating relation: use existing id)
"superInstanceId":  (id of the related parent)
"instanceRelationshipTypeId":   (type of relationship)
}
], …
```
=> UIIN-1546: Parse parentInstances and childInstances before instance record is saved

CHANGELOG.md, src/Instance/InstanceDetails/InstanceDetails.js, src/ViewInstance.js
https://issues.folio.org/browse/UIIN-1556
This is a regression I introduced in https://github.com/folio-org/ui-inventory/pull/1416 when I tried to address https://issues.folio.org/browse/UIIN-1534.
This PR should address it correctly now for both UIIN-1556 and UIIN-1554.
The `selectedInstance` resource was not cleared out between remounts and it would hold the previous version of `instance` on the first render before a new version was fetched. This was causing some issues with the `initialStatus` values passed to `AccordionSet`.
=> UIIN-1556: Fix collapse and expand buttons on instance view

src/Instance/HoldingsList/Holding/Holding.js, src/Instance/HoldingsList/Holding/HoldingAccordion.js, src/Instance/HoldingsList/Holding/HoldingAccordion.test.js, src/Instance/HoldingsList/Holding/HoldingButtonsGroup.js, src/Instance/ItemsList/ItemsListContainer.js, src/ViewInstance.js, src/constants.js, src/hooks/useHoldingItemsQuery.js, translations/ui-inventory/en.json, translations/ui-inventory/en_GB.json, translations/ui-inventory/en_SE.json, translations/ui-inventory/en_US.json
https://issues.folio.org/browse/UIIN-1560
This PR does couple of things in order to improve performance on the instance view.
1. Remove requests counter from the instance menu. Getting a total number of requests for all items across all holding records is very expensive. This is already happening on a separate route created for that purpose.
2. Fetch items only when a holding accordion is opened for the first time.
3. Add a separate request for item counters associated with each holding accordion.
4. Add loading indicators in various places.
These changes improved the loading time significantly but there is potentially more which can be done (for example add pagination to item list under each holding accordion).
Performance before this change:
Performance after this change:
=> UIIN-1560: Improve performance on instance view

CHANGELOG.md, src/hooks/useLoadSubInstances.js
https://issues.folio.org/browse/UIIN-1569
`babel-plugin-lodash` currently complains about lodash using chain sequences. 
This PR refactors it to use `flow`.
````
inventory/src/hooks/useLoadSubInstances.js: Lodash chain sequences are not supported by babel-plugin-lodash.
Consider substituting chain sequences with composition patterns.
See https://medium.com/making-internets/why-using-chain-is-a-mistake-9bc1f80d51ba
22 |   const results = useInstancesQuery(instanceIds.map(inst => inst[subId]));
23 |   const allLoaded = results.reduce((acc, { isSuccess }) => (isSuccess && acc), true);
> 24 |   const instances = chain(results)
````
More info:
https://medium.com/bootstart/why-using-chain-is-a-mistake-9bc1f80d51ba
We need this in place in order to finalize work on …
=> UIIN-1569 Make sure building inventory module works with babel-plugin-lodash

CHANGELOG.md, src/ConnectedInstance/StripesConnectedInstance.js, src/Instance/InstanceDetails/InstanceRelationshipView/InstanceRelationshipView.js, src/ViewInstance.js, src/ViewInstanceWrapper.js, src/components/InstancesList/InstancesList.js
https://issues.folio.org/browse/UIIN-1562
This PR introduces `ViewInstanceWrapper` which preloads child and parent instances before `ViewInstance` is mounted. This is required so the correct data is present during instance duplication.
=> UIIN-1562: Fix instance duplication when child or parent records are present

CHANGELOG.md, src/routes/buildManifestObject.js
When we implemented ElasticSearch, all requests, instead of only `GET`
requests, were redirected to the mod-search endpoints. This restores the
mod-inventory endpoints for `POST`, `PUT`, and `DELETE` requests,
restoring the ability to create, edit, and remove records.
Refs [UIIN-1634](https://issues.folio.org/browse/UIIN-1634)
=> UIIN-1634 only search requests should use mod-search

CHANGELOG.md, src/ViewInstanceWrapper.js
The issue here was that the existing `selectedInstance` var was mutated instead of recreated when sub instances were loaded. With in place mutations the child component was never re-rendered.
I think this was working fine before in react 16 so I wonder if this is some side effect of react 17.
https://issues.folio.org/browse/UIIN-1814
https://issues.folio.org/browse/UIIN-1816
=> UIIN-1814: Fix parent and child relationship rendering

CHANGELOG.md, src/filterConfig.js
https://issues.folio.org/browse/UIIN-1846
Based on the feedback from @magdazacharska it looks like `==` has to be replaced by `=` to make sure ISBN and ISSN work correctly.
=> UIIN-1846: Change search operators for ISBN and ISSN to '='

CHANGELOG.md, src/filterConfig.js, src/routes/InstancesRoute.test.js
Change search operator for "Identifier (all)" index to '='. Fixes UIIN-1855.
https://issues.folio.org/browse/UIIN-1855
=> UIIN-1855: Change search operator for 'Identifier (all)' index to '='.

CHANGELOG.md, src/components/InstancesList/InstancesList.js, translations/ui-inventory/en.json
Fix successful toast appears after clicking on In transit items report (CSV)
- Changed toast from info to success 
- Added missing translation
https://issues.folio.org/browse/UIIN-1838
=> UIIN-1838: Fix successful toast appears after clicking on In transit items report (CSV)

src/edit/holdings/holdingsStatementFields.js, src/edit/holdings/holdingsStatementForIndexesFields.js, src/edit/holdings/holdingsStatementForSupplementsFields.js
Add `canDelete` props to components for HoldingsStatements fields. Previously they didn't pass on these properties to RepeatableField
[UIIN-1853](https://issues.folio.org/browse/UIIN-1853)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that …
=> UIIN-1853: Add canDelete property to HoldingsStatements fields

CHANGELOG.md, src/edit/items/ItemForm.js
Use correct metadata on item form. The previous version was using `holdingsRecord` which was wrong since we deal with the item record.
https://issues.folio.org/browse/UIIN-1656
=> UIIN-1656: Use correct metadata on item form

CHANGELOG.md, src/ViewHoldingsRecord.js
Fix issue when updating a Holdings record. After successful update user should see an updated record, but instead they see a Instance record first and Holdings record later.
This issue is probably caused by delays in `stripes-connect` between `UPDATE_SUCCESS` and `REFRESH` actions. Initially I tried adding a `isUpdating` property to `holdingsRecords` resource, but this delay made it difficult to write correct conditions to check when a record has been updated and refreshed.
So eventually I decided to handle updating and refreshing Holdings record manually with a combination of `GET` and `reset` methods.
Added a `isLoadingUpdatedHoldingsRecord` which tells us if a record was updated and refreshed. In `isAwaitingResource` we're using this flag to show a loading message.
Also, calling `GET` …
=> UIIN-1854: After saving and updating a holdings record, the user is returned to the holdings instead of instance

CHANGELOG.md, src/Item/ViewItem/ItemAcquisition/ItemAcquisition.js, src/routes/ItemRoute.js
https://issues.folio.org/browse/UIIN-1558
The <ItemRoute> manifest uses a function to determine the right query to use when retrieving service point records, which are then used to populate details in the 'circulation history' section of <ItemView>. But if the service point to use wasn't yet available (i.e., the records were still loading), then the function returned `null`, causing the service point lookup to fail entirely. Returning an empty object instead of `null` fixes this.
=> UIIN-1558: Fix bug preventing service point and source from appearing in item view circ history

CHANGELOG.md, src/components/ViewSource/ViewSource.css, src/components/ViewSource/ViewSource.js
Sometimes the display of the indicators in the MARC View source UI are misaligned, dropping down 1 line.
- div.viewSource has been added into return of ViewSource component
- white-space: pre; css property has ben added to td (for all except last in a row) for proper alignment
=> UIIN-1859 SRS display. MARC indicators may be misaligned

CHANGELOG.md, src/ViewInstance.js, src/components/ViewInstance/MenuSection/NewInstanceRequestButton.js, src/components/ViewInstance/MenuSection/NewInstanceRequestButton.test.js, test/jest/__mock__/stripesCore.mock.js
Add posibility to create title-level request from `Instance` record
Done the same way as with `Item`: generates link to `request` module with `create` layer and pass `instanceId` in it.
New button appears only if TLR is switched on in settings, and we have permission to create requests.
https://issues.folio.org/browse/UIIN-1620
=> UIIN-1620: Create title level request from Instance record

CHANGELOG.md, src/ViewInstance.js, src/components/ViewInstance/MenuSection/RequestsReorderButton.js, src/components/ViewInstance/MenuSection/RequestsReorderButton.test.js, src/constants.js, src/routes/ItemRoute.js, src/views/ItemView.js, translations/ui-inventory/en.json
Add action menu link `View & reorder queue` for instance
To show this button we muse enable TLR and have at least one request on this `instance`. To minimize the load we fetch only one request and use field `totalRecords`. Also in `request` module our route looks like `/requests/view/${requestId}/${instanceId}/reorder` and we have a lot of logic connected with `requestId` which we pass here.
I'am shure that pass of `requestId` is not the best way, but to make it another way we forced to do a lot of code refactoring.
https://issues.folio.org/browse/UIIN-1881
=> UIIN-1881: Inventory action menu link `View & reorder queue`

CHANGELOG.md, src/filterConfig.js, translations/ui-inventory/en.json
Add the 'Browse by subjects" option for for "Browse" functionality feature.
Entry added to filter config, applicable translation key added.
I set the value as `browseSubjects` to disambiguate from the already present `subjects` value.
=> UIIN-1880 - add Browse by subject option to search field select

CHANGELOG.md, src/common/hooks/useFacets.js, src/components/HoldingsRecordFilters/HoldingsRecordFilters.js, src/components/HoldingsRecordFilters/HoldingsRecordFilters.test.js, src/components/InstanceFilters/InstanceFilters.js, src/components/ItemFilters/ItemFilters.js, src/components/ItemFilters/ItemsFilters.test.js, src/constants.js, src/filterConfig.js, src/utils.js, src/withFacets.js
Add ability to filter items and holding records by create and update dates. 
https://issues.folio.org/browse/UIIN-785
https://issues.folio.org/browse/UIIN-786
https://issues.folio.org/browse/UIIN-789
https://issues.folio.org/browse/UIIN-791
This is mostly based on the work @Baroquem did in: https://github.com/folio-org/ui-inventory/pull/1494
=> UIIN-791: Add ability to filter holding and items records by date

CHANGELOG.md, package.json
Support okapi interfaces `circulation` `13.0`
* Title level requests changes affect ui-requests (UIREQ) without breaking change for this module.
* Was changed API associated with request queue.
https://issues.folio.org/browse/UIIN-1871
=> UIIN-1871: Also support circulation 13.0

src/components/InstancesList/InstancesList.js
Upon selecting a "browse" option, the visible columns were not changing to the correct columns.
have the `getSelectedBrowseOption` function return a string or undefined.
=> Browse column fix

src/components/InstancesList/InstancesList.js, src/components/InstancesList/InstancesList.test.js
Currently, The query index select will not stay as it should after a browse row is clicked.
This PR resolves that by setting a key prop on search and sort that will change, causing the component to reset so that it will accept the supplied `selectedIndex` prop.
=> Transition on browse row click

src/components/HoldingsRecordFilters/HoldingsRecordFilters.js, src/components/InstanceFilters/InstanceFilters.js, src/components/ItemFilters/ItemFilters.js, src/facetUtils.js, src/providers/DataProvider.js
This PR adds statistical code types to statistical code filters based on feedback from @CharlotteWhitt.
I noticed that the data provider which holds all dictionaries was processing data multiple times at each re-render. I cleaned it up a bit to improve it.
https://issues.folio.org/browse/UIIN-792
https://issues.folio.org/browse/UIIN-793
https://issues.folio.org/browse/UIIN-794
=> UIIN-792 Adds statistical code types to statistical code filters

CHANGELOG.md, src/Instance/HoldingsList/Holding/HoldingAccordion.js, src/Instance/ItemsList/ItemsList.js, src/Instance/ItemsList/ItemsListContainer.js, src/hooks/useHoldingItemsQuery.js
https://issues.folio.org/browse/UIIN-1831
This PR fetches all items attached to a given holdings record and adds in memory pagination to MCL used for these item records.
=> UIIN-1831: Add pagination to holding items

CHANGELOG.md, src/Instance/InstanceEdit/InstanceEdit.js, src/components/ItemFilters/ItemFilters.js, src/hooks/useInstancesQuery.js, src/hooks/useInstancesQuery.test.js, src/hooks/useLoadSubInstances.js
https://issues.folio.org/browse/UIIN-1902
Previous implementation created a separate fetch request for every child and parent attached to the given instance object.
This was causing issues under chrome on window.
This PR changes the approach and creates a single request for all sub instances by using a query in a for of `(id==X OR id==Y ...)`
=> UIIN-1902: Fetch parent and child sub instances in one query

src/utils.js
The optimistic locking error format has changed from json to text:
https://issues.folio.org/browse/UIIN-1958
=> UIIN-1958: Handle message errors as plain text instead of json for optimistic locking 

src/utils.js
https://issues.folio.org/browse/UIIN-1958
Use content type instead of status to distinguish between type of error responses.
=> UIIN-1958: Use content type to distinguish between text and json

CHANGELOG.md, src/components/HoldingsRecordFilters/HoldingsRecordFilters.js, src/components/InstanceFilters/InstanceFilters.js, src/components/ItemFilters/ItemFilters.js
The previous implementation cross-checked the values returned from the tags facet with the global tags list. This is no longer required since the values returns from the tag facet include tag names which are required by mod-search. 
This PR removes that cross-check and just serves the values returned by the tags facet.
https://issues.folio.org/browse/UIIN-1974
=> UIIN-1974: Do not cross-check tag facets with tag list

CHANGELOG.md, src/providers/DataProvider.js
The resource data is being loaded every time the ui-inventory is opened. After leaving it and re-entering again the resources are re-fetched again but the previous data is still around (until new data arrives). This caused issues with stale data being served. 
This PR adds a `resourceShouldRefresh: true` which resets the resource data when the ui-inventory is unmounted so the fresh data is always being served.
https://issues.folio.org/browse/UIIN-1966
=> UIIN-1966: Reset reference data resources on unmount.

CHANGELOG.md, package.json
Set module.inventory.enabled includes search.facets.collection.get
rather than search.instances.facets.collection.get.
This is part of interface search 0.7. That interface was not bumped
so it will be random whether ui-inventory will actually use the
right permission... Only can only rely on "pinned" interfaces in
platform-complete.
=> Specify search.facets.collection.get UIIN-1941

CHANGELOG.md, src/components/RepeatableField/FieldRow.js, src/edit/alternativeTitles.js
https://issues.folio.org/browse/UIIN-1962
Improve `<RepeatableField>` layout.
Before:
After:
=> UIIN-1962: Improve RepeatableField layout

CHANGELOG.md, src/utils.js
https://issues.folio.org/browse/UIIN-1931
The previous implementation would always override identifiers array for the preceding/succeeding titles and only ISSN and ISBN would be kept around and updated.
This PR is trying to address an issue described in details by @wafschneider under UIIN-1931.
The new approach will keep all identifiers unchanged and it will only update ISSN and ISBN (if they are present and changed).
=> UIIN-1931: Do not change identifiers array for the preceding/succeeding titles

CHANGELOG.md, src/routes/QuickMarcRoute.js
Added a new prop to quickMARC to tell where optimistic locking banner should link to
https://issues.folio.org/browse/UIIN-1987
https://github.com/folio-org/ui-quick-marc/pull/292
=> UIIN-1987 Optimistic locking: display error message to inform user about OL

CHANGELOG.md, src/ViewHoldingsRecord.js, src/ViewInstance.js
Fix Edit a MARC holdings record generates a 500 error.
This bug occurred after editing MARC holdings record that was just created via quickmarc.
The problem was caused due to appending instance's `relatedRecordVersion` when redirecting to create holdings quickmarc page. Then when editing created MARC holdings record URL contained `relatedRecordVersion` of instance and then the `relatedRecordVersion` of the holdings record itself was appended.
[UIIN-1997](https://issues.folio.org/browse/UIIN-1997)
=> UIIN-1997: Edit a MARC holdings record - generates a 500 error

CHANGELOG.md, src/components/HoldingsRecordFilters/HoldingsRecordFilters.js, src/components/InstanceFilters/InstanceFilters.js, src/components/ItemFilters/ItemFilters.js
Several accordions' separators were incorrect, probably as a result of
copy-paste accordions as new filters were added.
Refs [UIIN-1933](https://issues.folio.org/browse/UIIN-1933)
=> UIIN-1933 correctly place/omit accordion separators

CHANGELOG.md, package.json, src/common/hooks/useFacets.js, src/components/CheckboxFacet/CheckboxFacetList.js, src/components/InstancesList/InstancesList.js, src/stores/facetsStore.js, src/stores/facetsStore.test.js
The state related to search values which belongs to each facet was previously
stored locally.
There was no easy way to reset it via `Reset all` because the `Reset all`
button and its action belongs to a completely different part of the DOM tree. 
This PR introduces [zustand](https://github.com/pmndrs/zustand) in order to
lift the local state up into a global store. The same could be accomplished via
react context or via local resource from stripes-connect but I find this
approach much simpler and cleaner.
https://issues.folio.org/browse/UIIN-1977
=> UIIN-1977: Reset search fields for each facet when Reset all button is clicked

CHANGELOG.md, src/hooks/useHoldingItemsQuery.js, src/hooks/useHoldingItemsQuery.test.js
Instance records with N holdings-records will have to issue N queries to
count their items and this can take a looooong time, longer than the
default timeout as configured in stripes-core. Rather than putting a
longer cap on the timeout, I think the best option is to just act like
fetch and wait indefinitely until the requests return.
https://github.com/folio-org/stripes-core/blob/6afa0d761aac4f4d00073a781072ae3ec0c8f6dd/doc/okapiKy.md#timeouts
describes this precisely.
Refs [UIIN-2006](https://issues.folio.org/browse/UIIN-2006)
=> UIIN-2006 avoid timeouts when retrieving item-counts

CHANGELOG.md, src/ViewInstance.js
Tenants may have more than 1000 locations; [5000 is the standard for
location-related values in stripes-smart-components](https://github.com/folio-org/stripes-smart-components/blob/cd38c4bbbef53e49e93f62f9bda3d134a9909fd1/lib/LocationLookup/LocationModal.js#L120) so we will use that
value here, too.
Refs [UIIN-2016](https://issues.folio.org/browse/UIIN-2016)
=> UIIN-2016 retrieve up to 5000 locations

CHANGELOG.md, test/jest/helpers/Harness.js
Wrap the component in `<CalloutContext.Provider>` with a dummy
`sendCallout` prop so that tests that render components that leverage
context don't blow up with NPEs. Locally, we'd see warnings in the test
output like
```
[UnhandledPromiseRejection: This error originated either by throwing
inside of an async function without a catch block, or by rejecting a
promise which was not handled with .catch(). The promise rejected
with the reason “TypeError: Cannot read properties of undefined
(reading ‘sendCallout’)“.] {
code: ‘ERR_UNHANDLED_REJECTION’
}
```
but tests would pass; in CI, however, such errors would cause the test
suite to abort.
This was discovered while working on UIIN-2049 to bump the CI Node
version to v16.
=> provide CalloutContext.Provider in the test harness

CHANGELOG.md, src/Instance/InstanceMovement/InstanceMovement.js, src/Instance/InstanceMovement/InstanceMovementDetails/InstanceMovementDetails.js, src/Instance/InstanceMovement/InstanceMovementDetails/InstanceMovementDetailsContainer.js
Add `id` to Instance movement sections to make it's easier to query them in e2e tests.
[UIIN-2052](https://issues.folio.org/browse/UIIN-2052)
=> UIIN-2052: Add id attribute to Instance movement sections to use in e2e tests

CHANGELOG.md, src/ViewHoldingsRecord.js, src/ViewHoldingsRecord.test.js
Fix options "View Source" and "Edit in quickMARC" are not available in holdings record view.
This issue was mostly reproduced in e2e tests, when the required resources didn't update in time.
The not loaded `instances1` resource resulted in `undefined` source which prevented from getting `marcRecord` data in `componentDidMount`.
The not loaded `holdingsRecords` resource resulted in having `isPending` always false and thus prevented from getting `marcRecord` data in `componentDidUpdate`.
And empty `marcRecord` led to disabled "View Source" and "Edit in quickMARC" options.
The fix was to wait for promises for `instances1` and `holdingsRecords` resources to resolve in `componentDidMount` before continuing.
With this fix, affected tests are passing successfully.
**C345404** in …
=> UIIN-2044: Option View Source is not available in holdings record view

src/components/InstancesList/InstancesList.js
Prevent searching Instance items when clicking on empty anchor item
[UIIN-2024](https://issues.folio.org/browse/UIIN-2024)
=> UIIN-2024 Prevent searching when clicking empty anchor item

src/Instance/InstanceMovement/InstanceMovementContainer.js, src/ViewHoldingsRecord.js
Fix in view Holding record displayed old Instance after moving Holding record to a new Instance.
Previously the instance data was taken from the first record in `this.props.resources.instances1.records`, but after moving Holding record between instances `this.props.resources.instances1.records` contains more than one record, the first of which being not the needed one.
The solution was to set a variable in the state to the value of the resolved `instances1` promise in `componentDidMount` and use this data to display Holdings Instance.
Fix for [this PR](https://github.com/folio-org/ui-inventory/pull/1695)
Also, fixed an issue when firstly search for a FROM Instance and the list has **one result**, then perform a move of a Holding record and go to a TO Instance - the TO Instance view is …
=> UIIN-2044: Fix in view Holding displayed old Instance after moving Holding to a new Instance

CHANGELOG.md, src/ViewHoldingsRecord.js, src/ViewHoldingsRecord.test.js
Fix when click view Holdings the Something went wrong error page appears.
The issue was caused by changes in [this PR](https://github.com/folio-org/ui-inventory/pull/1699)
The problem was that the component started to render before promises in `componentDidMount` are resolved, thus resulting in an empty `instance`.
The fix is to wait until `instance` is defined and only then render the component.
[UIIN-2063](https://issues.folio.org/browse/UIIN-2063)
=> UIIN-2063: When click view Holdings the Something went wrong error page appears

src/index.js, src/routes/buildManifestObject.js
This reverts commit da5f59eae201ff15a7af899cab4681489d567613.
Unfortunately, #1700 caused as many problems as it solved. With those
changes in place, regular searches (not browses) that resulted in a
single record would cause the results list and details pane to be stuck
in an infinite refresh loop.
Refs [UIIN-2045](https://issues.folio.org/browse/UIIN-2045)
=> Revert "UIIN-2045 Fix browse form refresh issue (#1700)"

src/components/InstancesList/InstancesList.js
Pass new `syncQueryWithUrl` prop to `<SearchAndSort>` to synchronize the "SAS" local query state with query parameter in the url
[UIIN-2069](https://issues.folio.org/browse/UIIN-2069)
=> UIIN-2069 Synchronizing search query with url

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/constants.js, src/filterConfig.js
Added contributor type filter to query when going from browse contributors to searching instances by contributor
https://user-images.githubusercontent.com/19309423/177537262-4bcd1516-1fdd-47b0-89d1-77daff8fd006.mp4
[UIIN-2096](https://issues.folio.org/browse/UIIN-2096)
=> UIIN-2096 Browse contributors | Instance search query does not include contributor Name type

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/components/InstancesList/InstancesList.test.js
The "Instance" record still displayed at the third pane when user selects "Browse contributors" option
Redirect user to `inventory/` on `qindex` change to any browse options to close record view window.
[UIIN-2124](https://issues.folio.org/browse/UIIN-2124)
=> UIIN-2124: The "Instance" record still displayed at the third pane when user selects "Browse contributors" option

CHANGELOG.md, src/ViewInstanceWrapper.js
When navigating from one instance with a parent/child relation to another without the parent or child relation the relation from the previous instance would still be present in the local state.
This PR is trying to address it by checking if the newly opened instance has the parent and child relations present.
https://issues.folio.org/browse/UIIN-2129
=> UIIN-2129: Do not load child/parent relations when navigating between two instances

src/ViewInstance.js
Coerce a potentially undefined state value to boolean in order to avoid
a prop-types warning. Values in conditionals are automatically coerced,
hence this isn't necessary in the many other places where it's
evaluated. Here, however, where it's just passed as a (required) prop,
we need to coerce it to a boolean value.
(stumbled on this in the JS console while hunting for sth else)
=> coerce undefined to boolean

CHANGELOG.md, package.json
Add version `12.0` to the list of supported `inventory` interface versions.
`DELETE /inventory/instances` and `DELETE /inventory/items` have been deleting all records.
MODINV-731 changed them to delete records by CQL, this requires a major interface version bump.
ui-inventory doesn't use these two `DELETE` APIs therefore no code change is needed.
=> UIIN-2170: Support inventory 12.0 in okapiInterfaces

CHANGELOG.md, src/components/InstancesList/InstancesList.js
Update second pane header when clicking on browse results. Pane header checks `state.optionSelected` to decide when to show Actions button and what title to show. Need to set this state with correct value
https://user-images.githubusercontent.com/19309423/187957385-26b376af-6b19-4953-8fdf-100a34535f97.mp4
[UIIN-2172](https://issues.folio.org/browse/UIIN-2172)
=> UIIN-2172 Update second pane header when switching from browse to search

CHANGELOG.md, src/components/InstancesList/InstancesList.test.js, src/withFacets.js
Reset `qindex` when a query is being built for a given facet. This is required otherwise `makeQueryFunction` won't use `queryTemplate` and will fall back to a provided query value.
https://github.com/folio-org/stripes-smart-components/blob/e918a620ad2ac2c5b06ce121cd0e061a03bcfdf6/lib/SearchAndSort/makeQueryFunction.js#L46
Thank you @zburke for catching this issue.
https://issues.folio.org/browse/UIIN-2189
=> UIIN-2189 - Reset qindex inside buildQuery

CHANGELOG.md, package.json, src/constants.js, src/filterConfig.js, src/routes/buildManifestObject.js
Use `==/string` search when clicking on Browse contributors result, but just `=` search when searching contributors
Downgraded `history@5` to `history@4` due to incompatibility with `react-router@5`
Application behaves correctly because `<Root>` inside `stripes-core` uses `history@4`
But module level tests fail because `ui-inventory` uses `history@5`.
The source incompatibility lies in how `history` notifies `react-router` that location has changed.
Here's how `react-router` listens to this change: https://github.com/remix-run/react-router/blob/v5.3.3/packages/react-router/modules/Router.js#L47.
It accepts a single `location` argument that is saved inside state as `location`
`history@4` notifies listeners like so:
https://github.com/remix-run/history/blob/v4.10.1/modules/createBrowserHisto …
=> UIIN-2191 No results return when you conduct a Contributor search

CHANGELOG.md, src/views/ItemView.js, src/views/ItemView.test.js
This PR replaces #1791 
The list of bound-with titles (instances) on the item view did not have 
any means of navigating to those instances for additional details.  
Now the HRID is a clickable link to the instance view.
Adjust the formatter for that cell to enclose the HRID in a link.
For the unit test I originally wanted to test that the intended URL opened
as expected on the click.  Zak pointed me to an [alternate design pattern](https://stackoverflow.com/a/57907719)
for Jest & react-testing-library that just checks that the URL is correct.
https://issues.folio.org/browse/UIIN-2195
=> UIIN-2195: Link from bound-with table to instances

CHANGELOG.md, translations/ui-inventory/en.json
This accordion on the item view (and eventually on holdings view) displays more than just bound-with data.
This PR replaces #1787 per https://github.com/folio-org/ui-inventory/pull/1787#issuecomment-1255501986
Simple rename of the label in en.json.
https://issues.folio.org/browse/UIIN-2196
=> UIIN-2196: Relabel bound-with accordion

src/components/InstancesList/InstancesList.js
Set default value of `segment` prop
This is checked inside `componentDidUpdate` to equal `segments.instances` so `state.optionSelected` is not synced with `qindex`
https://user-images.githubusercontent.com/19309423/193043177-98a1997b-d980-46b3-974d-36548652de23.mp4
[UIIN-2181](https://issues.folio.org/browse/UIIN-2181)
=> UIIN-2181 Set default segment prop value to instances

CHANGELOG.md, src/ViewHoldingsRecord.js, src/ViewHoldingsRecord.test.js
This PR reverts the part of #1810 that adds a link from the item HRID,
as well as a test case for the link.
The [interim solution for the link](https://issues.folio.org/browse/UIIN-2018?focusedCommentId=145944&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-145944) was not acceptable.
I will be working separately on a different solution for the link, but
@CharlotteWhitt requested this patch in the meantime.
https://issues.folio.org/browse/UIIN-2018
=> UIIN-2018: remove bound-with link to item search

CHANGELOG.md, src/edit/items/ItemForm.js
I caused an NPE on effectiveLocation in ItemForm.js with PR #1832.  The context was a change
to how an existing item's effectiveLocation is displayed, where it should never be null.  But
I failed to consider the AddItem context where it is not yet set.  This PR adds null checks.
https://issues.folio.org/browse/UIIN-2227
=> UIIN-2227: Fix NPE on Add Item

CHANGELOG.md, src/Holding/ViewHolding/HoldingBoundWith/HoldingBoundWith.js, src/Holding/ViewHolding/HoldingBoundWith/HoldingBoundWith.test.js, src/Holding/ViewHolding/HoldingBoundWith/useBoundWithHoldings.js, src/Holding/ViewHolding/HoldingBoundWith/useBoundWithHoldings.test.js, src/Instance/ItemsList/ItemsList.js, src/ViewHoldingsRecord.js, src/hooks/useHoldingItemsQuery.js, src/hooks/useHoldingItemsQuery.test.js
On the instance view, the holdings list should include all items, whether 
bound-with the holdings record or directly linked.
/inventory/items-by-holdings-id fills this need directly.
I considered creating an alternate version of useHoldingsItemsQuery to use 
that API in place of /inventory/items, or passing in a parameter to indicate
which API to use, rather than just changing the existing hook.
I decided to change the existing useHoldingItemsQuery because 
1. it appears that all existing uses of the function now intend to include bound-with items
2. that seems to be the intention going forward -- i.e. there was
[intentionally no visible difference](https://issues.folio.org/browse/UIIN-2164?focusedCommentId=148699&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comme …
=> UIIN-2164: Add bound-with items to holdings list

CHANGELOG.md, src/Holding/ViewHolding/HoldingBoundWith/HoldingBoundWith.js, src/Holding/ViewHolding/HoldingBoundWith/HoldingBoundWith.test.js, src/Holding/ViewHolding/HoldingBoundWith/fixtures.js, src/Holding/ViewHolding/HoldingBoundWith/useBoundWithItems.js, src/Holding/ViewHolding/HoldingBoundWith/useBoundWithItems.test.js, src/ViewHoldingsRecord.js, src/ViewHoldingsRecord.test.js
On the holdings view, the bound-with table should list only bound-with items, and not 
directly-linked items.
The UI previously used inventory/items-by-holdings-id to populate that table, which
includes directly linked items.  That was an oversight.  This approach uses 
/inventory-storage/bound-with-parts to get the correct list of item HRIDs, followed by
/items-storage/items to get the actual items.
https://issues.folio.org/browse/UIIN-2260
=> UIIN-2260: Fix holdings view bound-with table

package.json
https://issues.folio.org/browse/UIIN-2257
Upgrade moment from 2.24.0 to >= 2.29.4 fixes these vulnerabilities:
https://nvd.nist.gov/vuln/detail/CVE-2022-31129 Regular Expression Denial of Service (ReDoS)
https://nvd.nist.gov/vuln/detail/CVE-2022-24785 Directory Traversal
=> UIIN-2257: Upgrade moment from 2.24.0 to >= 2.29.4

CHANGELOG.md, src/storage.js
Show a console warning when catching a `sessionStorage` error instead of just swallowing it.
Refs [UIIN-2276](https://issues.folio.org/browse/UIIN-2276)
=> UIIN-2276 warn on sessionStorage error

CHANGELOG.md, src/routes/buildManifestObject.js
https://issues.folio.org/browse/UIIN-2275
The but related to this searching by the subject was introduced by https://issues.folio.org/browse/UIIN-2075 which was added because the "subject" index also exists on the "browse" tab.
Since the "browse" was moved to its own route now we can get rid of this when the query is constructed under the instances route.
=> UIIN-2275: Use correct index when searching for subject

CHANGELOG.md, src/components/BrowseResultsList/BrowseResultsList.css, src/components/BrowseResultsList/BrowseResultsList.js, src/components/BrowseResultsList/BrowseResultsList.test.js, src/components/BrowseResultsList/getBrowseResultsFormatter.js, src/components/BrowseResultsList/getBrowseResultsFormatter.test.js, src/components/BrowseResultsList/utils.js, src/components/InstancesList/InstancesList.js, src/components/SearchModeNavigation/SearchModeNavigation.js, src/hooks/useInventoryBrowse/index.js, src/hooks/useInventoryBrowse/useInventoryBrowse.js, src/hooks/useInventoryBrowse/useInventoryBrowse.test.js, src/views/BrowseInventory/BrowseInventory.js
https://issues.folio.org/browse/UIIN-2266
Make one of a MCL columns a `TextLink` component to navigate to the instance `Search` page.
---
_Additional scope_ - display the last watched records in a list when an user returns back to the `Browse` page. Relates to https://github.com/folio-org/ui-inventory/pull/1842
Currently `Browse` records are loaded based on provided filters (parsed from `search`) after bouncing back. That returns user back to initial query, but not the latest page.
- move `isRowPreventsClick` and `getSearchParams` from `BrowseResultsList.js` into separate utils to reuse it;
- update `getBrowseResultsFormatter` to allow `TextLink` rendering for columns, that will navigate to instance results on the `Search` page;
- hoist `pageConfig` state to the `BrowseInventory.js` and …
=> UIIN-2266 Browse Lists | Hyperlink one column to improve accessibility

CHANGELOG.md, src/ViewHoldingsRecord.js, src/ViewHoldingsRecord.test.js, src/routes/ItemRoute.js, src/views/ItemView.js, src/views/ItemView.test.js
https://issues.folio.org/browse/UIIN-2289
Due to a limitation in `stripes-connect` the resources are not attached to the given component instance. This can cause some unexpected issues from time to time when the resource name is shared between multiple components. For example, when one component is unmounted when another is mounted the fetched data may get wiped unexpectedly from the redux store.
This PR uses unique names for instances of resource in ItemRoute and HoldingRecordView to avoid these types of collisions.
=> UIIN-2289: Rename instances1 resource on ItemsRoute to avoid colliding with holding records

CHANGELOG.md, src/routes/buildManifestObject.js, src/routes/buildManifestObject.test.js
https://issues.folio.org/browse/UIIN-2285
https://issues.folio.org/browse/UIIN-2294
PR https://github.com/folio-org/ui-inventory/pull/1908 included the removal of a piece of code responsible for correctly building the query when an entry is selected on the `Browse` page and navigated to the `Search` page in Inventory. That part of code didn't work properly, so it should be changed.
Check `selectedBrowseResult` for true in the query parameters and build a query that will return the same number of instances as in the corresponding browse row. Otherwise, use the default query template.
If there are …
=> UIIN-2285 UIIN-2294 Wrong operator used in request when user selects a record in browse results

CHANGELOG.md, src/components/InstancesList/InstancesList.js
https://issues.folio.org/browse/UIIN-2301
This is a regression after the work done in: https://github.com/folio-org/ui-inventory/pull/1928 related to opening up the item details pane.
If the single item is not found the instance detail pane should still open.
=> UIIN-2301: Open instance details pane in cases when single item is not found after search

CHANGELOG.md, src/facetUtils.js
https://issues.folio.org/browse/UIIN-2320
Extra whitespace was causing issues when searching for a given statistical code.
=> UIIN-2320 - Remove extra whitespace when parsing statistical code options

CHANGELOG.md, src/constants.js
Block item deletion for items with status 'Claimed returned'.
https://issues.folio.org/browse/UIIN-2137
=> UIIN-2136: Block item deletion for items with status 'Claimed returned'

CHANGELOG.md, src/Holding/EditHolding/EditHolding.js, src/Item/EditItem/EditItem.js, src/components/TitleField/TitleField.js, src/edit/precedingTitleFields.js
The HTTP errors were already handled correctly by mutation hooks but they were not rendered on the screen.
This PR is wiring error modal on `EditHolding` and `EditItem` components to make sure that the errors are displayed correctly.
https://issues.folio.org/browse/UIIN-2322
=> UIIN-2320: Wire ErrorModal in cases of HTTP errors during item and holding mutations

CHANGELOG.md, src/Item/EditItem/EditItem.js, src/Item/EditItem/EditItem.test.js, src/Item/hooks/index.js, src/Item/hooks/useBoundWithsMutation/index.js, src/Item/hooks/useBoundWithsMutation/useBoundWithsMutation.js, src/Item/hooks/useBoundWithsMutation/useBoundWithsMutation.test.js, src/edit/items/ItemForm.js
Delete linked bound-with parts.  Represented in the UI as an edit to the item record.
- Utilizes the new [PUT /inventory-storage/bound-withs](https://s3.amazonaws.com/foliodocs/api/mod-inventory-storage/p/bound-with-part.html#inventory_storage_bound_withs_put) API to replace the item's entire set of linked bound-with parts.  
- Although that API does both deletes and adds as needed, there's no UI functionality for Add yet so I've disabled the 'add' button.
- If the bound-with API call succeeds but then the Item update call fails, there is no rollback of the BW change.  I'm told there is no transactional behavior in the UI.
- Does this …
=> UIIN-2001: Delete bound-with parts

src/components/InstancesList/InstancesList.js, src/components/InstancesList/instances.css
After #1962 changed the links on the instances search results from row-level to column-level
(on the title field), there was insufficient color contrast between the title text and background.
This fixes the foreground color to the expected white.
First, I fixed a bug in the designated row formatter that I introduced in #1962.
The designation of DefaultMCLRowFormatter
had no effect because the argument name resultRowFormatter was typoed result**s**RowFormatter.
Due to the typo, [anchoredRowFormatter was being used by mistake](https://github.com/folio-org/stripes-smart-components/blob/master/lib/SearchAndSort/SearchAndSort.js#L1230).
Second, the necessary CSS selector from TextLink:
`div[class*=Selected] .root---FBI0e:visited`
was being overridden by CSS from MCL with equal specificity: …
=> UIIN-2176: Fix search results title color contrast

src/edit/succeedingTitleFields.test.js
Refs:
UIIN-1695
succeedingTitleFields
URL: https://issues.folio.org/browse/UIIN-1695
=> UIIN-1695 JEST/RTL test cases for succeedingTitleFields

CHANGELOG.md, src/constants.js
Do not allow for item removal when an item has a loan with a status set to `Declared lost` or `Awaiting delivery`. 
https://issues.folio.org/browse/UIIN-2187
https://issues.folio.org/browse/UIIN-2138
=> UIIN-2187: Do not allow for item removal with associated loan

CHANGELOG.md, src/hooks/useInventoryBrowse/useInventoryBrowse.js
Update browse results when visiting Browse page again
Decrease `staleTime` to `0` to instantly invalidate existing data so users can refresh it when they want.
https://user-images.githubusercontent.com/19309423/224754472-bef66e68-beca-4b37-8e7b-6ffd6ac21e9c.mp4
[UIIN-2342](https://issues.folio.org/browse/UIIN-2342)
=> UIIN-2342 Browse results are not updated when field with Subject/Contributor value is linked/unlinked

CHANGELOG.md, src/components/CheckboxFacet/CheckboxFacet.js, src/components/CheckboxFacet/CheckboxFacet.test.js, src/stores/facetsStore.js, src/stores/facetsStore.test.js
https://issues.folio.org/browse/UIIN-2350
https://issues.folio.org/browse/UIIN-2351
https://issues.folio.org/browse/UIIN-2352
The previous implementation stored the `searchTerm` within the local state of the `<CheckboxFacet>` component. When the `Reset all` action was initiated, this local state was not updated, resulting in the facets remaining hidden due to synchronization issues.
This PR addresses the problem by replacing the local state with the global state managed by the `facetsStore` (a zustand store). The store already maintains the `searchTerm` for all facets and is appropriately synchronized with the `Reset all` `button.
=> UIIN-2350: Lift the local state from CheckboxFacet into facetsStore

CHANGELOG.md, src/routes/ItemRoute.js
https://issues.folio.org/browse/UIIN-2355
The item resource was incorrectly referenced causing `staffMembers` resource to not load. 
This PR fixes the name of the resource so the staff member data is fetched correctly.
=> UIIN-2355: Use correct reference to item resource

CHANGELOG.md, src/views/ItemView.js
The 'Missing' and 'Withdrawn' options in the actions menu are absent for the item with 'In process' status.
- Refactor code to improve the readability of code
- Check if a user has perms to observe action menu items
=> UIIN-2338: The 'Missing' and 'Withdrawn' options in the actions menu are absent for item status "In process"

CHANGELOG.md, src/edit/electronicAccessFields.js, src/edit/items/ItemForm.js, src/routes/CreateHoldingRoute.js, src/routes/CreateItemRoute.js, src/routes/DuplicateHoldingRoute.js, src/routes/DuplicateItemRoute.js, src/routes/EditHoldingRoute.js, src/routes/EditItemRoute.js
Navigating away and back to an open item-edit or holdings-record-edit pane causes an NPE. Reloading resolves the issue.
- Add default values for undefined Objects and Arrays
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …
=> UIIN-2112: Navigating away and back to item-edit or holdings-edit screen throws NPE

CHANGELOG.md, src/constants.js, src/settings/TargetProfileDetail.js, src/settings/TargetProfileDetail.test.js
On the view screen of Inventory/Z39.50 target profiles, we currently send a GET request to fetch all job profiles and then filter them by ids on UI.
It's needed to adjust a request path to include filtering by ids into `query` param to perform filtering on BE. It also fixes a bug with sorting profiles [UIIN-2424](https://issues.folio.org/browse/UIIN-2424).
- Fetch default profiles from endpoint `data-import-profiles/jobProfiles/{id}`
- Fetch allowed profiles using `query` param
- Update unit tests
- What other modules will …
=> UIIN-2428: ISRI: Adjust jobProfiles GET request to fetch profiles by ids

CHANGELOG.md, src/Item/DuplicateItem/DuplicateItem.js
https://issues.folio.org/browse/UIIN-2419
When a library opens an item that has a last-check-in history, and duplicates the item, it does not expect the last check in history to follow in the duplicated record, because they are creating a new item that has almost always never circulated.
However, when you duplicate the item, it duplicates the lastCheckIn to the new item record.
- Omit `lastCheckIn` field when duplicating item
- …
=> UIIN-2419: When duplicating an item, the circulation history is duplicated when it should not be

CHANGELOG.md, src/constants.js, src/filterConfig.js
https://issues.folio.org/browse/UIIN-2443
The issue here was related to the work done in: https://issues.folio.org/browse/UIIN-2036.
In UIIN-2036 the idea was to be able to automatically open an item details view if the search was performed on one of these indexes:
````js
'items.barcode': 'barcode==%{query}',
isbn: 'isbn==%{query}',
issn: 'issn==%{query}',
hrid: 'hrid==%{query}',
iid: 'id==%{query}'
````
and the returned instance had a single item attached to it.
The problem with that approach is that the `hrid` index name has been the same for instances, holdings and items. 
If somebody searched for holdings record hrid there was no way to detect it and the code alway assumed that the search for item hrid was performed causing to open the item details screen (even though the intention …
=> UIIN-2443: Rename hrid qindex for item to avoid collisions with holdings ans instances

CHANGELOG.md, src/Instance/InstanceMovement/InstanceMovementDetails/InstanceMovementDetails.test.js, src/components/BrowseResultsList/utils.js, src/constants.js, src/filterConfig.js, src/routes/buildManifestObject.js, src/routes/buildManifestObject.test.js, test/jest/helpers/Harness.js
Escape quotes to search for `Subject` and `Contributor`.
- escaped query to search for `Contributor`;
- search by subjects has the same `queryTemplate` for both `Search` and `Browse` lookups, so I removed the redundant.
- changed the `Subjects` `queryTemplate` to get `authorityId` via `filters` parameter to utilize already existing query escaping in `makeQueryFunction`. 
[UIIN-2445](https://issues.folio.org/browse/UIIN-2445)
https://github.com/folio-org/ui-inventory/assets/77053927/4d8d4307-9d94-4f29-99f3-d1db9ea86f61
- What …
=> UIIN-2445: Escape quotes to search for Subject and Contributor.

CHANGELOG.md, src/edit/items/BoundWithModal.js, src/edit/items/BoundWithModal.test.js
https://issues.folio.org/browse/UIIN-2401
Reset input fields on `BoundWithModal` when the modal is closed.
=> UIIN-2401: Reset BoundWithModal when modal is closed

CHANGELOG.md, src/Holding/ViewHolding/HoldingBoundWith/useBoundWithHoldings.js, src/hooks/useChunkedCQLFetch.js
useBoundWithHoldings calls GET holdings-storage/holdings with a query of a list of holdings UUIDs combined with 'or'.  This works but fails when the number of holdings UUIDs causes the URL to exceed the length limit. 
There are several CQL "chunking" solutions via react-query useQuer**ies**()  across the UI modules:
https://github.com/search?q=org%3Afolio-org%20useQueries&type=code
The most recent, easiest to use, and (looks to me) most robust is in stripes-erm-components:
https://github.com/folio-org/stripes-erm-components/blob/master/lib/hooks/useChunkedCQLFetch.js
ui-inventory currently doesn't appear to use stripes-erm-components (not surprising, it's not part of ERM).  Since I'm solving this as part of a potential release patch, I didn't want to add a new dependency, so I've …
=> UIIN-2478: Fix useBoundWithHoldings for 100+ items

src/Holding/ViewHolding/HoldingBoundWith/useBoundWithHoldings.js
useBoundWithHoldings.js queries for a list of holdingsRecords by UUID.
It fails (sometimes) when the number of UUIDs is larger than 300, due to
something in the chunking logic in useChunkedCQLFetch().  Specifically
it appears to fail when the number of concurrent requests (5) and the
number of records fetched in each request (60) is not enough to retrieve
all the ids in a single batch of requests (60 * 5).  The final batch of records
(max length 60) does not succeed.  I haven't yet figured out why.
This patch mitigates the problem rather than solving it.
This patch de-dupes the list of holdingsRecord UUIDs.  This should have
been done anyway.  Since this hook is used to retrieve the holdings records
for all of the items directly or bound-with to each holdings record, it will
now only fail …
=> UIIN-2478 De-dup holdingsRecordIds fetched

CHANGELOG.md, src/ViewInstance.js, src/ViewInstance.test.js, src/routes/QuickMarcRoute.js, src/utils.js, src/utils.test.js
Add `Shared` search parameter when the user is redirected to the quick-marc page to identify shared record.
[UIIN-2517](https://issues.folio.org/browse/UIIN-2517)
https://github.com/folio-org/ui-quick-marc/pull/570 …
=> UIIN-2517: Add 'Shared' search parameter when the user is redirected to the quick-marc page to identify shared record.

src/components/InstancesList/InstancesList.js, src/edit/holdings/RemoteStorageWarning.test.js, src/edit/items/RemoteStorageWarning.test.js
When closing an Instance record we need to clear `lastOpenRecord` from storage
[UIIN-2442](https://issues.folio.org/browse/UIIN-2442)
=> UIIN-2442 Clear lastOpenRecord when closing an Instance record

PULL_REQUEST_TEMPLATE.md
The purpose of this PR is to simplify PR template, because, as practice shows, no one uses the `Pre-Merge Checklist` section, however, this takes up a lot of space in the description of the PR.
So I suggest leaving just:
=> Adjust PULL_REQUEST_TEMPLATE.md

CHANGELOG.md, src/Instance/ItemsList/ItemsList.js
To display item statuses in the item list (instance details view) in translated format.
- Use `intl.formatMessage` to display item statuses.
https://issues.folio.org/browse/UIIN-2473
=> UIIN-2473: i18n item status in item list

CHANGELOG.md, src/Instance/ItemsList/ItemsList.js
Sorting on the item table is not working.
- Use sorted `records` array instead of initial `items` prop
https://issues.folio.org/browse/UIIN-2528
=> UIIN-2528: Sorting on the Instance's Holdings item table is not working

CHANGELOG.md, src/ViewInstanceWrapper.js, src/common/hooks/useInstance.js
- Do not rely on `tenantId` property for getting instance details because this is not a required field
- If the `tenantId` is not provided then okapi tenant headed won't be overwritten
https://issues.folio.org/browse/UIIN-2541
=> UIIN-2541: Instance details are not shown on Inventory pane

CHANGELOG.md, src/Instance/InstanceEdit/InstanceEdit.test.js, src/components/InstancesList/InstancesList.test.js, src/constants.js
Enclose the query in quotes to allow for parentheses.
[UIIN-2516](https://issues.folio.org/browse/UIIN-2516)
https://github.com/folio-org/ui-inventory/assets/77053927/b6e074c4-f155-4252-81f7-6886e8049610
=> UIIN-2516: Enclose the query in quotes to allow for parentheses.

CHANGELOG.md, src/ViewInstanceWrapper.js
Make the `isShared` prop boolean to avoid crashes when calling methods from `undefined` (`isShared.toString()`).
It is env issue, but it interferes.
[UIIN-2554](https://issues.folio.org/browse/UIIN-2554)
https://github.com/folio-org/ui-quick-marc/pull/583
=> UIIN-2554: Make the isShared prop boolean to avoid crashes when calling methods from undefined.

CHANGELOG.md, src/routes/buildManifestObject.js, src/withFacets.js, src/withFacets.test.js
Add advanced search query for facets.
[UIIN-2536](https://issues.folio.org/browse/UIIN-2536)
https://github.com/folio-org/ui-inventory/assets/77053927/35771282-59fd-431b-8114-b31f5f982791
=> UIIN-2536: Add advanced search query for facets.

CHANGELOG.md, src/ViewInstance.js, src/ViewInstance.test.js, src/edit/InstanceForm.js, src/utils.js
Currently, shadow instance records (source value = MARC-shared/FOLIO-shared) are shown as local because the response from mod-search returns property shared = false, and the record is stored in a local member tenant storage. It is needed to display such instances as shared - check for source value as well.
- Create `util` to check if instance is a shadow copy of the shared instance (check for source value)
- Adjust View details/Edit screen header for shadow instances
https://issues.folio.org/browse/UIIN-2552
=> UIIN-2552: ECS: display shadow instances as shared

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/components/InstancesList/InstancesList.test.js, src/routes/buildManifestObject.js
- don't reset filters after changing a search option.
- resetting filters was added in this PR [#1717](https://github.com/folio-org/ui-inventory/pull/1717) which is no longer relevant, Browse search is used on a separate page;
- removed `getFetchProp` from `buildManifestObject` due to we no longer fire search when selecting the search option.
https://github.com/folio-org/stripes-smart-components/pull/1393
[UIIN-2566](https://issues.folio.org/browse/UIIN-2566)
https://github.com/folio-org/ui-inventory/assets/77053927/b1a9cdcb-4c96-4b98-9abb-13b834c09375
=> UIIN-2566: Don't reset filters after changing a search option.

CHANGELOG.md, src/ViewInstance.js, src/ViewInstance.test.js, src/components/InstancesList/InstancesList.js
Make the Move actions available regardless of how user navigated to the record.
[UIIN-2518](https://issues.folio.org/browse/UIIN-2518)
https://github.com/folio-org/ui-inventory/assets/77053927/1a6e9f98-0aca-46f3-81c0-fd6a3758bd2a
=> UIIN-2518: Make the Move actions available regardless of how user navigated to the record.

CHANGELOG.md, src/ViewInstance.js
To suppress `New request` action item from Consortial Central Tenant
- Check if user is in central tenant and hide the action item when true
https://issues.folio.org/browse/UIIN-2572
=> UIIN-2572: Consortial Central Tenant: Hide Instance Action Menu New Request option

CHANGELOG.md, src/views/ItemView.js
Sometimes a user gets an error when navigating to Item details view from Circulation log app.
- Add the optional chainig operator to `locationsById[item.effectiveLocation.id]`
https://issues.folio.org/browse/UIIN-2606
=> UIIN-2606: Item barcode redirects to the broken page in circ log

CHANGELOG.md, src/constants.js, src/routes/buildManifestObject.test.js, src/withFacets.test.js
Use `==` for exact phrase search in Advanced Search for all full text and term fields
https://github.com/folio-org/ui-inventory/assets/19309423/970f37d8-2418-432e-b51e-6b520232efb1
[UIIN-2612](https://issues.folio.org/browse/UIIN-2612)
=> UIIN-2612 The "Exact phrase" search gives incorrect results for all fields

CHANGELOG.md, src/components/NewOrderModal/NewOrderModalContainer.js, src/components/NewOrderModal/NewOrderModalContainer.test.js
In order to support creating an order from an instance in the "consortium" mode, a PO line form must have the ability to fetch instance data in the specific tenant (actually the central tenant for shared instances).
Provide instance tenant value (as `instanceTenantId` field) in the location state when navigating to the creating PO/PO Line.
https://issues.folio.org/browse/UIIN-2614
https://issues.folio.org/browse/UIOR-1159
Required by https://github.com/folio-org/ui-orders/pull/1511
https://github.com/folio-org/ui-inventory/assets/88109087/f5893533-496b-4c2a-b524-6636d3971df2
=> UIIN-2614 Provide an instance `tenantId` to the PO line form when creating an order from the instance

CHANGELOG.md, src/Instance/InstanceDetails/InstanceDetails.js, src/Instance/InstanceDetails/InstanceDetails.test.js
After clicking "Share local instance" button on Member Consortial Tenant Consortial holdings is not appearing immediately. User need to refresh the page to see that they are present. 
- To check if an instance is a shadow copy to display Consortial holdings accordion
- Adjust and add new unit tests
https://issues.folio.org/browse/UIIN-2629
=> UIIN-2629: Consortial holdings accordion is not appearing after the sharing of Instance

CHANGELOG.md, package.json, src/components/CheckboxFacet/CheckboxFacet.js, src/components/CheckboxFacet/CheckboxFacet.test.js
Fix issue with "+ More" button disappearing after user selects some Effective location filters and resets search form.
When user clicks "+ More" button `state.more` is calculated to increase by 5 every click. When user loads more `state.more` is now `dataOptions.length + 5`. And when user clicks "Reset all" - 5 initial options are rendered, but `state.more` is still more than 5 so `showMore={filteredOptions.length > more}` condition fails.
So the solution is to reset `state.more` to default value when component is re-rendered with fewer options
https://github.com/folio-org/ui-inventory/assets/19309423/e77d6772-8c85-413d-bdc1-24c86ac6fd93
[UIIN-2531](https://issues.folio.org/browse/UIIN-2531)
=> UIIN-2531 Reset CheckboxFacet state.more when user resets search form and fewer facet options are loaded.

CHANGELOG.md, src/Instance/InstanceEdit/InstanceEdit.js
Non-consortial tenant and consortial member tenant success toasts no longer show the Instance HRID.
- Get instance hrid from a component state instead of from the response, because response contains no body
https://issues.folio.org/browse/UIIN-2588
=> UIIN-2588: Edit instance success toast no longer shows the instance HRID

CHANGELOG.md, src/components/CheckboxFacet/CheckboxFacetList.js, src/components/CheckboxFacet/CheckboxFacetList.test.js, src/components/InstanceFilters/InstanceFilters.js, src/facetUtils.js, src/facetUtils.test.js
Show facet options, if they exist, after clicking the `+More` button.
BE currently returns 6 options for the facet, but some of them may have already been removed. There is no way to fix it on the BE side. The UI was now looking at these 6 options in the data and displaying a `+More` button if all 6 options existed. Because there are only 5 options, the `+More` button doesn't appear in the UI.
After this PR, if the BE returns 6 options for the facet and some of them cannot be found in the data (deleted), we display the `+More` button, just do not render the deleted options, which we mark as `isDeleted`.
Added `isFilterable`, `onSearch`, `onFetch` props to be able to filter options via the facet's input field.
[UIIN-2533](https://issues.folio.org/browse/UIIN-2533) …
=> UIIN-2533: Show facet options, if they exist, after clicking the +More button.

CHANGELOG.md, src/components/BrowseResultsList/BrowseResultsList.js, src/components/BrowseResultsList/BrowseResultsList.test.js, src/components/BrowseResultsList/getBrowseResultsFormatter.js, src/components/BrowseResultsList/utils.js, src/components/BrowseResultsPane/BrowseResultsPane.js
If Shared & Held by facets were selected in the Browse search, then retain them in the Search lookup after clicking the record.
[UIIN-2608](https://issues.folio.org/browse/UIIN-2608)
https://github.com/folio-org/ui-inventory/assets/77053927/15837da1-a81e-46c8-b560-9fcf164b5263
=> UIIN-2608: If Shared & Held by facets were selected in the Browse search, then retain them in the Search lookup after clicking the record.

CHANGELOG.md, src/Instance/InstanceDetails/InstanceTitleData/InstanceTitleData.js
In Nolana the Series heading is displaying as expected, but in Orchid Bugfest environment the Series heading has vanished from the detailed view. It was broken after [UIIN-2311](https://issues.folio.org/browse/UIIN-2311).
- use `checkIfArrayIsEmpty` to check whether there is some series info or not
https://issues.folio.org/browse/UIIN-2601
=> UIIN-2601: Instance. Series heading has vanished in detailed view

CHANGELOG.md, src/ViewHoldingsRecord.js, src/components/InstancesList/InstancesList.js, src/components/InstancesList/InstancesList.test.js, src/routes/ItemRoute.js
* User receives an error when searching for an item in the Inventory app.
* Added `state` prop to `history.push` to allow reading `tenant: '!{location.state.tenantTo}',` in `ItemRoute`'s manifest
* Execute `itemsByQuery.GET` request with current tenant
[UIIN-2634](https://issues.folio.org/browse/UIIN-2634)
https://github.com/folio-org/ui-inventory/assets/85172747/85bb0d38-e414-4738-a9b6-c2fcf68a4301
=> UIIN-2634: Remove error when search for an item

CHANGELOG.md, src/ViewInstance.js
When creating a new instance then success toast does not contain HRID info.
- Wait until the instance is fetched before displaying the success toast.
https://issues.folio.org/browse/UIIN-2635
=> UIIN-2635: Create new instance success toast no longer shows the instance HRID

CHANGELOG.md, src/Instance/InstanceEdit/InstanceEdit.js, src/hooks/useInstanceMutation/useInstanceMutation.js
Optimistic locking message for an instance in a non-consortial tenant is not displaying properly.
- Use `mutate` func instead of `mutateAsync` to mutate Instance
- Fix handling errors during instance mutation
https://issues.folio.org/browse/UIIN-2628
https://github.com/folio-org/ui-inventory/assets/55138456/58511b86-1214-4958-b878-a80780a32b14
=> UIIN-2628: Optimistic locking message not working for instances in non-consortial tenant

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/components/InstancesList/InstancesList.test.js, src/views/BrowseInventory/BrowseInventory.js, src/views/BrowseInventory/BrowseInventory.test.js
Make Inventory search and browse query boxes expandable
https://github.com/folio-org/ui-inventory/assets/19309423/e8a4ffd2-92bb-404f-bf1a-30629155d452
[UIIN-2493](https://issues.folio.org/browse/UIIN-2493)
https://github.com/folio-org/stripes-smart-components/pull/1407
=> UIIN-2493 Make Inventory search and browse query boxes expandable

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/components/InstancesList/InstancesList.test.js
Inventory search/browse: Do not retain checkbox selections when toggling search segment
https://github.com/folio-org/ui-inventory/assets/19309423/1c452061-80a3-4964-8ca8-ec4af570a1d7
[UIIN-2477](https://issues.folio.org/browse/UIIN-2477)
=> UIIN-2477 Inventory search/browse: Do not retain checkbox selections when toggling search segment.

CHANGELOG.md, src/ViewInstance.js
When a user with local tenant permissions exports single instance from Instance detail view, and the instance is shared then the file generated by the export is not posted to the data export in local tenant but in the central tenant, making it unavailable to the users who do not have central tenant permissions.
- Set member tenant id to headers when triggering quick-export of shared instance from the member tenant
https://issues.folio.org/browse/UIIN-2613
=> UIIN-2613: Single instance export - MARC files sent to central tenant from member tenant

CHANGELOG.md, src/filterConfig.js, src/hooks/useInstanceMutation/useInstanceMutation.test.js
Fix misspelled Instance notes (all) advanced search query index.
https://github.com/folio-org/ui-inventory/assets/19309423/63b06bd4-a650-4a2c-8aff-3874843b4d81
[UIIN-2677](https://issues.folio.org/browse/UIIN-2677)
=> UIIN-2677 Fix misspelled Instance notes (all) advanced search query index.

CHANGELOG.md, src/hooks/useHoldingsQueryByHrids.js
https://issues.folio.org/browse/UIIN-2658
The `=` operator was taking too long to finish in Poppy.
This PR switched from `=` to `==` operator when querying for `holdings-storage/holdings` by hrids.
=> UIIN-2658: Switch from = to == operator when querying for holdings-storage

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/components/InstancesList/InstancesList.test.js, src/views/BrowseInventory/BrowseInventory.js, src/views/BrowseInventory/BrowseInventory.test.js
Search box/Browse box- Reset all should shift focus back to search box 
Pass refs to `<SearchAndSort>` and use them to focus search box after reset
https://github.com/folio-org/ui-inventory/assets/19309423/f773b3f2-3103-48cf-90ea-daf70c266dfd
[UIIN-2514](https://issues.folio.org/browse/UIIN-2514)
https://github.com/folio-org/stripes-smart-components/pull/1413
https://github.com/folio-org/stripes-components/pull/2169
https://github.com/folio-org/stripes-acq-components/pull/727
=> UIIN-2514: Search box/Browse box- Reset all should shift focus back to search box 

CHANGELOG.md, src/ViewInstance.js
A user gets 403 error when trying to fetch a local instance sharing status. Send requests in the context of member tenant instead of central tenant.
- Send requests in the context of member tenant instead of central tenant.
https://issues.folio.org/browse/UIIN-2680
=> UIIN-2680: Fetch sharing of local instance status in the context of member tenant

CHANGELOG.md, src/ViewInstance.js
- Adjust handling of failed requests
- Create `renderInstanceDetails` to render details conditionally and have only one `Callout` component in the tree
- Handle errors when fetching `MARC authorities`
https://issues.folio.org/browse/UIIN-2682
=> UIIN-2682: Handle errors correctly when sharing local instances failed

CHANGELOG.md, src/components/InstancesList/InstancesList.js
Ignored hot key command  (ALT + n) on edit fields.
Prevent execute hot key command on edit fields to able input special characters like polish "ń" 
By detect target event is edit field 
[UIIN-2604](https://issues.folio.org/browse/UIIN-2604)
=> UIIN-2604 Ignored hot key command on edit fields.

CHANGELOG.md, src/withFacets.js, src/withFacets.test.js
Remove unsupported `sort` parameter from requests to facets
https://github.com/folio-org/ui-inventory/assets/19309423/500483dd-73b3-4276-a111-5f0b5ef69389
[UIIN-2685](https://issues.folio.org/browse/UIIN-2685)
=> UIIN-2685 Remove sort parameter from requests to facets

CHANGELOG.md, src/Instance/InstanceEdit/InstanceEdit.css, src/Instance/InstanceEdit/InstanceEdit.js, src/utils.js
When there is an error while saving the edited instance, the confirmation modal shows "undefined" instead of an error message.
- To parse error correctly
https://issues.folio.org/browse/UIIN-2686
=> UIIN-2686: "Saving instance failed" modal does not show error message

CHANGELOG.md, src/components/BrowseResultsList/getBrowseResultsFormatter.js, src/components/BrowseResultsList/getBrowseResultsFormatter.test.js, src/components/BrowseResultsList/utils.js
Make browse result items that are not anchors and have no records not clickable, and show 0 in number of titles.
This is to fix a bug with Browsing contributors and subjects. In consortial environment, when browsing with `Shared: No` back-end returns items related to shared records. This is because search index does not differentiate between local and shared Instance records.
Since we can't remove the items from results without changing the index, the workaround for now is to identify such records (non-anchor and with 0 total results) and make them not clickable
https://github.com/folio-org/ui-inventory/assets/19309423/c236a1f6-e0ff-4fd0-b9e0-338c39f1e4d5
[UIIN-2699](https://issues.folio.org/browse/UIIN-2699)
=> UIIN-2699 Make browse result items that are not anchors and have no records not clickable, and show 0 in number of titles.

CHANGELOG.md, src/ViewInstance.js
* When user click "Share" button on "Are you sure you want to share this instance?" modal window the "Share" button is still active so he can pressed it again that will go to the error "Local instance was not shared". If environment is overloaded it can delay the response in modal window so user thought that it "Share" button was not clicked and click it one more time and get an error, so it's better to disable "Share" button after the first click
* Add `isShareButtonDisabled` to the state (false by default)
* Disable `Share` button when user clicks on it
* Enable `Share` button when there was an error during sharing OR sharing is done OR when there is an error during unlinking MARC Authorities
[UIIN-2704](https://issues.folio.org/browse/UIIN-2704) …
=> UIIN-2704: Disable the Share button after clicking on it once

CHANGELOG.md, src/ViewInstance.test.js, src/views/BrowseInventory/BrowseInventory.js, src/views/BrowseInventory/BrowseInventory.test.js
Always highlight the first list row after pagination is clicked (not always highlighted due to deletion of the `itemToView` after loading data).
[UIIN-2708](https://issues.folio.org/browse/UIIN-2708)
https://github.com/folio-org/ui-inventory/assets/77053927/36632216-83cb-4aff-8c46-8d2577656dda
=> UIIN-2708: Always highlight the first list row after pagination is clicked.

CHANGELOG.md, src/Instance/InstanceDetails/InstanceDetails.js, src/ViewInstance.js, src/ViewInstanceWrapper.js, src/ViewInstanceWrapper.test.js, src/components/HelperApp/HelperApp.js
The quantity of assigned tags to the instance is not displaying in the a little tag icon after assigning.
- Refetch instance after successful mutation. The bug was caused by refactoring the instance details pane to use `react-queries`.
https://issues.folio.org/browse/UIIN-2559
=> UIIN-2559: The quantity of assigned tags to the instance is not displaying in the little tag icon after assigning

CHANGELOG.md, src/components/WarningMessage/WarningMessage.css, src/edit/items/BoundWithModal.css
https://issues.folio.org/browse/UIIN-2716
We're on a mission to remove an out-of-date dependency of our CSS pipeline, `postcss-color-function`. `color()` as we used it, was removed from its proposal and ultimately changed in native CSS API to convert color spaces rather than blend colors. 
The functionality has been replaced via the `color-mix()` function as well as the new relative-color-syntax. This PR uses both.
The colors are a very near match..
This relates back, but is only blocked by https://github.com/folio-org/stripes-webpack/pull/133 for firefox support.
=> UIIN-2716 Refactor CSS away from postcss-color-function

CHANGELOG.md, src/Instance/InstanceDetails/ConsortialHoldings/ConsortialHoldings.js, src/providers/DataProvider.js
ECS: when viewing instances with more than one holding record there is a UX error.
- Filter member tenants correctly
- Add limit param for tenants request
https://issues.folio.org/browse/UIIN-2724
=> UIIN-2724: ECS: id of member tenant is undefined when rendering consortial holdings

CHANGELOG.md, package.json, translations/ui-inventory/en.json
* Add new permission to set FOLIO instance and MARC bib records for Deletion. 
* Added permission to `package.json`
* Added translation
[UIIN-2593](https://issues.folio.org/browse/UIIN-2593)
=> UIIN-2593: Add permission for setting record for deletion

CHANGELOG.md, src/Holding/ViewHolding/HoldingReceivingHistory/HoldingReceivingHistory.js, src/Holding/ViewHolding/HoldingReceivingHistory/HoldingReceivingHistory.test.js, src/edit/items/ItemForm.js, src/views/ItemView.js, translations/ui-inventory/en.json
Ensure the synchronized data points between different UIs (basically receiving and inventory) are named consistently.
Add a new field "Display summary" to the item view and form.
Update "Caption" to "Display summary" in the holding receiving history.
UI Jira - https://issues.folio.org/browse/UIIN-2740
BE Jira - https://issues.folio.org/browse/MODORDERS-1000
https://github.com/folio-org/ui-inventory/assets/88109087/eeb1fac0-7166-47cd-ad17-25201abb8cc9
=> UIIN-2740 Add 'Display summary' field to item enumeration data accordion

CHANGELOG.md, src/Holding/EditHolding/EditHolding.js
* The user should be redirected to the 'Holdings detail' page after clicking on the 'Save and close' button.
* When cancel editing or submitting changes, redirect user to Holdings detail page.
[UIIN-2734](https://issues.folio.org/browse/UIIN-2734)
https://github.com/folio-org/ui-inventory/assets/85172747/60be3eb3-e274-45c2-8f8f-e4feee651f83
=> UIIN-2734: Display the 'Holdings detail' page after saving the holdings changes

CHANGELOG.md, src/ViewInstance.js, src/ViewInstance.test.js, translations/ui-inventory/en.json
* This story covers invoking the **Set record for deletion** option from the Actions menu.
* Once the changes are saved a success message banner is displayed: **[Instance title] has been set for deletion**
* If an error occurs the error message banner is displayed: **[Instance title] was not set for deletion**
* Added unit tests
[UIIN-2595](https://issues.folio.org/browse/UIIN-2595)
https://github.com/folio-org/ui-inventory/assets/85172747/baec97b7-149d-4136-a79b-44ad258c2adf
=> UIIN-2595: Action when `Set record for deletion` option is invoked

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/components/InstancesList/InstancesList.test.js, src/routes/buildManifestObject.js, test/fixtures/instances.js
Using a consortium environment when searching for an item using `barcode` and there is only one result with the item belonging to some other member tenant, the item details view is not opening.
- Get items for a particular tenant
- Navigate to the details view when there is only one search result
https://folio-org.atlassian.net/browse/UIIN-2698
=> UIIN-2698: Detail view not opened for non-local items when one shared record found using "Barcode" search on "Item" tab

CHANGELOG.md, src/ViewHoldingsRecord.js, src/views/ItemView.js
* There’s security vulnerability for holdings and items, but instances is fine.  The goal here is to adjust the code for holdings and items so it’s consistent with instances and therefore no longer a security risk.
* Made Holdings/Item Electronic Access URIs consistent with Instances
[UIIN-2778](https://folio-org.atlassian.net/browse/UIIN-2778)
=> UIIN-2778: Display Holdings/Item Electronic Access URIs consistent with Instances

CHANGELOG.md, package.json, src/components/HoldingsRecordFilters/HoldingsRecordFilters.js, src/components/HoldingsRecordFilters/HoldingsRecordFilters.test.js, src/components/InstanceFilters/InstanceFilters.js, src/components/InstanceFilters/InstanceFilters.test.js, src/components/ItemFilters/ItemFilters.js, src/components/ItemFilters/ItemFilters.test.js, src/filterConfig.js, src/hooks/index.js, src/hooks/useStaffSuppressInitialValue/index.js, src/hooks/useStaffSuppressInitialValue/useStaffSuppressInitialValue.js, src/hooks/useStaffSuppressInitialValue/useStaffSuppressInitialValue.test.js, src/routes/buildManifestObject.js, src/routes/buildManifestObject.test.js, src/withFacets.js, src/withFacets.test.js, test/jest/__mock__/stripesCore.mock.js
Apply `staffSuppress.false` filter to all search and facet requests by default.
Users without `Inventory: Enable staff suppress facet` permissions don't have the ability to search for staff suppressed records and to change selected Staff Suppress facet value.
Users with the permission can see and change facet values.
**User with Staff Suppress facet permissions**
https://github.com/folio-org/ui-inventory/assets/19309423/f14fa8f4-ed04-4a19-971e-cb0520aac151
**User without Staff Suppress facet permissions**
https://github.com/folio-org/ui-inventory/assets/19309423/8282d79c-ed2f-41af-8687-145e596a87b7
[UIIN-2596](https://folio-org.atlassian.net/browse/UIIN-2596)
=> UIIN-2596  Staff suppress facet - use `No` as default value. Hide the facet when users don't have permissions to use it.

CHANGELOG.md, src/providers/HoldingsProvider.js
Unizar is reporting the issue In FOLIO only 1000 Holdings instances are viewed, the customer is saying they have 1346 in total.
Increase holdings limit to 5000.
https://folio-org.atlassian.net/browse/UIIN-2785
=> UIIN-2785: Increase holdings limit to 5000

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/routes/InstancesRoute.js
Remove unused code related to auto-open record detail view (third pane).
The `showSingleResult` prop is passed from `InstancesRoute` and is always `true`. This prop should always be true for `SearchAndSort` because we are using the auto-opening feature, and there is no need to pass it from the route component.
This code snippet is from a time when `Search` and `Browse` searches were not separated. It is no longer needed.
```
const onChangeIndex = () => {
this.setState({ isSingleResult: true });
};
```
[UIIN-2819](https://folio-org.atlassian.net/browse/UIIN-2819)
=> UIIN-2819: Remove unused code related to auto-open record detail view.

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/components/InstancesList/InstancesList.test.js, src/routes/buildManifestObject.js, src/utils.js, src/views/BrowseInventory/BrowseInventory.js
Apply staffSuppress.false when switching between Instance/Holdings/Items search
If a user doesn't have permissions to use Staff Suppress facet - when `staffSuppress.true` is present in the url then it should be changed to `staffSuppress.false`.
https://github.com/folio-org/ui-inventory/assets/19309423/8209356c-8527-4670-9a65-13469f003b29
[UIIN-2814](https://folio-org.atlassian.net/browse/UIIN-2814)
=> UIIN-2814 Apply staffSuppress.false in Holdings/Items search

CHANGELOG.md, package.json, src/components/InstancesList/InstancesList.js, translations/ui-inventory/en.json
Douglas College got an error message while trying to generate the “In Transit Items Report” in the Inventory module because of missed permission. It is required to create a separate UI permission for “In Transit Items Report” generating.
- Added a new **"Inventory: Create and download In transit items report"** UI permission
- Hidden `In transit items report (CSV)` action item for users without permission.
- Fix versions in CHANGELOG (`11.0.1` - Quesnelia Bugfix, `11.1.0` - Ramsons)
https://folio-org.atlassian.net/browse/UIIN-2776
**UI permission**
**Actions menu with permission**
**Actions menu without permission**
=> UIIN-2776: Add a new "Inventory: Create and download In transit items report" permission

src/index.js
Follow-up PR.
~~Windows computers should see `Ctrl` for the `quick-marc` shortcuts.
MAC computers should see `Control` for the `quick-marc` shortcuts.~~
Requirement change: show `Ctrl` for both OS for prev/next subfield shortcuts ([details](https://folio-org.atlassian.net/browse/UIIN-2795?focusedCommentId=207160)).
~~https://github.com/folio-org/stripes-components/pull/2260~~
[UIIN-2795](https://folio-org.atlassian.net/browse/UIIN-2795)
For Windows
For MAC
=> UIIN-2795: Replace 'Mod' with 'Control' for the quick-marc shortcuts.

CHANGELOG.md, src/Holding/ViewHolding/HoldingReceivingHistory/HoldingReceivingHistory.js, translations/ui-inventory/en.json
https://folio-org.atlassian.net/browse/UIIN-2826 - Add "Display to public" column to receiving history on Holdings
https://github.com/folio-org/ui-inventory/assets/116072773/32470e19-81f0-4226-a9f0-b3651333c2ca
=> UIIN-2826: Add "Display to public" column to receiving history on Holdings

src/Holding/ViewHolding/HoldingReceivingHistory/HoldingReceivingHistory.js
https://folio-org.atlassian.net/browse/UIIN-2826
use correct column from holding receiving history
=> UIIN-2826 Add "Display to public" column to receiving history on Holdings

CHANGELOG.md, package.json, translations/ui-inventory/en.json
Upon review, we feel that the permission should specifically speak to the ‘set record for deletion’ action ability. Even though the action does apply staff suppressed field too, I fear the current language could be confusing.
- Update permission name.
https://folio-org.atlassian.net/browse/UIIN-2855
=> UIIN-2855: Update Permission name for Inventory: Set records for deletion and staff suppress

CHANGELOG.md, package.json
[UIIN-2780](https://folio-org.atlassian.net/browse/UIIN-2780) requires to have `consortium-search.items.collection.get` and `consortium-search.holdings.collection.get` permissions assigned to a member tenant to be able to fetch limited info about holdings/items. These permissions should not be visible via UI but rather be assigned automatically that is why we decided to add these to the "Inventory: Module is enabled" sub-permissions.
- Add missing perms to the "Inventory: Module is enabled" sub-permissions
https://folio-org.atlassian.net/browse/UIIN-2860
=> UIIN-2860: Include mod-search permissions to "Inventory: Module is enabled" UI permission

src/components/BrowseResultsList/constants.js
Follow-up pull request.
Make the classification column 50% width in the Browse results.
[UIIN-2624](https://folio-org.atlassian.net/browse/UIIN-2624)
=> UIIN-2624: Make classification column 50% width in the Browse results.

CHANGELOG.md, src/Instance/InstanceDetails/SubInstanceList/SubInstanceList.test.js, src/components/ConnectedTitle/ConnectedTitle.test.js, src/utils.js
After this PR merged: 
- coverage for ConnectedTitle will be 100%
- fixed a condition that was never met
Ref: [UIIN-2666](https://folio-org.atlassian.net/browse/UIIN-2666)
=> UIIN-2666 Jest/RTL: Cover ConnectedTitle component with unit tests

CHANGELOG.md, src/Instance/MoveHoldingContext/MoveHoldingContext.test.js, test/fixtures/holdingsById.js, test/fixtures/index.js, test/fixtures/locationsById.js, test/fixtures/movingInstances.js
After this PR merged test coverage for MoveHoldingContext.js component will be ~80%
Covered all functinality inside MoveHoldingContext except drag/drop between lists, because as per now it's not good way to do that for react-butiful-dnd. Covered moving of holindgs using dropdown menu instead.
https://folio-org.atlassian.net/browse/UIIN-2664
=> UIIN-2664 Jest/RTL: Cover MoveHoldingContext component with unit tests

CHANGELOG.md, package.json, src/hooks/useLocationsForTenants/useLocationsForTenants.js, src/hooks/useLocationsForTenants/useLocationsForTenants.test.js, src/providers/DataProvider.js
Use consolidated locations endpoint to fetch all locations when in central tenant context.
https://github.com/folio-org/ui-inventory/assets/19309423/5118de48-895f-4413-919f-351a20b2a151
[UIIN-2811](https://folio-org.atlassian.net/browse/UIIN-2811)
=> UIIN-2811 Use consolidated locations endpoint to fetch all locations when in central tenant context.

CHANGELOG.md, package.json
Changes from `UIIN-2886` were pushed directly in `b10.0` because we don't need them neither in master nor in Q bugfix. It's only for CSP.
=> Release v10.0.15

CHANGELOG.md, package.json, src/components/InstancesList/InstancesList.js, src/constants.js, src/filterConfig.js
Added `stripes-inventory-components` to peerDeps list
Moved advanced search query builder util to `stripes-inventory-components`
[UIIN-2910](https://folio-org.atlassian.net/browse/UIIN-2910)
https://github.com/folio-org/stripes-inventory-components/pull/37
=> UIIN-2910 *BREAKING* Added a new `stripes-inventory-components` dependency. Move some utils to that module.

src/ViewHoldingsRecord.js, src/ViewInstance.js, src/components/ViewSource/ViewSource.js, translations/ui-inventory/en.json
Show callout when user doesn't have permissions to use edit MARC shortcut (follow-up)
Check for correct permissions in View Holdings and View Source pages
https://github.com/folio-org/ui-inventory/assets/19309423/898a7769-2d50-4819-becf-54e7e83e96a2
[UIIN-2896](https://folio-org.atlassian.net/browse/UIIN-2896)
=> UIIN-2896 Show callout when user doesn't have permissions to use edit MARC shortcut (follow-up)

CHANGELOG.md, src/Instance/InstanceEdit/InstanceEdit.js, src/edit/InstanceForm.js, src/edit/InstanceForm.test.js
Edit Inventory Instances: Display a Save & keep editing button
When user clicks "Save & keep editing" they should stay on the edit record page with updated data
https://github.com/folio-org/ui-inventory/assets/19309423/b7d303e3-1139-4d5b-a528-6b9db74e3476
[UIIN-2457](https://folio-org.atlassian.net/browse/UIIN-2457)
https://github.com/folio-org/stripes-components/pull/2292
=> UIIN-2457 Edit Inventory Instances: Display a Save & keep editing button

src/components/BoundPiecesList/BoundPiecesList.js, translations/ui-inventory/en.json
[UIIN-2760](https://folio-org.atlassian.net/browse/UIIN-2760): add modal title for removing piece
=> UIIN-2760: add modal title for removing piece

src/components/BrowseResultsList/BrowseResultsList.js, src/components/BrowseResultsList/getBrowseResultsFormatter.js, src/components/InstancesList/InstancesList.js, src/components/SearchModeNavigation/SearchModeNavigation.js, src/routes/InstancesRoute.js, src/views/BrowseInventory/BrowseInventory.js
- when both `ui-inventory` and `ui-plugin-find-instance` facets are visible, opening the plugin facet will also open the inventory facet. This is due to state being stored in one place for all modules. In the related PR the namespace is added for `facetsStore` to separate state for each module, all that's left is to pass the correct namespace;
- use `renderFilters` from `stripes-inventory-components` to reduce duplication.
https://github.com/folio-org/stripes-inventory-components/pull/50
[UIIN-2938](https://folio-org.atlassian.net/browse/UIIN-2938)
https://github.com/folio-org/ui-plugin-find-instance/assets/77053927/0a67cfba-107f-4c21-8143-442c835e3873
=> UIIN-2938: Use namespace to store facets state separately for different modules (follow-up PR).

CHANGELOG.md, src/edit/items/ItemForm.js
To make item status translatable in the item edit view.
- Add item status translations from `stripes-inventory-components`
https://folio-org.atlassian.net/browse/UIIN-2766
=> UIIN-2766: i18n item status in item edit view

CHANGELOG.md, package.json, src/settings/TargetProfiles.js
* When user has `Settings (Inventory): Configure single-record import` permission, we should enable `+New` and `Edit`
* Replace the `ui-inventory.single-record-import` permission with `ui-inventory.settings.single-record-import`.
* Add additional `inventory-storage.identifier-types.collection.get` permission to `Settings (Inventory): Configure single-record import` in order to get identifier types.
[UIIN-2771](https://folio-org.atlassian.net/browse/UIIN-2771)
=> UIIN-2771: Enable `+ New` and `Edit` buttons when user has `Settings (Inventory): Configure single-record import` permission

CHANGELOG.md, src/settings/HRIDHandling/HRIDHandlingSettings.js, src/settings/HRIDHandling/HRIDHandlingSettings.test.js, src/settings/index.js
* Allow user to view "HRID handling" section when `Settings (Inventory): View list of settings pages` permission is assigned.
* Disable fields in "HRID handling" section when `Settings (Inventory): Create, edit and delete HRID handling` permission is not assigned to user.
[UIIN-2773](https://folio-org.atlassian.net/browse/UIIN-2773)
=> UIIN-2773: Disable fields in "HRID handling" section when `Settings (Inventory): Create, edit and delete HRID handling` permission is not assigned

CHANGELOG.md, package.json, src/settings/TargetProfileForm.test.js
* In order to get list of statistical code types when view statistical codes, we need to update  `Settings (Inventory): Create, edit, delete statistical codes` permission.
* Added `inventory-storage.statistical-code-types.collection.get` to sub permissions.
[UIIN-2772](https://folio-org.atlassian.net/browse/UIIN-2772)
=> UIIN-2772: Update `Settings (Inventory): Create, edit, delete statistical codes` permission

CHANGELOG.md, package.json
Include `@folio/stripes-inventory-components` and
`@folio/stripes-marc-components` in `stripesDeps` to cause the translations defined in those shared libraries to be picked up by stripes-webpack when creating the bundle. Although it is possible to add translations to the bundle by directly including these modules in `stripes.config.js`, that's the wrong way to go about it (although it has the same effect) since these are just shared modules, not directly-useable applications.
Refs [UIIN-2968](https://folio-org.atlassian.net/browse/UIIN-2968)
=> UIIN-2968 include translations from all shared @folio libraries

CHANGELOG.md, src/components/BrowseResultsList/BrowseResultsList.test.js, src/components/BrowseResultsList/getBrowseResultsFormatter.js, src/components/BrowseResultsList/getBrowseResultsFormatter.test.js, src/components/BrowseResultsList/utils.js
Create a text link for classification numbers based on classification types.
Currently, when a user hits a classification number in the Browse search, they are redirected to the Search lookup, and the search is performed without regard to the classification types selected in Settings. 
Now, the search respects the selected types by extending the text link with `classifications.classificationTypeId`.
[UIIN-2907](https://folio-org.atlassian.net/browse/UIIN-2907)
https://github.com/folio-org/ui-inventory/assets/77053927/c8145aa2-7794-47ac-a569-f375d15f8302
=> UIIN-2907: Create a text link for classification numbers based on classification types.

CHANGELOG.md, src/views/BrowseInventory/BrowseInventory.js, src/views/BrowseInventory/BrowseInventory.test.js
Prevent removing spaces on change in Browse search.
Add `skipTrimOnChange` flag to `useLocationFilters` hook to prevent unnecessary trims on change.
[UIIN-2976](https://folio-org.atlassian.net/browse/UIIN-2976)
https://github.com/user-attachments/assets/8db510bb-4d98-4998-a41d-c913fd85cda5
=> UIIN-2976: Add `skipTrimOnChange` option to `useLocationFilters` hook to prevent unnecessary trims on change.

CHANGELOG.md, src/Instance/InstanceDetails/InstanceAdministrativeView/StatisticalCodesList.js, src/Instance/InstanceDetails/InstanceDetails.test.js, src/ViewHoldingsRecord.js, src/views/ItemView.js
In the Inventory Settings page there are **Statistical code type** and **Statistical code name** fields, but in instances, holdings, and items there are **Statistical code type** and **Statistical code**. This is confusing because when a user sets up these codes then they have to specify a name and a code, but these configurations don’t match with the Inventory UI.
- Render correct labels.
https://folio-org.atlassian.net/browse/UIIN-2922
=> UIIN-2922: Wrong statistical code column heading is displayed in instances, holdings, and items

CHANGELOG.md, src/utils.js
Consume FormattedDate and FormattedTime via stripes-components instead of react-intl in order to have the value prop automatically reformatted into a compliant string.
- Import {{FormattedTime}} from stripes-component.
https://folio-org.atlassian.net/browse/UIIN-1273
=> UIIN-1273: Inventory App: Consume {{FormattedTime}} via stripes-component

CHANGELOG.md, src/common/hooks/useBoundPieces/useBoundPieces.js, src/components/BoundPiecesList/utils.js
[UIIN-2984](https://folio-org.atlassian.net/browse/UIIN-2984): Add barcode values for "Bound pieces data" and update `useBoundPieces` hook query with `bindItemId` to fetch bound pieces correctly
https://github.com/user-attachments/assets/2a1599b8-aa2f-49df-9b07-187090f35f2c
=> UIIN-2984: Add barcode values for "Bound pieces data" and update `useBoundPieces` hook query with `bindItemId` to fetch bound pieces correctly

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/components/InstancesList/InstancesList.test.js, src/routes/buildManifestObject.test.js, src/utils.js, src/utils.test.js, test/jest/__mock__/stripesInventoryComponents.mock.js
Browsers have a limit of how many characters can be in a URI. When that limit exceeds HTTP requests fail
That happens in Inventory as well. When there are too many characters we need to split one query into multiple and join responses
https://github.com/user-attachments/assets/b6253605-6454-4c92-9e47-c7148c0ef4a5
[UIIN-2977](https://folio-org.atlassian.net/browse/UIIN-2977)
=> UIIN-2977 Save Instances UUIDs - When request URI exceeds character limit split request.

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/routes/InstancesRoute.js, src/routes/buildManifestObject.js, src/routes/buildManifestObject.test.js, src/views/InstancesView.js
When the request URL exceeds the limit:
1. Show an error toast message;
2. Show a specific error message inside the results list.
Export `buildRecordsManifest` to have one source of truth for ui-inventory and ui-plugin-find-instance.
Use `withSearchErrors` to show the error toast message, it also provides the `isRequestUrlExceededLimit` property for displaying correct error message in results pane.
The tests will pass once the related PRs are merged.
[UIIN-2970](https://folio-org.atlassian.net/browse/UIIN-2970)
https://github.com/folio-org/stripes-inventory-components/pull/61
https://github.com/folio-org/stripes-smart-components/pull/1496
https://github.com/user-attachments/assets/6a60bced-cbc3-4d86-b78e-efe99428f664
=> UIIN-2970: Use `withSearchErrors` HOC and `buildRecordsManifest` to display an error when the request URL is exceeded.

CHANGELOG.md, src/common/hooks/useInstance.js, src/common/hooks/useInstanceQuery/useInstanceQuery.js, src/common/hooks/useSearchInstanceByIdQuery/useSearchInstanceByIdQuery.js
When local Instance is successfully shared User can see the Shadow copy of that Instance (UUID the same, HRID is changed to reflect the central sequence, source is MARC/FOLIO-shared). This Instance appears to be manageable even though it is not, any attempt to edit it will result in error. When page is refreshed, the Shared Instance is displayed and can be successfully edited.
Display Shared Instance right after the sharing. In that case, User will not be able to see/access Shadow copy in any way from UI.
https://folio-org.atlassian.net/browse/UIIN-2969
=> UIIN-2969: Display shared instance immediately after the instance was shared

src/components/InstancesList/InstancesList.js
disable Save Instance UUIDs action when search results are empty and request did not faiol due to limit
[UIIN-2977](https://folio-org.atlassian.net/browse/UIIN-2977)
=> UIIN-2977 disable Save Instance UUIDs action when search results are empty and request did not faiol due to limit (follow-up)

CHANGELOG.md, src/components/FilterNavigation/FilterNavigation.js, src/components/FilterNavigation/FilterNavigation.test.js, src/components/InstancesList/InstancesList.js, src/components/InstancesList/InstancesList.test.js, src/components/SearchModeNavigation/SearchModeNavigation.js, src/components/SearchModeNavigation/SearchModeNavigation.test.js
Be able to see facet options after clicking on the current tab (Search/Browse or Instance/Holdings/Item) and then opening the facet.
If a user clicks a current search segment or search mode, do nothing.
Test will pass after the related PR is merged.
https://github.com/folio-org/stripes-inventory-components/pull/67
[UIIN-2949](https://folio-org.atlassian.net/browse/UIIN-2949)
https://github.com/user-attachments/assets/9dbe1d67-0140-4d4a-984c-30e902459eb3
=> UIIN-2949: Prevent callbacks from being triggered when clicking on the current tab, whether it's lookup mode or a search segment.

CHANGELOG.md, translations/ui-inventory/en.json
Create a new ‘Inventory: Update ownership’ permission to control the display of the Update ownership action.
- Added translation for the permission that was added on the backend side, refer to the PR - https://github.com/folio-org/mod-consortia/pull/155
https://folio-org.atlassian.net/browse/UIIN-2981
=> UIIN-2981: Create a new ‘Inventory: Update ownership’ permission to control display of Update ownership action

CHANGELOG.md, package.json, translations/ui-inventory/en.json
Create a new ‘Settings (Inventory): Create, edit, delete subject sources’ permission to control the display and edit of the Inventory Subject sources settings.
- Add new permission
https://folio-org.atlassian.net/browse/UIIN-3010
=> UIIN-3010: Add inventory permission: Settings (Inventory): Create, edit, delete subject sources

CHANGELOG.md, package.json, translations/ui-inventory/en.json
Create a new ‘Settings (Inventory): Create, edit, delete subject types’ permission to control the display and edit of the Inventory Subject types settings.
- Add a new permission
https://folio-org.atlassian.net/browse/UIIN-3009
=> UIIN-3009: Add inventory permission: Settings (Inventory): Create, edit, delete subject types

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/components/InstancesList/InstancesList.test.js, src/routes/InstancesRoute.test.js
Result list - add a sort indicator next to the column names for sortable fields and if the field is not currently sorted.
- pass the `showSortIndicator` prop to the `SearchAndSort` component;
- point correct `nonInteractiveHeaders`.
Removed unused fields, they are from the time when Search and Browse searches were on the same page.
https://github.com/folio-org/stripes-components/pull/2333
https://github.com/folio-org/stripes-smart-components/pull/1500
[UIIN-2986](https://folio-org.atlassian.net/browse/UIIN-2986)
https://github.com/user-attachments/assets/a92b05b1-ee16-4b77-8266-53b6893d53be
=> UIIN-2986: Add `showSortIndicator` prop to `SearchAndSort` to display sort indicator next to the column names, and add correct `nonInteractiveHeaders`

CHANGELOG.md, src/edit/holdings/HoldingsForm.js, src/edit/items/ItemForm.js
Trim call numbers when Creating/Editing/Deriving Holdings/Items.
New/updated Holdings/Items will not have trailing spaces
https://github.com/user-attachments/assets/45ade92a-aa85-4a01-81d4-42cc8c7d6d79
[UIIN-2889](https://folio-org.atlassian.net/browse/UIIN-2889)
=> UIIN-2889 Trim call numbers when Creating/Editing/Deriving Holdings/Items

src/edit/InstanceForm.js, src/edit/dateFields.js
disabled Dates fields when Instance has source MARC
https://github.com/user-attachments/assets/10e75f71-cab1-436c-a4f0-2f2b51cffedc
[UIIN-2849](https://folio-org.atlassian.net/browse/UIIN-2849)
=> UIIN-2849 disabled Dates fields when Instance has source MARC (follow-up)

CHANGELOG.md, src/Instance/InstanceEdit/InstanceEdit.js, src/components/InstancesList/InstancesList.js, src/edit/InstanceForm.js, src/edit/dateFields.js, src/edit/dateFields.test.js, src/providers/DataProvider.js, src/providers/DataProvider.test.js, src/utils.js, src/utils.test.js
When a user creates an Instance they can save dates without date type, but it should be saved as "No attempt to code"
If no dates are saved then date type should also be empty
When editing a record - date type cannot be unselected
https://github.com/user-attachments/assets/1c7fe1c5-58f8-4bae-9db7-1b93e461c22e
[UIIN-3034](https://folio-org.atlassian.net/browse/UIIN-3034)
=> UIIN-3034 Implement default Date type when not present - No attempt to code

CHANGELOG.md, src/Instance/ItemsList/ItemBarcode.js, src/View.css, src/hooks/index.js, src/hooks/useLocalStorageItems/index.js, src/hooks/useLocalStorageItems/useLocalStorageItems.js, src/hooks/useLocalStorageItems/useLocalStorageItems.test.js
* Since Poppy, the color of the linked item barcodes in the accordion under the holdings isn't changing once been clicked and viewed. This makes it hard to tell where the user has checked in a long list of items.
* It is necessary to use `<TextLink />` in order to have default options when click right mouse button (**Open link in new tab** etc).
* At the same time we need to switch affiliation when click on `<TextLink />` component. It's available only with `e.preventDefault()`.
* `e.preventDefault()` doesn't mark the link as visited.
* As the **TEMPORARY** solution it was decided to store items' ID in local storage.
* When we get rid of switching the affiliation ([UXPROD-4715](https://folio-org.atlassian.net/browse/UXPROD-4715)) we won't need to store IDs in local storage and …
=> UIIN-2994: Store item IDs in local storage in order to make it visited

CHANGELOG.md, src/Instance/InstanceDetails/InstanceDetails.js, src/Instance/InstanceDetails/InstanceSubjectView/InstanceSubjectView.js, src/Instance/InstanceDetails/InstanceSubjectView/InstanceSubjectView.test.js, src/Instance/InstanceEdit/ChildInstanceFields/ChildInstanceFields.test.js, src/Instance/InstanceEdit/ParentInstanceFields/ParentInstanceFields.test.js, src/components/UpdateItemOwnershipModal/UpdateItemOwnershipModal.test.js, src/edit/subjectFields.js, src/settings/TargetProfileForm.test.js
To updating the Instance View to display new subject fields.
- Add Subject source/type to instance view screen
- Update field names for create/edit screen
- Omit the 'Source specified in subfield $2' value for the subject source dropdown
https://folio-org.atlassian.net/browse/UIIN-2823
=> UIIN-2823: View -- Subject accordion instance UI changes

CHANGELOG.md, src/Instance/ItemsList/ItemsList.js
* When user have big barcode value (e.g. 40 characters) it represents as one big and long row. After the collapsing and expanding holdings accordion the barcode link become trimmed and not showing the “Copy” button. Make the Barcode with many characters (e.g. 40) be wrapped into the next row.
* Set default width for `Barcode` column.
[UIIN-2958](https://folio-org.atlassian.net/browse/UIIN-2958)
=> UIIN-2958: Make `Barcode` field wrapping to next row when there are many characters in the value

CHANGELOG.md, src/views/ItemView.js
* `.src/views/ItemView.js` has a potential NPE on line **753** if the patron record corresponding to the loan has been removed. 
* Check if `borrower` field exists. If not - leave borrower link as a `<NoValue />`.
[UIIN-3044](https://folio-org.atlassian.net/browse/UIIN-3044)
=> UIIN-3044: Display an item that has an open loan whose patron record has been removed

CHANGELOG.md, src/settings/InventorySettings/InventorySettings.js, src/settings/InventorySettings/InventorySettings.test.js
Display `Classification browse` settings for non-consortia.
[UIIN-3057](https://folio-org.atlassian.net/browse/UIIN-3057)
=> UIIN-3057: Display 'Classification browse' settings for non-consortia.

CHANGELOG.md, package.json, src/Instance/utils.js, src/common/hooks/useBoundPieces/useBoundPieces.js, src/common/hooks/useBoundPieces/useBoundPieces.test.js, src/common/hooks/usePiecesMutation/usePiecesMutation.js, src/common/hooks/usePiecesMutation/usePiecesMutation.test.js, src/common/hooks/useTenantKy/useTenantKy.js
When a user is on a member tenant and central ordering is enabled in the platform, it's necessary to fetch bound item-related pieces from the active tenant and the central one.
https://folio-org.atlassian.net/browse/UIIN-3054
https://github.com/user-attachments/assets/5266b308-0418-4a50-b2c5-5f34b820615d
---
non-ECS
https://github.com/user-attachments/assets/6e29d635-c20c-4268-b7af-249abd47f27d
=> UIIN-3054 Fetch bound item related pieces from the central tenant in the central ordering mode

CHANGELOG.md, src/components/BrowseResultsList/BrowseResultsList.test.js, src/components/BrowseResultsList/constants.js, src/components/BrowseResultsList/getBrowseResultsFormatter.js, src/components/BrowseResultsList/getBrowseResultsFormatter.test.js
We are updating the Instance schema to include more detailed information about subject headings - the subject source and the subject type. These new fields need to be added to the Inventory Browse results list. 
- Added two new columns after “Subject”: “Subject source” and “Subject type”
https://folio-org.atlassian.net/browse/UIIN-2960
=> UIIN-2960: Add subject source and subject type to Inventory subject browse results

CHANGELOG.md, src/ViewInstance.js, src/ViewInstance.test.js
The ‘Move items within an instance’ action is only designed for use with Instances on the currently affiliated tenant. As such, this action should only be displayed if an Instance has Holdings & Items is available on the member tenant that a user currently affiliated with during their session.
- Disallow 'Move items within an instance' and 'Move holdings/items to another instance' if no LOCAL Items/Holdings exist
https://folio-org.atlassian.net/browse/UIIN-3073
=> UIIN-3073: ECS - Disallow 'Move items within an instance' and 'Move holdings/items to another instance' if no LOCAL Items/Holdings exist

CHANGELOG.md, src/ViewInstance.js
Extend the functionality of UIIN-3051 by including current location information into redirects to Linked data editor, allowing navigation back to the Inventory.
https://folio-org.atlassian.net/browse/UIIN-3092
=> UIIN-3092: Include current location into redirects to Linked data editor

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/components/InstancesList/InstancesList.test.js, src/routes/InstancesRoute.js, test/jest/helpers/Harness.js
Date filters: Clear dates after pressing the reset search button even if values are invalid.
https://github.com/folio-org/stripes-smart-components/pull/1527
https://github.com/folio-org/stripes-inventory-components/pull/83
Use `ResetProvider` to publish the reset event from the `InstancesList` file and subscribe to it in filters. Use `nativeChangeFieldValue` to clear dates in filters.
[UIIN-3093](https://folio-org.atlassian.net/browse/UIIN-3093)
https://github.com/user-attachments/assets/ca890dd9-6021-431c-8dc9-bee7946d1293
=> UIIN-3093: Use `ResetProvider` to subscribe and publish the reset event and unsubscribe from it after a segment switch.

src/utils.js
- Fix [UIIN-3097](https://folio-org.atlassian.net/browse/UIIN-3097) by adding null safety on `currentPermission` object to prevent error screen.
=> [UIIN-3097] "Something went wrong" screen when opening shared FOLIO/MARC instances in Inventory on member tenant

CHANGELOG.md, src/ViewInstance.js, src/components/ViewInstance/MenuSection/RequestsReorderButton.js, src/components/ViewInstance/MenuSection/RequestsReorderButton.test.js
Update permission name after Review and cleanup Module Descriptor for ui-requests
Consistency update permission with ui-checkout ( https://folio-org.atlassian.net/browse/UIREQ-1156 )
Permissions renamed in according with Permissions naming convention ( https://folio-org.atlassian.net/wiki/spaces/FOLIJET/pages/156368925/Permissions+naming+convention )
https://issues.folio.org/browse/UIIN-3058
=> UIIN-3058: Update permission name after Review and cleanup Module Descriptor for ui-requests

CHANGELOG.md, src/components/BrowseResultsList/BrowseResultsList.test.js, src/components/BrowseResultsList/utils.js
Requires https://github.com/folio-org/stripes-inventory-components/pull/91
When clicking the subject heading hyperlink in the browse result it navigates to the inventory search result but shows results only by subject heading and not by source or type.
- Filter search results by subject source/type if exists.
https://folio-org.atlassian.net/browse/UIIN-3101
=> UIIN-3101: Browse | Number of titles in Subject browse results does not match the number of instances returned in search

CHANGELOG.md, src/ViewInstance.js
Change URI of a redirect to Linked data editor for supported MARC resources from `.../edit` to `.../preview` to support the changed scope of relevant tickets.
https://folio-org.atlassian.net/browse/UIIN-3107
=> UIIN-3107: Change URI of a redirect to Linked data editor

CHANGELOG.md, src/settings/SubjectSourcesSettings.js, src/settings/SubjectTypesSettings.js
Records with the `consortium` source are considered shared records and mustn't be editable outside the consortium manager.
Add `consortium` source type for suppression.
https://folio-org.atlassian.net/browse/UIIN-3112
https://github.com/user-attachments/assets/1bf59bce-cee1-4740-ab7b-ba29b49cb111
=> UIIN-3112 Suppress edit and delete actions of subject types and sources for 'consortium' source

CHANGELOG.md, package.json
To add missing 'replaces' array to refactored ui permissions.
- Add `replaces` to `package.json` for replaces UI permissions
https://folio-org.atlassian.net/browse/UIIN-3110
=> UIIN-3110: Add 'replaces' array to refactored ui permissions

CHANGELOG.md, src/ViewInstance.js
Update quick-marc permission name to meet https://github.com/folio-org/ui-quick-marc/pull/751
https://folio-org.atlassian.net/browse/UIIN-3111
=> UIIN-3111: Update quick-marc permission name.

CHANGELOG.md, src/views/ItemView.js, src/views/ItemView.test.js
[UIIN-3105](https://folio-org.atlassian.net/browse/UIIN-3105): ECS: Prevent Item affiliation ownership change if it is attached to a local PO line
https://github.com/user-attachments/assets/90d4bb3d-fac6-4599-a528-9b9a29f76992
=> UIIN-3105: ECS: Prevent Item affiliation ownership change if it is attached to a local PO line

CHANGELOG.md, src/views/ItemView.js
* `Mark as ...` action items in Item action menu are not displayed after renaming the permissions.
[UIIN-3114](https://folio-org.atlassian.net/browse/UIIN-3114)
=> UIIN-3114: Display correctly `Mark as ...` action items in Item action menu

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/components/InstancesList/InstancesList.test.js
Send `staffSuppress` filter and `sort` value in URL at the same time to avoid rewriting during mount and update.
Set the necessary search params in `const searchParams = new URLSearchParams(location.search);` and only then do `history.replace`.
[UIIN-3099](https://folio-org.atlassian.net/browse/UIIN-3099)
https://github.com/user-attachments/assets/d398121c-3e41-4e63-af83-8fe94a55a6c0
=> UIIN-3099: Run `history.replace` once during component mount and update to avoid URL rewriting.

CHANGELOG.md, src/common/hooks/useInstance.js
After instance sharing, the user gets an instance shadow copy instead of a shared instance. It happens because mod-search returned a response with `shared: true` but `tenantId: memberTenant` instead of the central tenant.
- Check if instance is shared, if so - make the next request to mod-inventory with `x-okapi-tenant: centralTenant`
https://folio-org.atlassian.net/browse/UIIN-3115
=> UIIN-3115: ECS | "FOLIO/MARC-shared" source is displayed in manually shared instance record

CHANGELOG.md, src/Instance/MoveHoldingContext/MoveHoldingContext.js
* The item should be moved to the holdings of another instance and displayed in the "Holdings" accordion, but the message **"1 item has been successfully moved."** appeared and the item was not actually moved.
* If user moves holdings then set to `movingItems` holdings ids, otherwise - items ids.
* Check if `holdingIds` is empty in `checkHasMultiplePOLsOrHoldings` function. Previously, when `holdingIds` was empty, it returned all the PO lines not related to current instance. 
[UIIN-3102](https://folio-org.atlassian.net/browse/UIIN-3102)
https://github.com/user-attachments/assets/2a526b28-cd7a-4f50-a570-89735cedc2cb
=> UIIN-3102: The item cannot be moved to another holdings associated with another instance

CHANGELOG.md, src/hooks/useMemberTenantHoldings/useMemberTenantHoldings.js
Consortial holdings accordion is empty for shared instance if a user does not have affiliations/permissions.
- Fix checking of empty holdings array for limited holdings info.
https://folio-org.atlassian.net/browse/UIIN-3113
=> UIIN-3113: ECS | Instance details pane does not contain all tenants when user does not have affiliations / permissions in all tenants

CHANGELOG.md, src/utils.js, src/utils.test.js
Use optional chaining when evaluating subPermissions to avoid potential NPEs if a permission does not have any subPermissions.
Refs [UIIN-3124](https://folio-org.atlassian.net/browse/UIIN-3124)
=> UIIN-3124 cautiously evaluate subPermissions in hasMemberTenantPermission

CHANGELOG.md, src/utils.js
* Remove **409: Server communication problem. Please try again** error message when optimistic locking error is occured. Show optimistic locking banner instead.
* On Eureka environment `Content-type` is `text/plain; charset=UTF-8`. So, we need to add more flexible check for `Content-type`, using `includes` insted of `===`
[UIIN-3127](https://folio-org.atlassian.net/browse/UIIN-3127)
=> UIIN-3127: Display informative error message when editing same instance, holdings, item in two tabs

CHANGELOG.md, package.json
* Added `users.collection.get` to `subPermissions` in order to get users list when the following permissions are assigned separately:
**Settings (Inventory): Create, edit, delete subject sources**
**Settings (Inventory): Create, edit, delete subject types**
**Settings (Inventory): Create, edit, delete ILL policies**
**Settings (Inventory): Create, edit, delete call number types**
**Settings (Inventory): Create, edit, delete holdings sources**
**Settings (Inventory): Create, edit and delete HRID handling**
[UIIN-3144](https://folio-org.atlassian.net/browse/UIIN-3144)
=> UIIN-3144: Display user's name instead of `Unknown user` in Last updated field in `Settings` for member tenant

CHANGELOG.md, src/ViewInstance.js
This PR addresses [UIIN-3146](https://folio-org.atlassian.net/browse/UIIN-3146)
The API URI `GET /resource/check/{inventoryId}/supported` has been changed to `GET /linked-data/inventory-instance/{inventoryId}/import-supported` in [mod-linked-data](https://github.com/folio-org/mod-linked-data)  as part of [MODLD-585](https://folio-org.atlassian.net/browse/MODLD-585). This Pull request makes the corresponding change in ui-inventory codebase.
Update the API URI in [ViewInstance.js](https://github.com/folio-org/ui-inventory/compare/pjacob/UIIN-3146?expand=1#diff-a962523d8df448cf50db88af841c0c0602e66f93913b469671082cea6cf85667)
Related tickets: 
1. [MODLD-585](https://folio-org.atlassian.net/browse/MODLD-585)
2. [UILD-428](https://folio-org.atlassian.net/browse/UILD-428)
=> UIIN:3146: Update API URI for checkCanBeOpenedInLinkedData manifest

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/components/InstancesList/InstancesList.test.js
Use default sorting only if it is not present in the URL (reset button pressed or sorting manually removed).
- `componentDidMount`: if `sort` option is not present (manually removed), add it to `searchParams`;
- `componentDidUpdate`: if `sort` option is not present (reset button hit), add it to `searchParams`.
[UIIN-3137](https://folio-org.atlassian.net/browse/UIIN-3137)
https://github.com/user-attachments/assets/f76c8a0d-7ca4-4861-8f99-1a9d946c2ffa
=> UIIN-3137: Set default sorting to URL in `componentDidMount` and `componentDidUpdate` if it is missing.

CHANGELOG.md, src/Instance/InstanceEdit/InstanceField/InstanceField.test.js, src/Instance/ItemsList/ItemsListContainer.test.js, src/Instance/ItemsList/tests/ItemsList.test.js, src/components/ViewSource/ViewSource.test.js
* Use `act` from `@folio/jest-config-stripes/testing-library/react` instead of `react-dom/test-utils`
[UIIN-2888](https://folio-org.atlassian.net/browse/UIIN-2888)
=> UIIN-2888: React 19: refactor away from react-dom/test-utils

CHANGELOG.md, src/components/BrowseResultsList/utils.js
Handle `null` `typeIds` in `browse/config/instance-classification` response. This can happend after a migration.
https://github.com/user-attachments/assets/0867cc5b-1071-4eb0-a62f-f69cec889f94
[UIIN-3161](https://folio-org.atlassian.net/browse/UIIN-3161)
=> UIIN-3161 Handle `null` `typeIds` in `browse/config/instance-classification` response

CHANGELOG.md, package.json
Inventory UI makes API call to the following API in linked-data module
[GET linked-data/inventory-instance/:{id}/import-supported](https://github.com/folio-org/mod-linked-data/blob/master/descriptors/ModuleDescriptor-template.json#L95)
Per [stripes documentation](https://github.com/folio-org/stripes/blob/8790eaaccc2fa58f5500570f5bdc6a47c7a53ff3/doc/dev-guide.md), the optional interfaces that UI module uses should be declared in `optionalOkapiInterfaces` section of package.json file. 
Purpose of this PR is to update `optionalOkapiInterfaces` section of the package.json with the following
`"linked-data": "1.0"`
=> UIIN-3106: Add 'linked-data' interface to 'optionalOkapiInterfaces'

CHANGELOG.md, src/Holding/DuplicateHolding/DuplicateHolding.js, src/Holding/EditHolding/EditHolding.js, src/Instance/ItemsList/ItemBarcode.js, src/Instance/utils.js, src/Item/DuplicateItem/DuplicateItem.js, src/Item/EditItem/EditItem.js, src/ViewHoldingsRecord.js, src/ViewHoldingsRecord.test.js, src/routes/ItemRoute.js, src/routes/ViewHoldingRoute.js, src/views/ItemView.js
* Remove errors after cancel edit/duplicate or 'Save & Close' consortial holdings/items.
* Add `initialTenantId` prop in order to have the ability to return to the initial tenant after cancelling edit/duplicate holdings/items.
[UIIN-3167](https://folio-org.atlassian.net/browse/UIIN-3167)
https://github.com/user-attachments/assets/feba3f64-daed-41ae-a873-7c5606f518a2
https://github.com/user-attachments/assets/4da5917f-2adf-4f94-8758-71f26fc4b17e
https://github.com/user-attachments/assets/723ed14c-da36-48a2-bffd-1db6e69af614
https://github.com/user-attachments/assets/67d35a62-b068-49a0-a6af-1d4fe8e33073
=> UIIN-3167: Fix errors after cancel edit/duplicate or 'Save & Close' consortial holdings/items 

CHANGELOG.md, src/views/ItemView.js, src/views/ItemView.test.js, translations/ui-inventory/en.json
Remove information icon and hover over text next to the field “Effective call number”.
- Remove info popover.
https://folio-org.atlassian.net/browse/UIIN-3131
=> UIIN-3131: Remove hover-over text next to "Effective call number" on the Item record detail view

CHANGELOG.md, src/reports/IdReportGenerator.js, src/reports/InTransitItemsReport.js, src/reports/InTransitItemsReport.test.js
`exportCsv` from `stripes-util` is deprecated. Changed imports to use `exportToCsv` from `stripes-components`
[UIIN-3025](https://folio-org.atlassian.net/browse/UIIN-3025)
=> UIIN-3025 Change import of `exportToCsv` from `stripes-util` to `stripes-components`

CHANGELOG.md, src/ViewInstance.js
* Allow to display of SHARED Instances when selecting the ‘Move To’ Instance location when invoking 'Move holdings/items to another instance' action
* Removed flag `suppressSharedFacet`
[UIIN-3198](https://folio-org.atlassian.net/browse/UIIN-3198)
https://github.com/user-attachments/assets/19e66c40-fd43-4317-a93d-408b54bd7f52
https://github.com/user-attachments/assets/9c2ff4bd-7380-4db4-93c1-54eda858f33b
=> UIIN-3198: Display Shared facet when user opens 'Move holdings/items to another instance' modal

CHANGELOG.md, src/ViewInstance.js
* Allow to display of ‘Move holdings/items to another instance' action on Instances that are ‘SHARED’.
* Removed `!isShared` condition from `canMoveHoldingsItemsToAnotherInstance` 
[UIIN-3188](https://folio-org.atlassian.net/browse/UIIN-3188)
=> UIIN-3188: ECS - Allow 'Move holdings/items to another instance' if instance is shared

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/components/InstancesList/InstancesList.test.js
When users are trying to find the item by barcode then they are getting error popup "Invalid token: User with id ... does not exist". It happens when there is only 1 search result and the item details page is trying to open, but the request failes because a user is not affiliated with the item's member tenant.
- Check if a user is affiliated with the item's member tenant before sending a request to get item details.
https://folio-org.atlassian.net/browse/UIIN-3187
=> UIIN-3187: ECS: Disable opening item details if a user is not affiliated with item's member tenant

CHANGELOG.md, src/common/hooks/useInstance.js, src/common/hooks/useInstance.test.js, src/common/hooks/useSearchInstanceByIdQuery/useSearchInstanceByIdQuery.js, src/common/hooks/useSearchInstanceByIdQuery/useSearchInstanceByIdQuery.test.js
Detail view of created Instance record is not loaded after saving. White screen displays in the third pane.
The problem is not reproduced consistently. GET to ‘/search/instances’ returns 0 records right after Instance creation. But instance is actually created.
- Make a pre-call to mod-search only if a user is in consortium mode to get info about the instance's tenant and shared status, otherwise make a call right to mod-inventory
- If a user is in consortium mode and mod-search returns the result with empty data even if the instance was successfully created, then make 3 attempts until there is filled data with a 3-second delay.
- Update unit tests
https://folio-org.atlassian.net/browse/UIIN-3194
=> UIIN-3194: Detail view of created Instance record is not loaded after saving

CHANGELOG.md, src/views/ItemView.js, src/views/ItemView.test.js, src/views/VersionHistory/VersionHistory.js, src/views/VersionHistory/index.js, translations/ui-inventory/en.json
* Add Version history button and Version history pane to details view of Item.
* The list of version history cards will be created in scope of [UIIN-3175](https://folio-org.atlassian.net/browse/UIIN-3175).
* Created `VersionHistory` component and use it in `ItemView` component.
* Added `VersionHistoryButton` as `lastMenu` for item view pane.
[UIIN-3172](https://folio-org.atlassian.net/browse/UIIN-3172)
=> UIIN-3172: Add Version history button and Version history pane to details view of Item

CHANGELOG.md, src/components/BrowseResultsList/BrowseResultsList.test.js, src/components/BrowseResultsList/getBrowseResultsFormatter.test.js, src/components/BrowseResultsList/utils.js, src/components/InstanceFiltersBrowse/instanceFiltersBrowse.test.js, src/hooks/index.js, src/hooks/useCallNumberBrowseConfig/index.js, src/hooks/useCallNumberBrowseConfig/useCallNumberBrowseConfig.js, src/hooks/useCallNumberBrowseConfig/useCallNumberBrowseConfig.test.js, src/providers/DataProvider.js, src/providers/DataProvider.test.js
In order to only return instances with the call number and call number type selected from call number browse settings, we need to use "Query search". When a user clicks on a call number title, they should be redirected to the Search page with a "Query search" option. It should have a call number query that takes into account the selected call number types.
The tests will pass after [PR](https://github.com/folio-org/stripes-inventory-components/pull/104) is merged, I didn't mock constants because tests will not catch the issue related to them if the constants become incorrect.
Build a query in `getCallNumberQuery`. Take selected call number types from `useCallNumberBrowseConfig`.
[UIIN-3205](https://folio-org.atlassian.net/browse/UIIN-3205) …
=> UIIN-3205: Add `getCallNumberQuery` function to build a query string based on the call number and its type.

CHANGELOG.md, src/ViewHoldingsRecord.js, src/ViewHoldingsRecord.test.js, translations/ui-inventory/en.json
* Add Version history button and Version history pane to details view of Item.
* The list of version history cards will be created in scope of [UIIN-3174](https://folio-org.atlassian.net/browse/UIIN-3174).
* Used `VersionHistory` component and in ItemView component in order to create version history pane.
* Added `VersionHistoryButton` as `lastMenu` for item view pane.
* Added unit tests
* Removed unused translation
[UIIN-3171](https://folio-org.atlassian.net/browse/UIIN-3171)
=> UIIN-3171: Add Version history button and Version history pane to details view of Holdings

CHANGELOG.md, src/settings/CardsPerVersionHistoryPage/CardsPerVersionHistoryPage.js, src/settings/CardsPerVersionHistoryPage/CardsPerVersionHistoryPage.test.js, src/settings/CardsPerVersionHistoryPage/components/CardsPerVersionHistoryPageForm/CardsPerVersionHistoryPageForm.css, src/settings/CardsPerVersionHistoryPage/components/CardsPerVersionHistoryPageForm/CardsPerVersionHistoryPageForm.js, src/settings/CardsPerVersionHistoryPage/components/CardsPerVersionHistoryPageForm/CardsPerVersionHistoryPageForm.test.js, src/settings/CardsPerVersionHistoryPage/components/CardsPerVersionHistoryPageForm/index.js, src/settings/CardsPerVersionHistoryPage/components/index.js, src/settings/CardsPerVersionHistoryPage/index.js, src/settings/InventorySettings/InventorySettings.js, translations/ui-inventory/en.json
Create Inventory settings to configure number of cards in version history
This ticket will be split into 2 parts: one for react component and another for hooks to fetch/save data
This is the react components PR.
The new setting will exist under a new group "Version history"
Two new components are added: `<CardsPerVersionHistoryPage>` and `<CardsPerVersionHistoryPageForm>`
`<CardsPerVersionHistoryPageForm>` defines the form, and `<CardsPerVersionHistoryPage>` uses it and with the second PR will handle the requests logic via hooks.
[UIIN-3213](https://folio-org.atlassian.net/browse/UIIN-3213)
=> UIIN-3213 Create Inventory settings to configure number of cards in version history

CHANGELOG.md, src/components/BrowseResultsList/constants.js
Set correct widths for Call number browse results columns
[UIIN-3229](https://folio-org.atlassian.net/browse/UIIN-3229)
=> UIIN-3229 Set correct widths for Call number browse results columns

CHANGELOG.md, src/components/BrowseResultsList/getBrowseResultsFormatter.test.js, src/components/BrowseResultsList/utils.js
Search the same number of Instances, specified in the Browse “Number of titles” column. 
Use `itemFullCallNumbers` instead of `itemNormalizedCallNumbers`. `itemNormalizedCallNumbers` uses the right truncation during the search while `itemFullCallNumbers` does an exact match.
[UIIN-3234](https://folio-org.atlassian.net/browse/UIIN-3234)
=> UIIN-3234: Change `itemNormalizedCallNumbers` to `itemFullCallNumbers` in `getCallNumberQuery`.

CHANGELOG.md, package.json, src/components/ViewSource/ViewSource.js, src/components/ViewSource/ViewSource.test.js, test/jest/__mock__/stripesMarcComponents.mock.js
MARC Bib > View Source > Display Version History pane with an empty Version History component
Actual implementation with real requests will be done after the AuditLogPane component has been implemented
https://github.com/user-attachments/assets/0633ecf2-7800-428b-9232-83fbad3e62d0
[UIIN-3235](https://folio-org.atlassian.net/browse/UIIN-3235)
https://github.com/folio-org/stripes-marc-components/pull/38
=> UIIN-3235 MARC Bib > View Source > Display Version History pane with an empty Version History component

CHANGELOG.md, src/Instance/InstanceDetails/InstanceDetails.js, src/Instance/InstanceDetails/InstanceDetails.test.js
* On Instance view in Inventory, when you click the 'Version history' icon to open the Version history view in the 4th pane, the following should also occur in the 3rd pane:
- `Actions` menu button disappears
- `Tags` icon become greyed out and unclickable
- `Version history` icon become greyed out and unclickable
* Hide/disable buttons when `isVersionHistoryOpen` is true.
[UIIN-3176](https://folio-org.atlassian.net/browse/UIIN-3176)
https://github.com/user-attachments/assets/7d2d1c01-c24f-4f11-81f0-1edbf761d799
=> UIIN-3176: Instance: Suppress action menu and disable buttons when click Change log icon

CHANGELOG.md, src/ViewHoldingsRecord.js, src/ViewHoldingsRecord.test.js
* On Holdings view in Inventory, when you click the 'Version history' icon to open the Version history view in the 2nd pane, the following should also occur in the 1st pane:
- Actions menu button disappears
- Version history icon become greyed out and unclickable
* Hide/disable buttons when `isVersionHistoryOpen` is true.
[UIIN-3177](https://folio-org.atlassian.net/browse/UIIN-3177)
=> UIIN-3177: Holdings: Suppress action menu and disable buttons when click Change log icon

CHANGELOG.md, src/views/ItemView.js, src/views/ItemView.test.js
* On Item view in Inventory, when you click the 'Version history' icon to open the Version history view in the 2nd pane, the following should also occur in the 1st pane:
- Actions menu button disappears
- Version history icon become greyed out and unclickable
* Hide/disable buttons when `isVersionHistoryOpen` is true.
[UIIN-3178](https://folio-org.atlassian.net/browse/UIIN-3178)
=> UIIN-3178: Item: Suppress action menu and disable buttons when click Change log icon

CHANGELOG.md, src/components/BrowseResultsList/BrowseResultsList.test.js, src/components/BrowseResultsList/utils.js, src/components/InstanceFiltersBrowse/InstanceFiltersBrowse.js, src/components/InstanceFiltersBrowse/instanceFiltersBrowse.test.js
The Shared facet returns an error in call numbers, it should use `instances.shared` in the query parameter, we cannot simply specify the necessary value for it, since it is also used in the Search tab. So a new facet variable `FACET.CALL_NUMBERS_SHARED` is created which will use `instances.shared`.
Tests will pass after the https://github.com/folio-org/stripes-inventory-components/pull/112 is merged.
https://github.com/folio-org/stripes-inventory-components/pull/112
https://folio-org.atlassian.net/browse/UIIN-3254
=> UIIN-3254: Use the name `CALL_NUMBERS_SHARED` for the `Shared` facet instead of `SHARED`.

CHANGELOG.md, src/components/ImportRecordModal/ImportRecordModal.js
Without a `limit` clause, CQL will only return 10 records (the default) even when more than 10 identifiers are specifically passed in the query. This suprises me, but apparently it is by design.
Follows up on PR #1820 where we added a `limit` clause to retrieve all providers; this PR makes sure we retrieve all a provider's job profiles. 
Refs [UIIN-3257](https://folio-org.atlassian.net/browse/UIIN-3257)
=> UIIN-3257 include limit param in jobProfiles query

CHANGELOG.md, src/edit/InstanceForm.js
To avoid user error, it has been recommended that we move the ‘Set for deletion’ checkbox in Instance Edit view to the 4th space in its current row, rather than the 1st space.
- Move `Set for deletion` checkbox to the end of the row
https://folio-org.atlassian.net/browse/UIIN-3259
=> UIIN-3259: Move `set for deletion` checkbox field to 4th space in a row

CHANGELOG.md, src/settings/HRIDHandling/HRIDHandlingSettings.js
Annotations _should_ be fine, but our esbuild-loader config chokes on them. Luckily, they are easy to replace.
Refs [UIIN-3271](https://folio-org.atlassian.net/browse/UIIN-3271)
=> UIIN-3271 replace annotation with simple wrappers

CHANGELOG.md, src/components/ViewSource/ViewSource.test.js, src/hooks/useHoldingAuditDataQuery/useHoldingAuditDataQuery.js, src/hooks/useInstanceAuditDataQuery/useInstanceAuditDataQuery.js, src/hooks/useInventoryVersionHistory/constants.js, src/hooks/useInventoryVersionHistory/useInventoryVersionHistory.js, src/hooks/useInventoryVersionHistory/useInventoryVersionHistory.test.js, src/hooks/useItemAuditDataQuery/useItemAuditDataQuery.js
When a record is first created, we do not need to show the field-level creation data. We only need to show that the card represents the original version of the record. 
- Instead of filtering out versions with `action = CREATE`, show it as original version.
Related PR in `stripes-components` https://github.com/folio-org/stripes-components/pull/2436
https://folio-org.atlassian.net/browse/UIIN-3270
=> UIIN-3270: Display Original version card of the audit log with no field changes

CHANGELOG.md, src/edit/items/ItemForm.js
https://folio-org.atlassian.net/browse/UIIN-3274
Preconditions Settings > Inventory > Number generator options
- Number generator for accession number and call number are enabled either On, field editable or On, field not editable
- And checkbox “Use the same generated number for accession number and call number” is selected 
In inventory item record in edit or add view when opening the modal by clicking the button Generate accession and call numbers the heading of the modal is not displayed correctly  
Current:
_ui-inventory.numberGenerator.accessionAndCallNumberGenerator_
expected:
_Generate accession and call numbers_
=> UIIN-3274: Fix bug in modal heading

CHANGELOG.md, src/Holding/HoldingsMarc/HoldingsMarcContainer.js, src/components/ViewSource/ViewSource.js, src/components/ViewSource/ViewSource.test.js, src/hooks/useAuditSettings/useAuditSettings.js
Display the history feature toggle/icon only if it is enabled in settings. The shared record should call for settings with the central tenant id, local record with the local tenant id.
[UIIN-3266](https://folio-org.atlassian.net/browse/UIIN-3266)
https://github.com/user-attachments/assets/8ef122d3-e0af-4e3b-9644-b823328d1cc8
=> UIIN-3266: `ViewSource` - add `tenantId` to `useAuditSettings`.

src/settings/CardsPerVersionHistoryPage/CardsPerVersionHistoryPage.js, src/settings/CardsPerVersionHistoryPage/components/CardsPerVersionHistoryPageForm/CardsPerVersionHistoryPageForm.js
Display the `Version history` header instead of `Cards per page` in the `Version history` settings.
[UIIN-3213](https://folio-org.atlassian.net/browse/UIIN-3213)
=> UIIN-3213: Update titles in `CardsPerVersionHistoryPage` to reflect version history (follow-up).

CHANGELOG.md, package.json
The major version was inadvertently bumped to 14 in PR #2769 and then reverted down to 13 in PR #2793. Although the present release was not intended to be a major release, now that some v14.x releases have already been published to CI we are better off just keeping that change rather than trying to undo it, which is likely to be even more disruptive.
=> bump major to v14.0.0 for new development work

CHANGELOG.md, src/Instance/InstanceDetails/InstanceDetails.js
* The header of the Instance details pane is not changed after overlaying source bibliographic record process
Update dependencies in `paneTitle`
[UIIN-3282](https://folio-org.atlassian.net/browse/UIIN-3282)
https://github.com/user-attachments/assets/5b8fd831-8542-49cf-89db-3cf82a3a874a
=> UIIN-3282: Update instance header after overlaying source bibliographic record process

CHANGELOG.md, src/Instance/InstanceDetails/InstanceDetails.js, src/Instance/InstanceVersionHistory/InstanceVersionHistory.js
* We should show “Shared” label instead of “Original version” in the first card for Instance records which were promoted to be Shared.
* Add `useSharedInstancesQuery` hook to determine if an instance is shared from a local one to display "Shared" in the version history original card
[UIIN-3300](https://folio-org.atlassian.net/browse/UIIN-3300)
=> UIIN-3300: Display `Shared` label for promoted to be shared FOLIO records

CHANGELOG.md, src/hooks/useInventoryVersionHistory/useInventoryVersionHistory.js, src/hooks/useInventoryVersionHistory/useInventoryVersionHistory.test.js
The "Source" field in the history pane shouldn't be empty for member tenants if changes are made by another member tenant (the College should see the user who made changes in the University).
https://folio-org.atlassian.net/browse/UIIN-3321
=> UIIN-3321: Use central tenant id in `useUsersBatch` to retrieve all users.

src/ViewInstance.js
Need to wait for central tenant permissions to load because it is also a condition to show loading pane. Focusing before permissions are loaded has no effect on the third pane.
[UIIN-3122](https://folio-org.atlassian.net/browse/UIIN-3122)
=> UIIN-3122 wait for central tenant permissions to load before focusing third pane (follow-up)

src/components/InstanceFiltersBrowse/InstanceFiltersBrowse.js
For Browse Effective Location filter show the top border only for member tenants. In central tenant this is the only filter so the border is not needed
Member tenant
Central tenant
[UIIN-3301](https://folio-org.atlassian.net/browse/UIIN-3301)
=> UIIN-3301 Browse Effective location - show separator only for member tenants (follow-up)

CHANGELOG.md
`v13.0.2` was skipped due to a release workflow issue: [FOLIO-4281](https://folio-org.atlassian.net/browse/FOLIO-4281)
=> Release v13.0.3

CHANGELOG.md, src/ViewInstance.js, src/ViewInstance.test.js
* Currently, the `Set record for deletion` action is set to be hidden if an Instance has both `Staff suppressed` and `Suppress from discovery` set to **true**. We should instead hide this action only if the `Set for deletion` field has been set to **true** for an instance.
[UIIN-3317](https://folio-org.atlassian.net/browse/UIIN-3317)
https://github.com/user-attachments/assets/21d63420-ff73-4964-87a0-c32bace11e10
=> UIIN-3317: Hide Set for deletion action when Set for deletion field value is true

CHANGELOG.md, src/edit/InstanceForm.js, src/edit/holdings/HoldingsForm.js, src/edit/items/ItemForm.js
When editing forms in Inventory, changing some text box and then clicking Enter key - the form is submitting which is not expected behavior.
- Moved `form` tag under `Pane` component to suppress event propagation
https://folio-org.atlassian.net/browse/UIIN-3377
=> UIIN-3377: Instance/holdings/items form - moved `form` under `Pane` component to suppress form submitting on Enter key click event

CHANGELOG.md, src/components/ViewSource/ViewSource.js, src/components/ViewSource/ViewSource.test.js
MARC Holdings doesn't support shared records yet so we should always request MARC Holdings records from a current tenant.
[UIIN-3423](https://folio-org.atlassian.net/browse/UIIN-3423)
=> UIIN-3423 Use current tenant for MARC Holdings requests in View Source.

CHANGELOG.md, src/Item/hooks/useItemDetailsData/useItemDetailsData.js, test/jest/__mock__/stripesSmartComponents.mock.js
* The `Service point` should be displayed in the `Circulation history` section in the item view page after `check in` action.
* Update dependency for `circulationHistory` in order to get updated data.
[UIIN-3417](https://folio-org.atlassian.net/browse/UIIN-3417)
=> UIIN-3417: Display Service point in the Circulation history section in the item view page after check in action

CHANGELOG.md, src/Instance/ViewInstance/ViewInstance.js, src/Instance/ViewInstance/components/InstanceActionMenu/InstanceActionMenu.js, src/Instance/hooks/useInstancePermissions/useInstancePermissions.js
`useInstancePermissions` hook referenced `this.hasCentralTenantPerm` in code, which caused an exception.
=> UIIN-3382 fix issue with checking for central tenant permissions (follow-up)

CHANGELOG.md, src/Item/hooks/useItemUpdateOwnership/useItemUpdateOwnership.js
No request sends when user clicks on “Confirm” button in “Update ownership of items” modal.
- Add missing `useCallback` dependencies to `onConfirmHandleUpdateOwnership` handler
https://folio-org.atlassian.net/browse/UIIN-3440
=> UIIN-3440: ECS | No request send when user confirms ownership update of item record

CHANGELOG.md, src/Instance/ViewInstance/ViewInstance.js
User can not see holdings in data tenant on shared instance.
- Provide correct tenant to get member tenant holdings for instance (not central tenant because it's shared instance, but member tenant)
https://folio-org.atlassian.net/browse/UIIN-3447
=> UIIN-3447: User can not see holdings in data tenant on shared instance

CHANGELOG.md, src/components/InstancesList/InstancesList.js, src/constants.js
Open Item record detail view when exact match is found via Keyword search option in Item tab.
Items keywork option will search items only by hrid, uuid and barcode because those are the available item search parameters.
https://github.com/user-attachments/assets/e9ee15a1-fc8f-495e-8ce6-98bc98561e0b
[UIIN-3416](https://folio-org.atlassian.net/browse/UIIN-3416)
=> UIIN-3416 Open Item record detail view when exact match is found via Keyword search option in Item tab

src/components/InstancesList/InstancesList.js, src/settings/DisplaySettings/DisplaySettings.js
show all columns when Default Columns setting does not exist. 
show all checkboxes as checked if a setting hasn't been saved yet.
send empty array as the setting value when a user unchecks all checkboxes
[UIIN-3422](https://folio-org.atlassian.net/browse/UIIN-3422)
=> UIIN-3422 show all columns when Default Columns setting does not exist (follow-up)

CHANGELOG.md, src/hooks/useHoldingItemsQuery.js, src/hooks/useHoldingItemsQuery.test.js
* Fix sorting of Order column. Make sure sorting by the rest of enabled columns also works as expected.
* When sorting by Order column we need to change query like this `.../order/number/...`
[UIIN-3478](https://folio-org.atlassian.net/browse/UIIN-3478)
https://github.com/user-attachments/assets/f0dd4cbd-b363-4f0a-8d04-3ee3385d48eb
=> UIIN-3478: Fix sorting for Items on Instance details page

CHANGELOG.md, package.json
Added a permission to delete records from SRS to a "Inventory: All permissions" and "Inventory: View, create, edit, delete holdings"
Users were unable to delete MARC Holdings records with these permissions assigned
[UIIN-3434](https://folio-org.atlassian.net/browse/UIIN-3434)
=> UIIN-3434 Added a permission to delete records from SRS to a "Inventory: All permissions" and "Inventory: View, create, edit, delete holdings"

CHANGELOG.md, src/Instance/ItemsList/DraggableItemsList.js, src/Instance/ItemsList/ItemsList.js, src/dnd/hooks/useDndHandlers.js, src/hooks/index.js, src/hooks/useItemsUpdateMutation/index.js, src/hooks/useItemsUpdateMutation/useItemsUpdateMutation.js, src/hooks/useItemsUpdateMutation/useItemsUpdateMutation.test.js, test/jest/__mock__/stripesCore.mock.js
When dragging and dropping item/items within the same holding it is required to send patch request to save new order on the server.
- Implement new mutation hook to update items
- Call patch request on dragEnd event
- Disable checkboxes when items are fetching
https://folio-org.atlassian.net/browse/UIIN-3454
https://github.com/user-attachments/assets/14c18b91-c642-4453-b095-640f3ecadde2
=> UIIN-3454: Handle saving new items order on dragEnd event

CHANGELOG.md, src/Item/DuplicateItem/DuplicateItem.js
When a user duplicates an item, the new item receives the same order value as the original. This can lead to confusion in the list of items.
- Omit `order` value during duplication of item.
https://folio-org.atlassian.net/browse/UIIN-3518
=> UIIN-3518: Fix duplicating an item order value when duplicating an item

CHANGELOG.md, src/Instance/ItemsList/ItemsList.js
The drag-and-drop functionality for manually moving items between holdings was broken after the implementation of UIIN-3486. This affects users who cannot move items between different holdings within a single instance.
- Remove `initializeOriginalOrders` from `useEffect` deps that caused items state to get reassigned on every change.
https://folio-org.atlassian.net/browse/UIIN-3519
=> UIIN-3519: Fix moving items to another holdings within the same instance is broken

CHANGELOG.md, src/Holding/DuplicateHolding/DuplicateHolding.js
[UIIN-3513](https://folio-org.atlassian.net/browse/UIIN-3513)
As a librarian I would like to generate call numbers via number generator while duplicating holdings records. 
Inventory > View holdings > Actions > Duplicate
**Current**
Right now no number generator functionality is available in the duplicate holdings view. Due to a misunderstanding of those different screens, the number generator functionality in this duplicate view has not yet been realized.
**Expected**
While duplicating a holdings record the button for the Call number number generator is visible and functional, when user has the appropriate permissions/capability sets and the number generator for Call number is enabled in Settings > Inventory > Holdings, Items > Number generator options
Number generator functionality in …
=> UIIN-3513: Add number generators to duplicate holding

CHANGELOG.md, src/Item/DuplicateItem/DuplicateItem.js
[UIIN-3514](https://folio-org.atlassian.net/browse/UIIN-3514)
As a librarian I would like to generate Call numbers, Accession numbers and/or Item barcodes via number generators while duplicating item records.
Inventory > View item > Actions > Duplicate
**Current**
Right now no number generator functionality is available in the duplicate item view. Due to a misunderstanding of those different screens, the number generator functionality in this duplicate view has not yet been realized.
**Expected**
While duplicating an item record the buttons for the Call number, Accession number and Item barcode number generators are visible and functional, when user has the appropriate permissions/capability sets and the number generator for Call number, Accession number and/or Item barcode is enabled in …
=> UIIN-3514: Add number generators to duplicate item
